### ISSUE TITLE
Can not import Source Storage with kube2iam

### ISSUE THREAD

**Issue by xhuaustc** [heartexlabs/label-studio#1025]
I set up kube2iam service in my k8s cluster. After binding the correct role to the label studio instance, I created source storage left Access Key ID/Secret Access Key/Session Token blank, but failed with the logs:

> [2021-06-05 00:20:29,308] [core.utils.common::custom_exception_handler::79] [ERROR] f9a4709c-15af-4ea9-8352-b6ae051534ce {'non_field_errors': [ErrorDetail(string='Cannot connect to S3 bucket-name with specified AWS credentials', code='invalid')]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/generics.py", line 190, in post
    return self.create(request, *args, **kwargs)
  File "/label-studio/label_studio/io_storages/api.py", line 102, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'non_field_errors': [ErrorDetail(string='Cannot connect to S3 bucket-name with specified AWS credentials', code='invalid')]}
[05/Jun/2021 00:20:29] "POST /api/storages/s3/validate HTTP/1.1" 400 234

**Comment by niklub** [comment]
Hi! You should explicitly specify AWS credentials, IAM role-based access is not supported.

**Comment by xhuaustc** [comment]
I created a new key for access s3 storage. But errors if I left Session Token blank. Is "Session Token " must be set?

**Comment by xhuaustc** [comment]
It works after setting "Bucket Prefix". And it's found that label studio supports kube2iam also after testing.
