### ISSUE TITLE
Label studio 1.0.2 stops working properly when the ML backend returns bad data.

### ISSUE THREAD

**Issue by jrdalenberg** [heartexlabs/label-studio#1055]
Hey,

I am trying to update our backend ML model that was working with label studio 0.9.0.post5.  

To my surprise, the project task overview in label studio 1.0.2 stops working when it receives wrong info from our backend. The webpage shows the error: `Nothing found Try adjusting the filter` and all task data becomes completely inaccessible from a user perspective, while the console returned the error below:  

```
[14/Jun/2021 14:17:08] "PATCH /api/dm/views/4?project=3 HTTP/1.1" 200 578
[2021-06-14 14:17:09,037] [ml.models::predict_many_tasks::173] [ERROR] ML backend returned response number 2 != task number 30
[2021-06-14 14:17:09,037] [core.utils.common::custom_exception_handler::85] [ERROR] 64653aaf-d954-4ca4-9f50-9c64b13c7d96 string indices must be integers
Traceback (most recent call last):
  File "/home/USER/.virtualenvs/label-studio/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/USER/.virtualenvs/label-studio/lib/python3.7/site-packages/label_studio/data_manager/api.py", line 129, in tasks
    evaluate_predictions(tasks_for_predictions)
  File "/home/USER/.virtualenvs/label-studio/lib/python3.7/site-packages/label_studio/data_manager/functions.py", line 233, in evaluate_predictions
    ml_backend.predict_many_tasks(tasks)
  File "/home/USER/.virtualenvs/label-studio/lib/python3.7/site-packages/label_studio/ml/models.py", line 179, in predict_many_tasks
    'result': response['result'],
TypeError: string indices must be integers
``` 
This problem persists until the backend is disconnected.

**Comment by makseq** [comment]
@jrdalenberg 
Thank you for your report! 
Could you please check this PR: https://github.com/heartexlabs/label-studio/pull/1060
Hope this helps.

**Comment by jrdalenberg** [comment]
> @jrdalenberg
> Thank you for your report!
> Could you please check this PR: #1060
> Hope this helps.

Thanks! I'll check next Monday

**Comment by jrdalenberg** [comment]
```
git clone https://github.com/heartexlabs/label-studio.git
cd label-studio/
git fetch origin pull/1060/head:ml_fix
git checkout ml_fix
pip uninstall label_studio
pip install -e .
label-studio
```
Same error

Alternatively, I also tried branch `fix/ml-response` and installed this in a fresh virtualenv without a pip cache dir, which also gave the same error.

**Comment by makseq** [comment]
Nice! I added more checks to LS in that PR, hope it will help our users to understand what's wrong.
