### ISSUE TITLE
Feature to access images from GCS bucket

### ISSUE THREAD

**Issue by suvojit-0x55aa** [heartexlabs/label-studio#1059]
**Is your feature request related to a problem? Please describe.**
I've a huge folder of images in a private GCS bucket, I import a few (around hundred) by defining tasks using the GCS url for image. But there is no way of giving authorization to that currently.
 
**Describe the solution you'd like**
A way to provide authentication by using the GCS json key.

This is the json I'm using to create tasks:

```
{
  "data": {
    "image": "gs://image-bucket/image.png"
  },
  "is_labeled": false,
  "project": x
}
```

**Comment by makseq** [comment]
@suvojit-0x55aa Have you added a GCS storage? Doesn't it resolve you links automatically?

**Comment by suvojit-0x55aa** [comment]
Label Studio is not able to load the image:
```
Cannot load image (gs://image-bucket/image.png). Check console/network panel for more info.
```
These are the steps I've followed:
 - Added extra env variable to docker-compose to give access to json key as described [here](https://labelstud.io/guide/storage.html#Prerequisites)
 - Added import storage with the bucket name
 - Added the data mentioned above
 
Here I get the error that image can't be loaded.

**Comment by suvojit-0x55aa** [comment]
I'm also getting the following error when. I try to sync the import storage.
```
[2021-06-16 06:42:29,014] [core.utils.common::custom_exception_handler::79] [ERROR] c35c39a9-8e06-4095-b797-a39e22b70193 nothing to repeat at position 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/io_storages/api.py", line 91, in post
    storage.sync()
  File "/label-studio/label_studio/io_storages/base_models.py", line 153, in sync
    self.scan_and_create_links()
  File "/label-studio/label_studio/io_storages/gcs/models.py", line 163, in scan_and_create_links
    return self._scan_and_create_links(GCSImportStorageLink)
  File "/label-studio/label_studio/io_storages/base_models.py", line 80, in _scan_and_create_links
    for key in self.iterkeys():
  File "/label-studio/label_studio/io_storages/gcs/models.py", line 66, in iterkeys
    regex = re.compile(str(self.regex_filter)) if self.regex_filter else None
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Comment by suvojit-0x55aa** [comment]
In [prerequisite](https://labelstud.io/guide/storage.html#Prerequisites) it is mentioned that `Service Account Token Creator` permission is needed only I think label-studio is trying to access with other permission also:

```
[2021-06-16 07:38:57,741] [core.utils.common::custom_exception_handler::79] [ERROR] 759a7a36-dbd2-41f4-afdb-33a16b5e5216 403 GET https://storage.googleapis.com/storage/v1/b/image-bucket?projection=noAcl&prettyPrint=false: just-another-account@project.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket.
```

**Comment by alexfecke** [comment]
Try changing the GCS uri to the https version, i.e. `
https://storage.cloud.google.com/[...]` instead of `gs://[...]`

**Comment by lightsaway** [comment]
@alexfecke changing this to `https://storage.cloud.google.com/` needs to make sure your google account in browser can access that.
I think the proper solution here can be one of  -
*  when importing / parsing uri the uri should be signed and returned as signed uri, so it should behave like "storage" module. 
* the image data  is proxied through label-studio server that does read image data with service account configured on backend.

**Comment by lightsaway** [comment]
@suvojit-0x55aa i think this can be fixed with https://github.com/heartexlabs/label-studio/commit/5c5b78446b13e3feb71fc6209c8d3ad845bb6beb
if you will create gcs storage with the prefix that will match folder in gs, on import that will turn that into "signed" url

**Comment by alexfecke** [comment]
@lightsaway Yes, agreed. The external gcloud storage uri is an ugly workaround. The second option that you mentioned, "image data is proxied trhough label-studio server" sounds like what I wanted to achieve. I did not get that to work, however...

**Comment by smoreface** [comment]
@alexfecke have you gotten this to work with the commit that lightsaway referenced?

**Comment by makseq** [comment]
this feature is supported more than 1.5 year.
