### ISSUE TITLE
Init and start missing project_dir

### ISSUE THREAD

**Issue by hurshprasad** [heartexlabs/label-studio#1097]
I am starting label-studio from a submodule used in another project. 

The [config.xml ](https://github.com/lolipopshock/Detectron2_AL/tree/master/annotating)is provided there.  

I did the following steps. 

```
label-studio init labeling/tk-labeling \
        --input-path=./data \
        --input-format=image-dir \
        --allow-serving-local-files --force \
        --label-config=../../annotating/config.xml  \
        --ml-backends http://localhost:9090

/Users/curr_user/Dev/document_analyzer/Detectron2_AL/annotating/config.xml label config copied to ./labeling/tk-labeling/config.xml
./labeling/tk-labeling/completions output dir has been created.
```

then I start label-studio

```
label-studio start ./labeling/tk-labeling
Start browser at URL: http://localhost:8080/welcome
 * Serving Flask app "label_studio.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2021-06-24 07:22:49,766] [INFO] [werkzeug::_log::122]  * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```
However I get the following error.

```
Project loading error
__init__() missing 1 required positional argument: 'project_dir'
Traceback
Traceback (most recent call last):
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/utils/misc.py", line 89, in exception_f
    return f(*args, **kwargs)
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/server.py", line 206, in welcome_page
    project = project_get_or_create()
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/server.py", line 115, in project_get_or_create
    return Project.get_or_create(input_args.project_name,
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/project.py", line 858, in get_or_create
    project = cls.get(project_name, args, context)
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/project.py", line 841, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/project.py", line 829, in _load_from_dir
    return cls(config, project_name, context=context, root_dir=args.root_dir)
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/project.py", line 67, in __init__
    self.load_converter()
  File "/Users/curr_user/Dev/document_analyzer/Detectron2_AL/src/label-studio/label_studio/project.py", line 224, in load_converter
    self.converter = Converter(self.parsed_label_config)
TypeError: __init__() missing 1 required positional argument: 'project_dir'
```

I assume it is a config or init issue, but it would seem the dir is the project directory and output path is deprecated. Do I need to upgrade. Please advise.

**Environment (please complete the following information):**
 - OS: MacOS Catalina 10.15.7
 - Label Studio Version 0.7.4.post0

**Comment by makseq** [comment]
Hi, why do you use so ancient version of LS? 
Looks like it's very modern version of label-studio-converter is installed. Look into requirements.txt and check what converter version is there, install it via

pip install label-studio-converter==0.xx
