### ISSUE TITLE
Cannot import data from Azure

### ISSUE THREAD

**Issue by twsl** [heartexlabs/label-studio#1120]
**Describe the bug**
Cannot import data from Azure.

**To Reproduce**
1. Go to 'Settings', 'Cloud Storage'
2. Click on 'Add Source Storage'
3. Select 'Microsoft Azure'
4. See config image, connection works

**Expected behavior**
Should find and import all images within the container, e.g. https://labelstudiotest.blob.core.windows.net/reservoir/test.png

**Screenshots**
![image](https://user-images.githubusercontent.com/45483159/124090252-f657f680-da54-11eb-976e-33c54fa76c21.png)

![image](https://user-images.githubusercontent.com/45483159/124090095-d0325680-da54-11eb-80e0-ecbf097e1149.png)

**Environment (please complete the following information):**
 - OS: Linux (Docker)
 - Label Studio Version: 1.1.0

**Additional context**
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/io_storages/api.py", line 91, in post
    storage.sync()
  File "/label-studio/label_studio/io_storages/base_models.py", line 153, in sync
    self.scan_and_create_links()
  File "/label-studio/label_studio/io_storages/azure_blob/models.py", line 119, in scan_and_create_links
    return self._scan_and_create_links(AzureBlobImportStorageLink)
  File "/label-studio/label_studio/io_storages/base_models.py", line 80, in _scan_and_create_links
    for key in self.iterkeys():
  File "/label-studio/label_studio/io_storages/azure_blob/models.py", line 86, in iterkeys
    for file in files:
  File "/usr/local/lib/python3.8/dist-packages/azure/core/paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_list_blobs_helper.py", line 72, in _get_next_cb
    return self._command(
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_generated/operations/_container_operations.py", line 1459, in list_blob_flat_segment
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/policies/_redirect.py", line 158, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/policies.py", line 515, in send
    raise err
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/policies.py", line 489, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/policies.py", line 290, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/_base.py", line 103, in send
    self._sender.send(request.http_request, **request.context.options),
  File "/usr/local/lib/python3.8/dist-packages/azure/storage/blob/_shared/base_client.py", line 333, in send
    return self._transport.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/azure/core/pipeline/transport/_requests_basic.py", line 291, in send
    raise error
azure.core.exceptions.ServiceRequestError: (<urllib3.connection.HTTPSConnection object at 0x7f51dc32acd0>, 'Connection to labelstudiotest.blob.core.windows.net timed out. (connect timeout=20)')`

**Comment by twsl** [comment]
Not caused by labelstudio, error due to network issue with changed certificates
