### ISSUE TITLE
FileNotFoundError when I export result to json

### ISSUE THREAD

**Issue by thesby** [heartexlabs/label-studio#1144]
I labeled a lot of images and export result to json, an error occured:

```python
Traceback (most recent call last):
  File "/py_env/py37/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/py_env/py37/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/py_env/py37/lib/python3.7/site-packages/label_studio/data_export/api.py", line 103, in get
    export_stream, content_type, filename = DataExport.generate_export_file(project, tasks, export_type, request.GET)
  File "/py_env/py37/lib/python3.7/site-packages/label_studio/data_export/models.py", line 77, in generate_export_file
    input_json = DataExport.save_export_files(project, now, get_args, data, md5, name)
  File "/py_env/py37/lib/python3.7/site-packages/label_studio/data_export/models.py", line 40, in save_export_files
    'version': version.get_git_version()
  File "/py_env/py37/lib/python3.7/site-packages/label_studio/core/version.py", line 102, in get_git_version
    info = get_git_commit_info(skip_os)
  File "/py_env/py37/lib/python3.7/site-packages/label_studio/core/version.py", line 62, in get_git_commit_info
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

python: 3.7.10
labelstudio: 1.1.0

**Comment by makseq** [comment]
Please check this branch - https://github.com/heartexlabs/label-studio/pull/1161

OR (the correct track)

do you have `label_studio/core/version_.py`? This file will be automatically created on LS start if you have a git repo or it's already created if you use LS from pip.

**Comment by thesby** [comment]
Yes,  `label_studio/core/version.py` and `label_studio/core/version_.py` exist.

**Comment by makseq** [comment]
Hope this problem was solved, feel free to reopen if not.
