### ISSUE TITLE
Filtering by ID in between not working

### ISSUE THREAD

**Issue by alex-eurec** [heartexlabs/label-studio#1166]
**Describe the bug**
The filter that is supposed to filter by ID is not working with the "in between" option

**To Reproduce**
1. Install LS v1.1.0
2. Create user, create project and upload 12 or more texts
3. Filter by ID between 2 and 3
![image](https://user-images.githubusercontent.com/81571132/125081183-02336080-e0c6-11eb-83c8-9ac02d796464.png)

**Expected behavior**
The filter to work as expected

**Screenshots/logs**

<details><summary>Logs of LS when I set the filter:</summary>
<p>

```
[09/Jul/2021 12:58:26] "PATCH /api/dm/views/1?interaction=filter&project=1 HTTP/1.1" 200 675
[2021-07-09 12:58:26,713] [core.utils.common::custom_exception_handler::80] [ERROR] 228fc8da-6ca0-4ccd-b63a-d28db6fb639b 1 validation error for PrepareParams
filters -> items -> 0 -> value
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/label_studio/data_manager/api.py", line 116, in tasks
    queryset = self.get_task_queryset(request, view)
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/label_studio/data_manager/api.py", line 104, in get_task_queryset
    return Task.prepared.all(prepare_params=view.get_prepare_tasks_params())
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/label_studio/data_manager/models.py", line 58, in get_prepare_tasks_params
    data=self.data, selectedItems=selected_items)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PrepareParams
filters -> items -> 0 -> value
  none is not an allowed value (type=type_error.none.not_allowed)
[2021-07-09 12:58:26,719] [django.request::log_response::230] [ERROR] Internal Server Error: /api/dm/views/1/tasks/
[09/Jul/2021 12:58:26] "GET /api/dm/views/1/tasks?page=1&page_size=30&interaction=filter&project=1 HTTP/1.1" 500 1456
[09/Jul/2021 12:58:27] "PATCH /api/dm/views/1?interaction=filter&project=1 HTTP/1.1" 200 675
[2021-07-09 12:58:27,288] [core.utils.common::custom_exception_handler::80] [ERROR] 97b73319-191c-437b-9db9-69c807cb1de2 1 validation error for PrepareParams
filters -> items -> 0 -> value
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/label_studio/data_manager/api.py", line 116, in tasks
    queryset = self.get_task_queryset(request, view)
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/label_studio/data_manager/api.py", line 104, in get_task_queryset
    return Task.prepared.all(prepare_params=view.get_prepare_tasks_params())
  File "/home/alex/Desktop/venv/lib/python3.6/site-packages/label_studio/data_manager/models.py", line 58, in get_prepare_tasks_params
    data=self.data, selectedItems=selected_items)
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PrepareParams
filters -> items -> 0 -> value
  none is not an allowed value (type=type_error.none.not_allowed)
[2021-07-09 12:58:27,295] [django.request::log_response::230] [ERROR] Internal Server Error: /api/dm/views/1/tasks/
[09/Jul/2021 12:58:27] "GET /api/dm/views/1/tasks?page=1&page_size=30&interaction=filter&project=1 HTTP/1.1" 500 1456
```
</p>
</details>

**Environment:**
 - OS: Ubuntu Desktop 18.04
 - Label Studio Version 1.1.0
 - pip installation inside Venv with only python3.6.9

**Extra info**
When the page is reloaded, the filters are empty and therefor, no task is shown
![image](https://user-images.githubusercontent.com/81571132/125082274-4f640200-e0c7-11eb-9c68-18a17602a460.png)

**Comment by makseq** [comment]
@alex-eurec Thank you for your report, we are on it!

**Comment by makseq** [comment]
Fixed in the latest master commit.
