### ISSUE TITLE
Json Schema disallows Boolean Values

### ISSUE THREAD

**Issue by natemccoy** [heartexlabs/label-studio#1299]
when making a labelling config, you cannot use the words `true` or `false` as they are not allowed.

using the example labelling config

```
<View>
  <Text name="text" value="$text"/>
  <View style="box-shadow: 2px 2px 5px #999; padding: 20px; margin-top: 2em; border-radius: 5px;">
    <Choices name="sentiment" toName="text" choice="single" showInLine="true">
      <Choice value="True"/>
      <Choice value="False"/>
    </Choices>
  </View>
</View>
```

an error occurs when submitting (saving) in the back end

```
[12/Aug/2021 13:28:31] "POST /api/projects/7/validate HTTP/1.0" 400 222
[12/Aug/2021 13:28:31] "POST /api/projects/7/sample-task HTTP/1.0" 200 74
[2021-08-12 13:28:35,533] [core.utils.common::custom_exception_handler::85] [ERROR] faf478fb-9ae4-493f-b171-6753feddf880 {'label_config': [ErrorDetail(string="Validation failed on : True is not of type 'string'", code='invalid')]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/label-studio/label_studio/projects/api.py", line 204, in patch
    return super(ProjectAPI, self).patch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/generics.py", line 288, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 67, in update
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 228, in is_valid
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'label_config': [ErrorDetail(string="Validation failed on : True is not of type 'string'", code='invalid')]}
```

Thanks to Max, it seems the Json Schema has an error in this location

https://github.com/heartexlabs/label-studio/blob/33eb579596055b726c31bc7120243c265d33f20e/label_studio/core/utils/schema/label_config_schema.json#L14

Which only allows strings and numbers

**Comment by natemccoy** [comment]
tagging @makseq here for consistency with the slack chat

**Comment by triklozoid** [comment]
Thank you for the report! This is PR with fix: https://github.com/heartexlabs/label-studio/pull/1334
