### ISSUE TITLE
Source filename filters bug

### ISSUE THREAD

**Issue by jhunkim** [heartexlabs/label-studio#1364]
**Describe the bug**
`source filename` Filter does not work properly.

**To Reproduce**
1. generate projects and import task.
2. add `source filename` filter.

**Expected behavior**
When i print the query of queryset in apply_filters func in managers.py of data_manager,
there is no data related to the file source.
```
SELECT "task"."id", "task"."data", "task"."meta", "task"."project_id", "task"."created_at", "task"."updated_at", "task"."is_labeled", "task"."overlap", "task"."file_upload_id", 
COUNT(DISTINCT "task_completion"."id") FILTER (WHERE NOT "task_completion"."was_cancelled") AS "total_annotations", 
COUNT(DISTINCT "task_completion"."id") FILTER (WHERE "task_completion"."was_cancelled") AS "cancelled_annotations", 
COUNT(DISTINCT "prediction"."id") AS "total_predictions" 
FROM "task" 
LEFT OUTER JOIN "task_completion" ON ("task"."id" = "task_completion"."task_id") 
LEFT OUTER JOIN "prediction" ON ("task"."id" = "prediction"."task_id") 
WHERE "task"."project_id" = 12 GROUP BY 
"task"."id", "task"."data", "task"."meta", "task"."project_id", "task"."created_at", "task"."updated_at", "task"."is_labeled", "task"."overlap", "task"."file_upload_id"
```
Perhaps TaskQuerySet does not hold information related to source filename.
I attached an error message.
```code
[27/Aug/2021 08:43:24] "PATCH /api/dm/views/10?interaction=filter&project=12 HTTP/1.1" 200 574
[2021-08-27 08:43:24,160] [core.utils.common::custom_exception_handler::83] [ERROR] 30aae87e-7c4b-4cf0-99ab-49493641cfd3 Related Field got invalid lookup: icontains
Traceback (most recent call last):
  File "/home/jhunkim/conda/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/ssd/1.2020_AST/0.2021_project/backup-label-studio/1.2.0/label-studio/label_studio/data_manager/api.py", line 118, in tasks
    queryset = self.get_task_queryset(request, view)
  File "/ssd/1.2020_AST/0.2021_project/backup-label-studio/1.2.0/label-studio/label_studio/data_manager/api.py", line 103, in get_task_queryset
    return Task.prepared.all(prepare_params=view.get_prepare_tasks_params())
  File "/ssd/1.2020_AST/0.2021_project/backup-label-studio/1.2.0/label-studio/label_studio/data_manager/managers.py", line 369, in all
    return self.get_queryset(fields_for_annotation).prepared(prepare_params=prepare_params)
  File "/ssd/1.2020_AST/0.2021_project/backup-label-studio/1.2.0/label-studio/label_studio/data_manager/managers.py", line 254, in prepared
    queryset = apply_filters(queryset, prepare_params.filters)
  File "/ssd/1.2020_AST/0.2021_project/backup-label-studio/1.2.0/label-studio/label_studio/data_manager/managers.py", line 237, in apply_filters
    queryset = queryset.filter(filter_expression)
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1380, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1244, in build_filter
    check_filterable=check_filterable,
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1380, in _add_q
    split_subq=split_subq, check_filterable=check_filterable,
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/jhunkim/conda/lib/python3.7/site-packages/django/db/models/sql/query.py", line 1156, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
```

**Screenshots**
![image](https://user-images.githubusercontent.com/23379255/131099792-2d835867-4866-46c6-be2b-3ecae3b4abd7.png)

**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - Label Studio Version 1.2.0

**Additional context**

**Comment by makseq** [comment]
@jhunkim Please, check this PR: https://github.com/heartexlabs/label-studio/pull/1373
Hope it's fixed there.

**Comment by jhunkim** [comment]
> @jhunkim Please, check this PR: #1373
> Hope it's fixed there.

Thanks for the quick fix.
