### ISSUE TITLE
Cannot delete task after updating with API

### ISSUE THREAD

**Issue by lluissalord** [heartexlabs/label-studio#1531]
**Describe the bug**
I cannot delete two tasks which I have updated with API, because accidentaly I messed up the format of `data` field on these tasks which instead of being a dictionary are strings.

Then, when trying to localize them on UI by filtering the UI it does not update to see the results and also when there is any interaction with these tasks with the API.

**To Reproduce**
1. Donwload a task
2. Modify `data` field for a string instead of dict field
3. Update task with this new format
4. See errors when looking for it on UI, trying to download/modify/delete.

**Expected behavior**
Even the format is not correct, we should be able to delete/modify this kind of data to fix it. Besides, I would think that it would be great to have a checker when uploading/modifying data to ensure it has the correct format.

**Environment (please complete the following information):**
 - Label Studio Version 1.3

**Additional context**
Logs when trying to delete task with API:
```
[2021-09-24 13:28:33,867] [core.utils.common::custom_exception_handler::83] [ERROR] 2de925af-6860-4608-92a5-59557ac6ff7f 'str' object has no attribute 'keys'
Traceback (most recent call last):
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/api.py", line 133, in delete
    return super(TaskAPI, self).delete(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/generics.py", line 291, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/home/opground/.local/lib/python3.8/site-packages/django/db/models/base.py", line 947, in delete
    return collector.delete()
  File "/home/opground/.local/lib/python3.8/site-packages/django/db/models/deletion.py", line 404, in delete
    signals.pre_delete.send(
  File "/home/opground/.local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/home/opground/.local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 451, in remove_data_columns
    instance.decrease_project_summary_counters()
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 270, in decrease_project_summary_counters
    summary.remove_data_columns([self])
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/projects/models.py", line 698, in remove_data_columns
    for key in task_data.keys():
AttributeError: 'str' object has no attribute 'keys'
[2021-09-24 13:28:33,873] [core.utils.common::custom_exception_handler::117] [DEBUG] Traceback (most recent call last):
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/api.py", line 133, in delete
    return super(TaskAPI, self).delete(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/generics.py", line 291, in delete
    return self.destroy(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 91, in destroy
    self.perform_destroy(instance)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/mixins.py", line 95, in perform_destroy
    instance.delete()
  File "/home/opground/.local/lib/python3.8/site-packages/django/db/models/base.py", line 947, in delete
    return collector.delete()
  File "/home/opground/.local/lib/python3.8/site-packages/django/db/models/deletion.py", line 404, in delete
    signals.pre_delete.send(
  File "/home/opground/.local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/home/opground/.local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 451, in remove_data_columns
    instance.decrease_project_summary_counters()
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 270, in decrease_project_summary_counters
    summary.remove_data_columns([self])
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/projects/models.py", line 698, in remove_data_columns
    for key in task_data.keys():
AttributeError: 'str' object has no attribute 'keys'

[2021-09-24 13:28:33,873] [django.request::log_response::224] [ERROR] Internal Server Error: /api/tasks/21730/
[24/Sep/2021 13:28:33] "DELETE /api/tasks/21730/ HTTP/1.1" 500 2265
```

Logs when trying to see task on UI:
```
[2021-09-27 08:24:45,289] [core.utils.common::custom_exception_handler::83] [ERROR] 563c2994-00b3-42c7-b0f6-3abe69fcdd21 'str' object has no attribute 'values'
Traceback (most recent call last):
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/data_manager/api.py", line 133, in tasks
    return self.get_paginated_response(serializer.data)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/serializers.py", line 151, in to_representation
    instance.data = instance.resolve_uri(instance.data, proxy=self.context.get('proxy', False))
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 159, in resolve_uri
    storage = self._get_task_storage(task_data)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 186, in _get_task_storage
    storage = self._get_storage_by_task_data(task_data)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 167, in _get_storage_by_task_data
    for url in task_data.values():
AttributeError: 'str' object has no attribute 'values'
[2021-09-27 08:24:45,304] [core.utils.common::custom_exception_handler::117] [DEBUG] Traceback (most recent call last):
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/data_manager/api.py", line 133, in tasks
    return self.get_paginated_response(serializer.data)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/home/opground/.local/lib/python3.8/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/serializers.py", line 151, in to_representation
    instance.data = instance.resolve_uri(instance.data, proxy=self.context.get('proxy', False))
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 159, in resolve_uri
    storage = self._get_task_storage(task_data)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 186, in _get_task_storage
    storage = self._get_storage_by_task_data(task_data)
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 167, in _get_storage_by_task_data
    for url in task_data.values():
AttributeError: 'str' object has no attribute 'values'
```

**Comment by makseq** [comment]
@lluissalord Could you try to remove this task using shell? 

```
label-studio shell
> Task.objects.get(id=<broken_task_id>).delete()
```

Will it help you? 


> it would be great to have a checker when uploading/modifying data to ensure it has the correct format.

We have a validation in the task import api, but we left api/tasks without it because performance thoughts.

**Comment by lluissalord** [comment]
@makseq I've tried using shell as you mentioned and it did not work. Do you know which other option I could have?

```
>>> Task.objects.get(id=21730).delete()
Traceback (most recent call last):
  File "/usr/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/opground/.local/lib/python3.8/site-packages/django/db/models/base.py", line 947, in delete
    return collector.delete()
  File "/home/opground/.local/lib/python3.8/site-packages/django/db/models/deletion.py", line 404, in delete
    signals.pre_delete.send(
  File "/home/opground/.local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/home/opground/.local/lib/python3.8/site-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 451, in remove_data_columns
    instance.decrease_project_summary_counters()
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 270, in decrease_project_summary_counters
    summary.remove_data_columns([self])
  File "/home/opground/.local/lib/python3.8/site-packages/label_studio/projects/models.py", line 698, in remove_data_columns
    for key in task_data.keys():
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by makseq** [comment]
Try these please:

``
Task.objects.filter(id=<broken_task_id>).update(data={})
Task.objects.get(id=<broken_task_id>).delete()
```

**Comment by lluissalord** [comment]
> Try these please:
> 
> ```
> Task.objects.filter(id=<broken_task_id>).update(data={})
> Task.objects.get(id=<broken_task_id>).delete()
> ```

It worked, thank you!!
