### ISSUE TITLE
Export to COCO, VOC and Yolo give KeyError: 'x' 

### ISSUE THREAD

**Issue by baswenneker** [heartexlabs/label-studio#1818]
**Describe the bug**
I've labelled about 60 images (using the latest docker container). After labelling I tried to export the set to Pascal VOC and I get the following error:

```[07/Dec/2021 15:48:18] "GET /api/projects/1/export/files HTTP/1.1" 200 19
[2021-12-07 15:48:22,818] [core.utils.common::custom_exception_handler::83] [ERROR] 4d0b7cf1-6578-4a3f-b7e0-a4c60970d937 'x'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_export/api.py", line 181, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/label-studio/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter/converter.py", line 178, in convert
    self.convert_to_voc(input_data, output_data, output_image_dir=image_dir, is_dir=is_dir)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter/converter.py", line 734, in convert_to_voc
    x = int(bbox['x'] / 100 * width)
KeyError: 'x'
```

![error](https://user-images.githubusercontent.com/173496/145062424-696a6e14-fba4-4e34-a365-d66c27300509.jpg)

**To Reproduce**
To start LS I ran `docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest`.

1. Go to 'Export'
2. Click on 'Pascal VOC XML' and then on the 'Export' button
3. See error

**Expected behavior**
I need the export :)

**Screenshots**

**Environment (please complete the following information):**
 - OS: OSX Monterey, using latest Docker version 
 - Label Studio Version - latest docker 
 - Django version 3.1.13, using settings 'core.settings.label_studio'

**Additional context**
```{
  "release": "1.4",
  "label-studio-os-package": {
    "version": "1.4",
    "short_version": "1.4",
    "latest_version_from_pypi": "1.4",
    "latest_version_upload_time": "2021-11-19T15:56:02",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "Include  tag as label (#1811)",
    "commit": "20c38d3c75b625d959f2eeb5e04ad1dfeaee1d83",
    "date": "2021-12-06 18:45:22 +0800",
    "branch": "master",
    "version": "1.4.0+24.g20c38d3.dirty"
  },

  "label-studio-frontend": {
    "message": "Fix resize observer crash when Image URL is not provided",
    "commit": "23580b27a85248d6fc616b58dd9daecd267c9a3b",
    "branch": "fix/dev-1247/resize-observer-crash",
    "date": "2021-12-02T17:07:52Z"
  },

  "dm2": {
    "message": "DEV-609: Load task data from server (#22)  * Load task data from serve ...",
    "commit": "feb9f1db923039b098fd0122f3d6a87bdc224a79",
    "branch": "master",
    "date": "2021-11-18T20:01:55Z"
  },

  "label-studio-converter": {
    "version": "0.0.36"
  }
}
```

**Comment by makseq** [comment]
Thank you for your report!

**Comment by zhiting-wang** [comment]
I also encountered a similar problem. How did you get your csv file? Do I need to modify the source code to generate this csv? Which file?  Please give some advise, thank you!
