### ISSUE TITLE
I can't upload image to label-stuido server

### ISSUE THREAD

**Issue by auroua** [heartexlabs/label-studio#185]
**Describe the bug**
I have used label-studio on windows os and ubuntu os. After config step, I try to drag image so as to upload the image to server, but the server report the following error:

**To Reproduce**
1. Go to 'image'
2. Click on 'drag local image to the drop area'

**Expected behavior**
```
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\label_studio\server.py", line 184, in tasks_page
    reload_config()
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\label_studio\server.py", line 89, in reload_config
    db.re_init(c)
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\label_studio\utils\db.py", line 202, in re_init
    init(config)
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\label_studio\utils\db.py", line 154, in init
    tasks_from_json_file(path, tasks)
  File "c:\users\administrator\anaconda3\envs\py37\lib\site-packages\label_studio\utils\db.py", line 98, in tasks_from_json_file
    json_body = orjson.loads(f.read())
json.decoder.JSONDecodeError: trailing comma at line 12 column 1: line 1 column 1 (char 0)
```

**Environment (please complete the following information):**
 - OS: [e.g. iOS]     I have tried windows and ubuntu
 - Browser [e.g. chrome, safari]   firefox

**Additional context**

**Comment by deppp** [comment]
Hey @auroua, direct file uploads are not supported atm. You need to provide either a CSV or JSON file with the URLs. Click on one of the supported file formats in the "Import" page to get an example. 

We may consider adding the files directly soon.
