### ISSUE TITLE
Deploying Labelstudio with mysql as DB fails with error "No module named 'MySQLdb'"

### ISSUE THREAD

**Issue by prashant2402** [heartexlabs/label-studio#1896]
**Describe the bug**
Trying to deploy latest label studio with MySql as DB in kubernetes, fails with the below error, I've also tried bringing it up using docker-compose files but same result:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/label-studio/label_studio/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/base_user.py", line 48, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.8/dist-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?
```

**To Reproduce**
1. Set mysql db configuration in docker-compose
2. run docker-compose up
3. Check label studio logs

**Expected behavior**
Label studio should start without errors and initialise the Mysql database.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: kubernetes cluster and also in docker-compose
 - Label Studio Version 1.14.0

**Additional context**
n/a

**Comment by makseq** [comment]
Try to install LS with extra lib

`pip install label-studio[mysql]`

**Comment by prashant2402** [comment]
I was not installing label-studio via pip, was using kubernetes helm charts to deploy so was just referring to the 1.4 image. 
after your suggestion, I modified dockerfile to add `pip3 install mysqlclient`, built a new version and deployed it, that seems to have initialised mysqldb as expected.

could we add mysqlclient in requirements.txt and make it available for all?

**Comment by makseq** [comment]
Sorry, we can't add mysql because we don't support mysql officially and we are trying to avoid dependency hell.

**Comment by makseq** [comment]
Feel free to re-open if you have any questions.
