### ISSUE TITLE
Export Data Error from Database (django.db.utils.OperationalError: too many SQL variables)

### ISSUE THREAD

**Issue by sainathgk** [heartexlabs/label-studio#1941]
**Describe the bug**
A project of Natural Language Processing for Named-Entity Recognition, The Data size is around 1,500 sentences. SQLITE error while exporting the data after Labelling. 
Label Studio Version - 1.4

**To Reproduce**
1. Go to 'Export' 
2. Click on 'CSV' or 'JSON'
3. Click on 'Export'
4. See error like below
RUNTIME ERROR
too many SQL variables

**Expected behavior**
Should export all the data from that Project.

**Screenshots**

```
Traceback (most recent call last):
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/label_studio/data_export/api.py", line 177, in get
    self.get_task_queryset(query.filter(id__in=_task_ids)), many=True, expand=['drafts']
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/rest_framework/serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 508, in execute
    return real_execute(self, sql, params)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/data/sainath/lb_studio/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: too many SQL variables
```

**Environment (please complete the following information):**
 - OS: Linux (x86_64)
 - Label Studio Version - 1.4

**Comment by chiganov** [comment]
Hello. Thanks for your question.

Unfortunately I couldn't repeat this bug at my laptop. Can you text how did you install LableStudio.

Looks like you use SQLight and there some extraordernal `SQLITE_MAX_VARIABLE_NUMBER` value.

Try to migrate data to Postgres or change `SQLITE_MAX_VARIABLE_NUMBER` for your DB instance.

Also you might try to use other export through API, it could work for you: 
https://labelstud.io/api#operation/api_projects_exports_create

**Comment by sainathgk** [comment]
> Hello. Thanks for your question.
> 
> Unfortunately I couldn't repeat this bug at my laptop. Can you text how did you install LableStudio?
> 
> Looks like you use SQLight and there some extraordernal `SQLITE_MAX_VARIABLE_NUMBER` value.
> 
> Try to migrate data to Postgres or change `SQLITE_MAX_VARIABLE_NUMBER` for your DB instance.
> 
> Also you might try to use other export through API, it could work for you: https://labelstud.io/api#operation/api_projects_exports_create

Thanks chiganov for your reply.
I installed LabelStudio through pip install -U label-studio
and updated the sqlite3 to latest.

Please help me how to change the SQLITE_MAX_VARIABLE_NUMBER value. or migrate to Postgres.

Thanks once again.

**Comment by chiganov** [comment]
Hi 

Use [this docs](https://labelstud.io/guide/storedata.html) to set up the aplication with postgress.

**Comment by youyuge34** [comment]
@sainathgk I meet the same problem as yours, which i cannot export any data. Have you solved this problem?

**Comment by makseq** [comment]
@youyuge34 Try this steps: 

```
label-studio shell
```

```
from tasks.serializers import TaskWithAnnotationsSerializer

tasks = Task.objects.filter(project=<ID>)
export_json_data = TaskWithAnnotationsSerializer(tasks, many=True).data
```

**Comment by makseq** [comment]
you have to use ls converter library: https://github.com/heartexlabs/label-studio-converter
