### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by ya0002** [heartexlabs/label-studio#2002]
Hi guys,
I am trying to integrate my ML backend to my label-studio, the backend has been set up and running, I am trying to perform active learning but whenever I start to train the model after annotating(Start model training after any annotations are submitted or updated is ON), I get `socket.timeout: timed out`

The ML backend is connected.

### COMPLETE TRACEBACK
```

[05/Feb/2022 00:03:32] "POST /api/dm/actions?id=next_task&tabID=6&project=7 HTTP/1.1" 200 618
[2022-02-05 00:04:29,155] [root::run_webhook::33] [ERROR] HTTPConnectionPool(host='192.168.1.100', port=9090): Max retries exceeded with url: /webhook (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F6AFD9FCA0>, 'Connection to 192.168.1.100 timed out. (connect timeout=1.0)'))
Traceback (most recent call last):
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\http\client.py", line 951, in send
    self.connect()
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\connection.py", line 187, in connect
    conn = self._new_conn()
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x000001F6AFD9FCA0>, 'Connection to 192.168.1.100 timed out. (connect timeout=1.0)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.100', port=9090): Max retries exceeded with url: /webhook (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F6AFD9FCA0>, 'Connection to 192.168.1.100 timed out. (connect timeout=1.0)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\label_studio\webhooks\utils.py", line 26, in run_webhook
    return requests.post(
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "d:\users\yusuf\anaconda3\envs\hinglish\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.168.1.100', port=9090): Max retries exceeded with url: /webhook (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001F6AFD9FCA0>, 'Connection to 192.168.1.100 timed out. (connect timeout=1.0)'))

````

**Comment by ya0002** [comment]
@makseq 
I am using:
label-studio=1.4
label-studio-ml= 1.0.3

**Comment by makseq** [comment]
Are you sure 192.168.1.100:9090 is accessible from LS backend?

**Comment by ya0002** [comment]
Yes

![image](https://user-images.githubusercontent.com/48356056/152951750-a9342cb9-8d69-4a76-84d3-35c64f1888e3.png)

![image](https://user-images.githubusercontent.com/48356056/152951873-bdf059c5-40ea-48e1-b814-1e7ca38a117b.png)


> Are you sure 192.168.1.100:9090 is accessible inside of LS backend?

**Comment by 2212168851** [comment]
I have the same problem

**Comment by makseq** [comment]
If your ML backend takes long time for prediction generating, you can try to increase all LS timeouts for ML backends:
https://github.com/heartexlabs/label-studio/blob/develop/label_studio/ml/api_connector.py#L22

Just set environment variables with their names.

**Comment by AkashDataScience** [comment]
I used command below to update environment variable:
```export TIMEOUT_PREDICT=400```
```echo``` also reflects that TIMEOUT_PREDICT is 400.
But still my API call from postman times out around 100 seconds. 
PS: Postman timeout is set to infinite.

**Comment by ice6** [comment]
> I used command below to update environment variable: `export TIMEOUT_PREDICT=400` `echo` also reflects that TIMEOUT_PREDICT is 400. But still my API call from postman times out around 100 seconds. PS: Postman timeout is set to infinite.

A late reply for others to this thread. the `environment variable` should be `ML_TIMEOUT_PREDICT`. 

:)
