### ISSUE TITLE
Error when adding a local address in the dock environment

### ISSUE THREAD

**Issue by DimIsaev** [heartexlabs/label-studio#2035]
When adding a local address in the dock environment

![image](https://user-images.githubusercontent.com/11172642/154291830-57675352-6773-4ca8-9ddf-2ac897059de5.png)

**Environment (please complete the following information):**
 - OS: Ubuntu / Docker
 - Label Studio Version 1.4.0

**Comment by farioas** [comment]
Please provide more details:
- label-studio logs
- result of `curl http://prom:9090/send`

**Comment by makseq** [comment]
Are you sure your LS server instance can access this address - prom:9090?

**Comment by DimIsaev** [comment]
> Are you sure your LS server instance can access this address - prom:9090?

- Error  label-studio logs

```
[2022-02-17 05:24:48,044] [core.utils.common::custom_exception_handler::83] [ERROR] a0277d4f-b808-479a-b7bb-ce7856c4a3ad {'url': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch        
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper      
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 228, in is_valid  
    raise ValidationError(self.errors)
rest_framework.exceptions.ValidationError: {'url': [ErrorDetail(string='Enter a valid URL.', code='invalid')]}
[2022-02-17 05:24:48,061] [django.request::log_response::224] [WARNING] Bad Request: /api/webhooks/   
[17/Feb/2022 05:24:48] "POST /api/webhooks/ HTTP/1.1" 400 174
```

**Comment by DimIsaev** [comment]
Wait for an answer ?

**Comment by chiganov** [comment]
Hi and thank you for the question.

We use django url validator here. It was supposed that would be used for external remote addresses but not for docker network. So we use [URLValidator](https://docs.djangoproject.com/en/4.0/ref/validators/#urlvalidator) here which has following [regexp rule](https://github.com/django/django/blob/main/django/core/validators.py#L94
)

Like available solution if you know external IP of the host you might try use it.

But your use case is important for us. We will add this point to our backlog.

**Comment by cptspacemanspiff** [comment]
For anyone looking at this in the future, the issue seems to be that it does not like web addresses without a top level domain in it.
IE `example.com` is fine, `example` is not.
specifically it looks for: `yourname.yourtopleveldomain` with the `.` being the important part.
At least in docker (with docker compose) an easy fix for this is to change the name of the container:

Instead of naming the container: `myserver` name it `my.server`.

Its pretty janky, and feels silly, but it works. 

It would probably be very helpful to add a note to this effect in the documentation though, debugging this took a couple hours.
