### ISSUE TITLE
Loading Images from Local Directory Fails

### ISSUE THREAD

**Issue by rsomani95** [heartexlabs/label-studio#205]
**Describe the bug**
Automatic creation of tasks from a directory in the `input_path` of the `config.json` file doesn't work. The server fails to start. I followed instructions regarding modifying the `config.json` file from the official [guide](https://labelstud.io/guide/format.html#Directory-with-image-files).

Here's my config file:
```json
{
  "title": "Label Studio",
  "port": 8200,
  "debug": false,
  "label_config": "/Users/rahulsomani/labeling_project/config.xml",
  #####
  "input_path": "/Users/rahulsomani/Desktop/imgs/",
  #####
  "output_dir": "/Users/rahulsomani/labeling_project/completions",
  "instruction": "Type some <b>hypertext</b> for label experts!",
  "allow_delete_completions": true,
  "templates_dir": "examples",
  "editor": {"debug": false},
  "!ml_backend": {"url": "http://localhost:9090", "model_name": "my_super_model"},
  "sampling": "uniform",
  "config_path": "/Users/rahulsomani/labeling_project/config.json",
  "label_config_updated": true
}
```
where `"input_path": "/Users/rahulsomani/Desktop/imgs/"` is a folder that contains `.jpg` images.

When I run `label-studio start labeling_project/` on the command line, I get an `IsADirectoryError`. Here's the full message:
```python
Start browser at URL: http://127.0.0.1:8200/welcome
 * Serving Flask app "label_studio.server" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2020-01-30 12:06:06,176] [werkzeug] [INFO]  * Running on http://0.0.0.0:8200/ (Press CTRL+C to quit)
[2020-01-30 12:06:08,780] [label_studio.server] [ERROR] Exception on /welcome [GET]
Traceback (most recent call last):
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rahulsomani/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/rahulsomani/label-studio/label_studio/server.py", line 148, in welcome_page
    project = project_get_or_create()
  File "/Users/rahulsomani/label-studio/label_studio/server.py", line 77, in project_get_or_create
    'multi_session': False
  File "/Users/rahulsomani/label-studio/label_studio/project.py", line 587, in get_or_create
    project = cls.get(project_name, args, context)
  File "/Users/rahulsomani/label-studio/label_studio/project.py", line 570, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/Users/rahulsomani/label-studio/label_studio/project.py", line 558, in _load_from_dir
    return cls(config, project_name, context)
  File "/Users/rahulsomani/label-studio/label_studio/project.py", line 44, in __init__
    self.load_tasks()
  File "/Users/rahulsomani/label-studio/label_studio/project.py", line 62, in load_tasks
    self.tasks = json_load(self.config['input_path'])
  File "/Users/rahulsomani/label-studio/label_studio/utils/io.py", line 106, in json_load
    with io.open(file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/rahulsomani/Desktop/imgs/'
[2020-01-30 12:06:08,807] [werkzeug] [INFO] 127.0.0.1 - - [30/Jan/2020 12:06:08] "GET /welcome HTTP/1.1" 500 -
```

On lines 61-62 of `project.py`, it appears that `label-studio` expects the `input_path` to be a `.json` file only. This contradicts the official [guide](https://labelstud.io/guide/format.html#Directory-with-image-files) though. Perhaps I'm missing something? I'd appreciate any help on this. Thank you.

Related: #119

**Comment by niklub** [comment]
Hi, @rsomani95 !

Thanks for reporting this. Please don't modify `config.json`: if you want to stream your images from local dir, you can do the following:

Starting from the v0.4.5, you can initialize project with images from local directory:
```
label-studio init labeling-project --input-path=/Users/rahulsomani/Desktop/imgs/ --input-format=image-dir
```

Then launch label studio
```
label-studio start labeling-project
```

We are on the way to ehnance the official guide, it will be updated very soon.

**Comment by rsomani95** [comment]
Thanks a lot @niklub! Great project!

For anyone that sees this in the future, you can add `--template {image_classifiction,...}` etc. when initialising the project to setup the labelling config. All the options can be viewed by entering `label-studio init -h`
