### ISSUE TITLE
Removing dulplicate tasks 

### ISSUE THREAD

**Issue by sachin-singh-12** [heartexlabs/label-studio#2050]
Hi, I have following issues -
1.  I don't know why but when I synced  my source storage (local storage). Many duplicate tasks got created though there were not any duplicate files in my source data. 
2. Next, when I am trying to delete these duplicate tasks using the "remove duplicate tasks" option. Every time it gets "gateway time out" (in total there are around 25K tasks). Even with just 1000 tasks selected it gets gateway time out and not a single duplicate is actually deleted.

Any suggestions on how to resolve this gateway time out issue and why did these duplicates tasks got created in first place.

**Comment by makseq** [comment]
1. What LS version do you use? Looks like a bug. 
2. As we've discussed it in slack, you can run the code of Remove Duplicates action in the `label-studio shell`.

**Comment by sachin-singh-12** [comment]
1. I am using LS version 1.4 using docker 
2. I tried the solution we discussed on slack i.e. after entering command line mode using label-studio shell, I ran following commands 
```
from data_mangaer.actions.experimental import remove_duplicates
project = Project.objects.get(id=2)
remove_duplicates(project, project.tasks)
````
But this is running indefinitely. Specifically this line is taking time
https://github.com/heartexlabs/label-studio/blob/101e8766723c6ddf5aab3b74f30ef61890d05736/label_studio/data_manager/actions/experimental.py#L79
Just to do a sanity check I manually run the commands of  this function on another dummy project with just 3 tasks. When I execute -
`project.tasks.filter(id__in=[106], annotations__isnull=True).delete()`
I encounter this error - 
`django.db.utils.IntegrityError: update or delete on table "task" violates foreign key constraint "io_storages_localfile_task_id_d0e8315f_fk_task_id" on table "io_storages_localfilesimportstoragelink"`

**Comment by kennethjiang** [comment]
I am trying to de-dupe the images located in a local storage. But I ran into this error:

```
Traceback (most recent call last):
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/label_studio/data_manager/api.py", line 354, in post
    result = perform_action(action_id, project, queryset, request.user, **kwargs)
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/label_studio/data_manager/actions/__init__.py", line 117, in perform_action
    raise e
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/label_studio/data_manager/actions/__init__.py", line 113, in perform_action
    result = action['entry_point'](project, queryset, **kwargs)
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/label_studio/data_manager/actions/experimental.py", line 113, in remove_duplicates
    link_instance = _class.objects.get(id=source[2])
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/kenneth/miniconda3/lib/python3.10/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
io_storages.localfiles.models.LocalFilesImportStorage.DoesNotExist: LocalFilesImportStorage matching query does not exist.
Version: 1.9.0
```
