### ISSUE TITLE
orjson requires glibc 2.18

### ISSUE THREAD

**Issue by zacharywhitley** [heartexlabs/label-studio#215]
**Describe the bug**
orjson requires glibc 2.18 that isn't available on some distributions, specifically Centos 7

**To Reproduce**
1. pip install label-studio
2. label-studio init bbox_project
3. Stack trace

```sh
Traceback (most recent call last):
  File "/home/centos/.pyenv/versions/3.7.4/bin/label-studio", line 5, in <module>
    from label_studio.server import main
  File "/home/centos/.pyenv/versions/3.7.4/lib/python3.7/site-packages/label_studio/server.py", line 31, in <module>
    from label_studio.project import Project
  File "/home/centos/.pyenv/versions/3.7.4/lib/python3.7/site-packages/label_studio/project.py", line 21, in <module>
    from label_studio.tasks import Tasks
  File "/home/centos/.pyenv/versions/3.7.4/lib/python3.7/site-packages/label_studio/tasks.py", line 1, in <module>
    import orjson
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/centos/.pyenv/versions/3.7.4/lib/python3.7/site-packages/orjson.cpython-37m-x86_64-linux-gnu.so)
```

**Environment (please complete the following information):**
 - Centos 7

**Comment by niklub** [comment]
@zacharywhitley please try to update label-studio package `pip install -U label-studio` (should be 0.4.6.post2), tell me whether this issue reproduces

**Comment by zacharywhitley** [comment]
Looks good now. Thanks!
