### ISSUE TITLE
Docker Run Error about config file

### ISSUE THREAD

**Issue by wrathagom** [heartexlabs/label-studio#220]
**Describe the bug**
When I copy/paste the command from your README for running in Docker I get an error. The full terminal output is shown below:

```
~/Projects                                                                                                                                                               
▶ docker run --rm -p 8200:8200 heartexlabs/label-studio:latest
Unable to find image 'heartexlabs/label-studio:latest' locally
latest: Pulling from heartexlabs/label-studio
bc51dd8edc1b: Pull complete 
dc4aa7361f66: Pull complete 
0b69bf5f8bd1: Pull complete 
79b36be36783: Pull complete 
c1943469abb7: Pull complete 
2e46d6f10a1d: Pull complete 
4bda89854ec2: Pull complete 
0fbb9bd3d7e7: Pull complete 
583f63add2aa: Pull complete 
9e393c9d9c90: Pull complete 
f2d7580c8609: Pull complete 
Digest: sha256:b34c9a030602ed6f71322c22e32451007ebcc0357a6a43cb7587091842108abb
Status: Downloaded newer image for heartexlabs/label-studio:latest
Traceback (most recent call last):
  File "/usr/local/bin/label-studio", line 11, in <module>
    load_entry_point('label-studio', 'console_scripts', 'label-studio')()
  File "/label-studio/label_studio/server.py", line 642, in main
    Project.create_project_dir(input_args.project_name, input_args)
  File "/label-studio/label_studio/project.py", line 482, in create_project_dir
    already_exists_error('label config', config_xml_path)
  File "/label-studio/label_studio/project.py", line 468, in already_exists_error
    path=path, what=what
RuntimeError: ./my_project/config.xml label config already exists. Use "--force" option to recreate it.
```

**Expected behavior**

I was kind of hoping it would just work.

**Environment (please complete the following information):**
 - OS: Mac OS Catalina
 - Docker version in below screenshot

![image](https://user-images.githubusercontent.com/1779894/75212038-b17eca00-5753-11ea-93aa-4914f4644a72.png)

**Comment by niklub** [comment]
Hi, @wrathagom! Thanks reporting this. Consider overriding default docker command, e.g. by running

```
docker run --rm -p 8200:8200 heartexlabs/label-studio:latest label-studio start my_project --init --force
```

meanwhile we'll update default docker command & docs

**Comment by wrathagom** [comment]
Thanks! worked great.
