### ISSUE TITLE
Tiff file extension as .tif is not detected

### ISSUE THREAD

**Issue by vfdev-5** [heartexlabs/label-studio#221]
**Describe the bug**
TIFF image can have `.tif` file extension which is not seen by the server. And it fails with an error.

**To Reproduce**
```
user:/project/labelling# label-studio init labeling_project --input-path=/input/img --input-format=image-dir
Empty config has been created in ./labeling_project/config.xml
Traceback (most recent call last):
  File "/opt/conda/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/label_studio/server.py", line 635, in main
    Project.create_project_dir(input_args.project_name, input_args)
  File "/opt/conda/lib/python3.7/site-packages/label_studio/project.py", line 499, in create_project_dir
    tasks = cls._load_tasks(input_path, args, config_xml_path)
  File "/opt/conda/lib/python3.7/site-packages/label_studio/project.py", line 440, in _load_tasks
    data_key = Project._get_single_input_value(input_data_tags)
  File "/opt/conda/lib/python3.7/site-packages/label_studio/project.py", line 168, in _get_single_input_value
    input_data_tag = input_data_tags[0]
IndexError: list index out of range
user:/project/labelling# pip list | grep label-studio
label-studio                  0.4.8              
label-studio-converter        0.0.11    

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22] 0.4.8

**Additional context**
Add any other context about the problem here.

https://github.com/heartexlabs/label-studio/blob/dc3e40440643469869d8456311a9c860a5a75f09/label_studio/tasks.py#L17

**Comment by niklub** [comment]
Hi, @vfdev-5 ! 
Thanks for reporting this. Yes`.tif` format is what we've missed, only `.tiff`.

But actually the problem is that we have to specify a label config explicitly when `--input-format=image_dir` - otherwise we don't know the name of the input tag for `<Image>`. Another option could be preparing all your task in [json format](https://labelstud.io/guide/format.html#JSON-file), then you don't need for label config because JSON formatted tasks already contain the input tag key.

Anyway, here the PR that prevent starting Label Studio in these circumstances and I hope it makes things simpler https://github.com/heartexlabs/label-studio/pull/223

**Comment by niklub** [comment]
Please try out `label-studio>=0.5.0` and reopen this issue if the problem persists
