### ISSUE TITLE
Unable to start - ImportError: cannot import name 'ParamSpec' from 'typing_extensions'

### ISSUE THREAD

**Issue by vladaman** [heartexlabs/label-studio#2210]
The Label Studio tool does not start after fresh install

* Python 3.8.10
* Ubuntu 5.13.0-30-generic
* pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

```
:/tmp$ label-studio

=> Database and media directory: /home/vlad/.local/share/label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 46133
Traceback (most recent call last):
  File "/home/vlad/.local/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/vlad/.local/lib/python3.8/site-packages/label_studio/server.py", line 282, in main
    _setup_env()
  File "/home/vlad/.local/lib/python3.8/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "/home/vlad/.local/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/vlad/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vlad/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/vlad/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vlad/.local/lib/python3.8/site-packages/label_studio/io_storages/models.py", line 5, in <module>
    from .azure_blob.models import AzureBlobImportStorage, AzureBlobImportStorageLink, AzureBlobExportStorage, AzureBlobExportStorageLink
  File "/home/vlad/.local/lib/python3.8/site-packages/label_studio/io_storages/azure_blob/models.py", line 14, in <module>
    from azure.storage.blob import BlobServiceClient, generate_blob_sas, BlobSasPermissions
  File "/home/vlad/.local/lib/python3.8/site-packages/azure/storage/blob/__init__.py", line 10, in <module>
    from ._blob_client import BlobClient
  File "/home/vlad/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 21, in <module>
    from azure.core.tracing.decorator import distributed_trace
  File "/home/vlad/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 31, in <module>
    from typing_extensions import ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/home/vlad/.local/lib/python3.8/site-packages/typing_extensions.py)
```

Might be related to https://giters.com/Azure/azure-sdk-for-python/issues/23697

**Comment by makseq** [comment]
@vladaman Please use virtualenv for LS

```
python -m venv new-env
source new-env/bin/activate
pip install label-studio
```

**Comment by nikitabelonogov** [comment]
Hi @vladaman 

I'm having trouble to reproduce that issue 
Could you please share the versions of _azure-core_ and _azure-storage-blob_ via `pip3 show azure-core azure-storage-blob`

**Comment by john-tseng-710** [comment]
Same issue encountered as on the attempt to start label-studio with command line.
Even I've installed it under new Python venv.

My configuration:
+ Python 3.9.10
+ pip 22.2.2
+ Windows 10 Professional (21H2)

Azure versions:

    Name: azure-core
    Version: 1.26.2
    Summary: Microsoft Azure Core Library for Python
    Home-page: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core
    Author: Microsoft Corporation
    Author-email: azpysdkhelp@microsoft.com
    License: MIT License
    Location: c:\users\john\appdata\local\programs\python\python39\lib\site-packages
    Requires: requests, six, typing-extensions
    Required-by: azure-storage-blob, msrest
    
    Name: azure-storage-blob
    Version: 12.14.1
    Summary: Microsoft Azure Blob Storage Client Library for Python
    Home-page: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-storage-blob
    Author: Microsoft Corporation
    Author-email: ascl@microsoft.com
    License: MIT License
    Location: c:\users\john\appdata\local\programs\python\python39\lib\site-packages
    Requires: azure-core, cryptography, msrest
    Required-by: label-studio


    Current platform is win32, apply sqlite fix
    Can't load sqlite3.dll from current directory
    => Database and media directory: C:\Users\john\AppData\Local\label-studio\label-studio
    => Static URL is set to: /static/
    => Database and media directory: C:\Users\john\AppData\Local\label-studio\label-studio
    => Static URL is set to: /static/
    Starting new HTTPS connection (1): pypi.org:443
    https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 54959
    Traceback (most recent call last):
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\Scripts\label-studio.exe\__main__.py", line 7, in <module>
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\label_studio\server.py", line 290, in main _setup_env()
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\label_studio\server.py", line 40, in _setup_env
        application = get_wsgi_application()
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\wsgi.py", line 12, in 
    get_wsgi_application
        django.setup(set_prefix=False)
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\django\__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\registry.py", line 114, in 
    populate
        app_config.import_models()
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\django\apps\config.py", line 301, in 
    import_models
        self.models_module = import_module(models_module_name)
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\label_studio\io_storages\models.py", line 5, in <module>
        from .azure_blob.models import AzureBlobImportStorage, AzureBlobImportStorageLink, AzureBlobExportStorage, 
    AzureBlobExportStorageLink
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site- packages\label_studio\io_storages\azure_blob\models.py", line 15, in <module>
        from azure.storage.blob import BlobServiceClient, generate_blob_sas, BlobSasPermissions
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\storage\blob\__init__.py", line 10, in <module>
        from ._blob_client import BlobClient
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\storage\blob\_blob_client.py", line 21, in <module>
        from azure.core.tracing.decorator import distributed_trace
      File "C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\azure\core\tracing\decorator.py", line 31, in <module>
        from typing_extensions import ParamSpec
    ImportError: cannot import name 'ParamSpec' from 'typing_extensions' 
    (C:\Users\john\AppData\Local\Programs\Python\Python39\lib\site-packages\typing_extensions.py)
    Sentry is attempting to send 2 pending error messages
    Waiting up to 2 seconds
    Press Ctrl-Break to quit

**Comment by makseq** [comment]
@john-tseng-710 Try this instructions:
https://stackoverflow.com/a/73532082/1045399

```
pip uninstall typing_extensions
pip uninstall fastapi
pip install --no-cache fastapi
```

Looks like not an LS issue, just a mess with package dependencies.

**Comment by john-tseng-710** [comment]
@makseq Thank you for reply. I successfully run LS service with docker. Maybe try this later and get back if it works. Still many thanks.
