### ISSUE TITLE
Failed to start: ImportError: cannot import name 'KeyTextTransform' from 'django.contrib.postgres.fields.jsonb'

### ISSUE THREAD

**Issue by teohsinyee** [heartexlabs/label-studio#2241]
After my installation, I want to launch label studio for the first time but get an error.

```
C:\Users\sin-yee.teoh>label-studio
Current platform is win32, apply sqlite fix
Can't load sqlite3.dll from current directory
=> Database and media directory: C:\Users\sin-yee.teoh\AppData\Local\label-studio\label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 46133
Traceback (most recent call last):
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\Scripts\label-studio.exe\__main__.py", line 7, in <module>
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\label_studio\server.py", line 282, in main
    _setup_env()
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\label_studio\server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\django\apps\config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\label_studio\users\models.py", line 18, in <module>
    from projects.models import Project
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\label_studio\projects\models.py", line 16, in <module>
    from tasks.models import Task, Prediction, Annotation, Q_task_finished_annotations, bulk_update_stats_project_tasks
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\label_studio\tasks\models.py", line 30, in <module>
    from data_manager.managers import PreparedTaskManager, TaskManager
  File "C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\label_studio\data_manager\managers.py", line 13, in <module>
    from django.contrib.postgres.fields.jsonb import KeyTextTransform
ImportError: cannot import name 'KeyTextTransform' from 'django.contrib.postgres.fields.jsonb' (C:\Users\sin-yee.teoh\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\postgres\fields\jsonb.py)
```

**Comment by makseq** [comment]
Looks like your environment uses incorrect version of postgres. Please use venv:

```
python -m venv env
env/bin/activate.bat
pip install label-studio
```

**Comment by teohsinyee** [comment]
Thanks @makseq , it works after installing it at virtual env. 1 Question, is it possible to **have multiple labels for each text line** for **Text classification** task. Referring to the picture below, I want to label 'Education' with 2 labels (education, header).
But with the current setting, I can only label each line with maximum 1 label.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/56106630/163743358-12d0447f-3570-49b8-988a-49c354007867.png">

**Comment by makseq** [comment]
Try to add `choice="multiple"` in your <Choices> tag.
