### ISSUE TITLE
Problems running on Windows with Anaconda

### ISSUE THREAD

**Issue by begnini** [heartexlabs/label-studio#234]
**Describe the bug**
I don't know if the problem is with Windows or with anaconda per se, but I stuck with little problems trying to run label-studio with this env combination.

First, during installation, I had the problem with the certifi package.

```
λ "c:\Program Files\Anaconda3\Scripts\pip.exe" install label-studio
...
Installing collected packages: idna, six, python-dateutil, certifi, urllib3, requests, Pillow, numpy, pytz, pandas, label-studio-converter, lxml, python-json-logger, attrs, jsonschema, tqdm, xmljson, MarkupSafe, Jinja2, wasabi, Werkzeug, mixpanel, Click, itsdangerous, Flask, orjson, flask-api, rarfile, label-studio
...
  Attempting uninstall: certifi
    Found existing installation: certifi 2018.8.24
ERROR: Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

I managed to install the package ignoring certifi

``` 
λ "c:\Program Files\Anaconda3\Scripts\pip.exe" install label-studio --ignore-installed certifi
...
Successfully installed Click-7.0 Flask-1.1.1 Jinja2-2.10.3 MarkupSafe-1.1.1 Pillow-6.2.1 Werkzeug-0.16.0 appdirs-1.4.3 attrs-19.1.0 blis-0.4.1 certifi-2019.11.28 chardet-3.0.4 cymem-2.0.3 flask-api-2.0 idna-2.8 importlib-metadata-1.5.0 itsdangerous-1.1.0 jsonschema-3.2.0 label-studio-0.4.8 label-studio-converter-0.0.11 lxml-4.5.0 mixpanel-4.4.0 numpy-1.18.1 orjson-2.5.1 pandas-1.0.1 pyrsistent-0.15.7 python-dateutil-2.8.1 python-json-logger-0.1.11 pytz-2019.3 rarfile-3.1 requests-2.23.0 setuptools-45.3.0 six-1.12.0 srsly-0.2.0 tqdm-4.40.2 urllib3-1.25.7 wasabi-0.4.2 xmljson-0.2.0 zipp-3.1.0
```

With the package installed, when I try to create a new project, the following error occurs:

```
λ label-studio.exe init captcha

Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\Scripts\label-studio.exe\__main__.py", line 4, in <module>
  File "c:\program files\anaconda3\lib\site-packages\label_studio\server.py", line 24, in <module>
    from label_studio.utils import uploader
  File "c:\program files\anaconda3\lib\site-packages\label_studio\utils\uploader.py", line 20, in <module>
    from .misc import Settings
  File "c:\program files\anaconda3\lib\site-packages\label_studio\utils\misc.py", line 49, in <module>
    file_handler = logging.FileHandler(logfile)
  File "c:\program files\anaconda3\lib\logging\__init__.py", line 1031, in __init__
    StreamHandler.__init__(self, self._open())
  File "c:\program files\anaconda3\lib\logging\__init__.py", line 1060, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)

PermissionError: [Errno 13] Permission denied: 'c:\\program files\\anaconda3\\lib\\site-packages\\label_studio\\static\\logs\\service.log'
```

Of course, you can't write a log in the program files directory. The problem seems to be in this line

https://github.com/heartexlabs/label-studio/blob/796c64a66d3fbdc48ed2e497dc96b14ce852b81b/label_studio/utils/misc.py#L43

Maybe we can configure the directory log in 'logger.json' or use the current directory instead ```dirname(__file__)```.

**Environment (please complete the following information):**
 - OS: Windows 10 Pro 64
 - Version: 0.4.8

**Comment by niklub** [comment]
Hi, @begnini ! Thanks reporting this. Please check the fix in the [latest release](https://github.com/heartexlabs/label-studio/releases/tag/v0.5.0) (`pip install label-studio==0.5.0`)

**Comment by begnini** [comment]
Tested and working fine. Thanks for your support.
