### ISSUE TITLE
Migration fails when running label-studio with remote POSTGRE_HOST environment variables

### ISSUE THREAD

**Issue by GiacomoCherry** [heartexlabs/label-studio#2344]
**Describe the bug**
`django.db.migrations.exceptions.NodeNotFoundError: Migration data_manager.0001_squashed_0005_view_user dependencies reference nonexistent parent node ('projects', '0060_merge_20210126_1328')`

Hi everyone and congrats for the amazing tool.
I'm trying do start a local docker instance of label-studio with a remote postgresql db.
As you can see from my dockerfile down here, I'm pulling the latest label-studio image and declaring the required env variables.
The docs ( [here](https://labelstud.io/guide/storedata.html#Create-connection-on-startup) ) suggests to run label-studio with this command `CMD [label-studio start my_project --init -db postgresql]` but in this way it fails to connect to the db.
Instead, by simply running CMD ["label-studio"]` the connection with the remote db goes smoothly, but then Django fails the migration process (is it migrating only system tables? because it's the first time I'm running it so I don't have any data to migrate).

Am I doing something wrong? it looks like Django doesn't find the migration data, but what data is he looking for?

`FROM heartexlabs/label-studio:latest

ENV DJANGO_DB=default
ENV POSTGRE_NAME=xxxdb
ENV POSTGRE_USER=userxx
ENV POSTGRE_PASSWORD=xxxxxxxx
ENV POSTGRE_PORT=5432
ENV POSTGRE_HOST=xx.xx.xxx.xxx

CMD ["label-studio"]`

**To Reproduce**
1. run `docker build -t test-labelstudio . `
2. run docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data test-labelstudio 
3. Result:
 `./deploy/docker-entrypoint.sh: Looking for init scripts in /label-studio/deploy/docker-entrypoint.d/
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/10-copy-static-data.sh
=> Skipping copy data.
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/20-wait-for-db.sh
=> Waiting for postgres...
=> Postgres is up.
./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/30-run-db-migrations.sh
=> Do database migrations...
=> Database and media directory: /label-studio/data
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 46133
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/loader.py", line 255, in build_graph
    self.graph.validate_consistency()
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration data_manager.0001_squashed_0005_view_user dependencies reference nonexistent parent node ('projects', '0060_merge_20210126_1328')`

**Environment (please complete the following information):**
 - OS: MacOs: 11.1
 - Label Studio Version: Latest on dockerHub (1.4.1 I suppose)

**Comment by triklozoid** [comment]
@GiacomoCherry your settings looks right. Is it a clear database instance? Can you try to drop it and start from empty one?
