### ISSUE TITLE
The container does not work with MySQL

### ISSUE THREAD

**Issue by jlobo** [heartexlabs/label-studio#2365]
**Describe the bug**
The docker container doesn't work when configured to use mysql.
> Apparently label-studio doesn't come with the python client for mysql because the error is displayed is `ModuleNotFoundError: No module named 'MySQLdb'` 

When the client is installed before the service starts with `pip3 install mysqlclient && label-studio start`, the migrations do not finish.
> Even after executing the command `ALTER DATABASE 'labelstudio' CHARACTER SET utf8;` in the database, the same error `django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')` is shown.

**To Reproduce**
1. Configure the docker-compose file to use mysql
2. run `docker-compose up`

**Expected behavior**
Just to run with mysql

**Screenshots 1**
```
app_1  | ./deploy/docker-entrypoint.sh: Looking for init scripts in /label-studio/deploy/docker-entrypoint.d/
app_1  | ./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/10-copy-static-data.sh
app_1  | => Copy static data to a shared folder...
app_1  | => Successfully copied.
app_1  | ./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/20-wait-for-db.sh
app_1  | => Waiting for MySQL...
app_1  | => MySQL is up.
app_1  | ./deploy/docker-entrypoint.sh: Launching /label-studio/deploy/docker-entrypoint.d/30-run-db-migrations.sh
app_1  | => Do database migrations...
app_1  | => Database and media directory: /label-studio/data
app_1  | => Static URL is set to: /static/
app_1  | Starting new HTTPS connection (1): pypi.org:443
app_1  | https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 46133
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 15, in <module>
app_1  |     import MySQLdb as Database
app_1  | ModuleNotFoundError: No module named 'MySQLdb'
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/label-studio/label_studio/manage.py", line 22, in <module>
app_1  |     execute_from_command_line(sys.argv)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
app_1  |     utility.execute()
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 377, in execute
app_1  |     django.setup()
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/__init__.py", line 24, in setup
app_1  |     apps.populate(settings.INSTALLED_APPS)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/apps/registry.py", line 114, in populate
app_1  |     app_config.import_models()
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/apps/config.py", line 211, in import_models
app_1  |     self.models_module = import_module(models_module_name)
app_1  |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
app_1  |     return _bootstrap._gcd_import(name[level:], package, level)
app_1  |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
app_1  |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
app_1  |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
app_1  |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
app_1  |   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
app_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/models.py", line 2, in <module>
app_1  |     from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/base_user.py", line 48, in <module>
app_1  |     class AbstractBaseUser(models.Model):
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 122, in __new__
app_1  |     new_class.add_to_class('_meta', Options(meta, app_label))
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 326, in add_to_class
app_1  |     value.contribute_to_class(cls, name)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/models/options.py", line 206, in contribute_to_class
app_1  |     self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/__init__.py", line 28, in __getattr__
app_1  |     return getattr(connections[DEFAULT_DB_ALIAS], item)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 214, in __getitem__
app_1  |     backend = load_backend(db['ENGINE'])
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 111, in load_backend
app_1  |     return import_module('%s.base' % backend_name)
app_1  |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
app_1  |     return _bootstrap._gcd_import(name[level:], package, level)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 17, in <module>
app_1  |     raise ImproperlyConfigured(
app_1  | django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
app_1  | Did you install mysqlclient?
app_1  | Sentry is attempting to send 2 pending error messages
app_1  | Waiting up to 2 seconds
app_1  | Press Ctrl-C to quit
classipii_app_1 exited with code 1
```

**Screenshots 2**
```
app_1  | Starting new HTTPS connection (1): pypi.org:443
app_1  | https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 46133
app_1  | Initializing database..
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
app_1  |     return self.cursor.execute(sql, params)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
app_1  |     return self.cursor.execute(query, args)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 206, in execute
app_1  |     res = self._query(query)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 319, in _query
app_1  |     db.query(q)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 254, in query
app_1  |     _mysql.connection.query(self, query)
app_1  | MySQLdb._exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/bin/label-studio", line 33, in <module>
app_1  |     sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
app_1  |   File "/label-studio/label_studio/server.py", line 283, in main
app_1  |     _apply_database_migrations()
app_1  |   File "/label-studio/label_studio/server.py", line 59, in _apply_database_migrations
app_1  |     call_command('migrate', '--no-color', verbosity=0)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 168, in call_command
app_1  |     return command.execute(*args, **defaults)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 371, in execute
app_1  |     output = self.handle(*args, **options)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 85, in wrapped
app_1  |     res = handle_func(*args, **kwargs)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/core/management/commands/migrate.py", line 243, in handle
app_1  |     post_migrate_state = executor.migrate(
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 117, in migrate
app_1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
app_1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
app_1  |     state = migration.apply(state, schema_editor)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/migration.py", line 124, in apply
app_1  |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/migrations/operations/models.py", line 808, in database_forwards
app_1  |     schema_editor.add_constraint(model, self.constraint)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/schema.py", line 362, in add_constraint
app_1  |     self.execute(sql)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/schema.py", line 142, in execute
app_1  |     cursor.execute(sql, params)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/sentry_sdk/integrations/django/__init__.py", line 544, in execute
app_1  |     return real_execute(self, sql, params)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
app_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
app_1  |     return executor(sql, params, many, context)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
app_1  |     return self.cursor.execute(sql, params)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
app_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
app_1  |     return self.cursor.execute(sql, params)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/django/db/backends/mysql/base.py", line 73, in execute
app_1  |     return self.cursor.execute(query, args)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 206, in execute
app_1  |     res = self._query(query)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/cursors.py", line 319, in _query
app_1  |     db.query(q)
app_1  |   File "/usr/local/lib/python3.8/dist-packages/MySQLdb/connections.py", line 254, in query
app_1  |     _mysql.connection.query(self, query)
app_1  | django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')
app_1  | Sentry is attempting to send 2 pending error messages
app_1  | Waiting up to 2 seconds
app_1  | Press Ctrl-C to quit
classipii_app_1 exited with code 1
```

**Environment (please complete the following information):**
 - OS: [windows]
 - Label Studio Version [latest]

**Additional context**

**Comment by makseq** [comment]
Unfortunately LS doesn't support mysql officially. 
Similar issue: https://github.com/heartexlabs/label-studio/issues/1896

You can try to install it using `pip install label-studio[mysql]`.

**Comment by chengtm** [comment]
> 

now can't install label_studio[mysql] ,when i try it return:  'no matches found: label-studio[mysql]'

**Comment by makseq** [comment]
```
pip install label-studio[mysql]
```
