### ISSUE TITLE
'Annotation' object has no attribute '_tracker'

### ISSUE THREAD

**Issue by safehumeng** [heartexlabs/label-studio#2377]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/webhooks/utils.py", line 114, in wrap
    responce = func(self, request, *args, **kwargs)
  File "/label-studio/label_studio/tasks/api.py", line 291, in patch
    return super(AnnotationAPI, self).patch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/generics.py", line 288, in patch
    return self.partial_update(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "/label-studio/label_studio/tasks/api.py", line 279, in update
    return super(AnnotationAPI, self).update(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/mixins.py", line 78, in perform_update
    serializer.save()
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 1006, in update
    instance.save()
  File "/label-studio/label_studio/tasks/models.py", line 366, in save
    result = super().save(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 753, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/dist-packages/model_utils/tracker.py", line 254, in inner
    getattr(instance, self.attname).set_saved_fields(
AttributeError: 'Annotation' object has no attribute '_tracker'

**Comment by makseq** [comment]
This issue was solved in the last master/develop branch commits. Please, try to use LS from there.

**Comment by safehumeng** [comment]
it works! thanks!
