### ISSUE TITLE
Issue with uploading data

### ISSUE THREAD

**Issue by buntys2010** [heartexlabs/label-studio#245]
**Describe the bug**
Whenever i try to add a new line in sample file , it is showing below error

```
Traceback (most recent call last):
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\bunty.shah\appdata\roaming\python\python37\scripts\doc_app\lib\site-packages\label_studio\server.py", line 409, in api_import
    old_tasks = json.load(open(path))
  File "c:\users\bunty.shah\appdata\local\continuum\anaconda3\Lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "c:\users\bunty.shah\appdata\local\continuum\anaconda3\Lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\bunty.shah\appdata\local\continuum\anaconda3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\bunty.shah\appdata\local\continuum\anaconda3\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 353 column 21 (char 7135)
```
I have tried both CSV and Text files.

**To Reproduce**
1. Go to import task 
2. Click on upload data
4. Error: can't upload/process file on server side. Reasons: Critical error, see console for more description

**Expected behavior**
With Sample file without new addition it is working fine as expected.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22]  80.0.3987.162

**Additional context**

**Comment by deppp** [comment]
@buntys2010 Can you please provide a minimal config and a sample of the CSV file that produces that error. Without that, it's hard to tell if the error is in the code or in the input. Thanks!

**Comment by bigwayne** [comment]
@buntys2010 This happened to me too, I was able to fix it; let me take a guess at what happened to you:

I tried to Import Tasks from a file containing Unicode characters that failed to transcode during the conversion from Input Data to Task, causing the process to abort _while_ writing to `tasks.json`, causing an incomplete JSON document, producing an error similar to the one pasted in your OP whenever Label Studio (LS) tries to read its own `tasks.json` file before manipulating it during subsequent Import requests.

To see if I'm on the right track, and to take the first step to fixing it, follow:

* In the project directory (containing the `config.xml` generated by you or LS), you should also see `tasks.json` Open this file and scroll to the bottom. Is it complete, valid JSON? Or does it look like an unfinished homework assignment?
* If it's complete, then it's not your tasks file and this was a bad guess; your issue isn't my own.
* If it's incomplete, note the `id` of the incomplete record, because that's the line in your CSV/Source document causing the initial problem. For example, this would point me to Line 213 in my CSV:
![Incomplete tasks.json](https://user-images.githubusercontent.com/673786/79629459-dc0b5480-80fe-11ea-807d-e052d003af67.png)
* Fix the error in the CSV, and either delete `tasks.json` and start over, or remove the incomplete record and close up the JSON document to make it valid again.
