### ISSUE TITLE
Python error when trying to run label-studio after installing via pip

### ISSUE THREAD

**Issue by haimat** [heartexlabs/label-studio#2460]
**Describe the bug**
I installed Label Studio via `pip`, as described on the main GitHub page. However, when I try to run it a Python exception is being thrown:

```
$ label-studio
=> Database and media directory: /home/mfb/.local/share/label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 46133
Traceback (most recent call last):
  File "/home/mfb/.local/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/mfb/.local/lib/python3.8/site-packages/label_studio/server.py", line 282, in main
    _setup_env()
  File "/home/mfb/.local/lib/python3.8/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "/home/mfb/.local/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/mfb/.local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mfb/.local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/mfb/.local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mfb/.local/lib/python3.8/site-packages/label_studio/users/models.py", line 18, in <module>
    from projects.models import Project
  File "/home/mfb/.local/lib/python3.8/site-packages/label_studio/projects/models.py", line 16, in <module>
    from tasks.models import Task, Prediction, Annotation, Q_task_finished_annotations, bulk_update_stats_project_tasks
  File "/home/mfb/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 29, in <module>
    from core.label_config import SINGLE_VALUED_TAGS
  File "/home/mfb/.local/lib/python3.8/site-packages/label_studio/core/label_config.py", line 9, in <module>
    import jsonschema
  File "/usr/lib/python3/dist-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 152, in <module>
    @attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'
```

**To Reproduce**
1. run `pip install label-studio`
2. run `label-studio`

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version: latest version from PyPi

**Comment by makseq** [comment]
```
python3 -m venv env
source env/bin/activate 
pip install label-studio
label-studio
```

**Comment by Stinosko** [comment]
This fixed it for me without virtual environment:
> pip uninstall attr
> pip install attrs

Reference: [stackoverflow](https://stackoverflow.com/questions/49228744/attributeerror-module-attr-has-no-attribute-s)

**Comment by janru** [comment]
uninstalling attr and installing attrs didn't solve the issue for me.
I got it working with
`pip uninstall attr
pip install jsonschema==4.9.1 attrs==22.1.0`
