### ISSUE TITLE
Issues setting up tasks.json – AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by asdfang** [heartexlabs/label-studio#252]
**Describe the bug**
AttributeError: 'list' object has no attribute 'items' when I try to run with my own `tasks.json`.

**To Reproduce**
1. I installed version 0.5.1 with `pip` yesterday, and used the default initialization `label-studio start my_labeling_project --init`
2. My `tasks.json`, inspired by [text_pairwise/tasks.json](https://github.com/heartexlabs/label-studio/blob/master/label_studio/examples/text_pairwise/tasks.json) and [audio_classification/tasks.json](https://github.com/heartexlabs/label-studio/blob/master/label_studio/examples/audio_classification/tasks.json):
```
[
    {
        "data": {
            "url-a": "https://go.heartex.net/static/samples/game.wav",
            "url-b": "https://go.heartex.net/static/samples/game.wav"
        }
    }
]
```
3. My `config.xml`:
```
<View>
  <Pairwise name="pairwise" leftClass="audio-a" rightClass="audio-b" toName="choice-a,choice-b"></Pairwise>
  <Header value="Choice A"></Header>
  <Audio name="choice-a" value="$url-a"></Audio>
  <Header value="Choice B"></Header>
  <Audio name="choice-b" value="$url-b"></Audio>
  
  <Choices name="selection" toName="choice-a,choice-b" choice="single-radio">
    <Choice alias="a" value="A"></Choice>
    <Choice alias="b" value="B"></Choice>
  </Choices>
</View>
```
4. Ran with: `label-studio start ./my_labeling_project`. Got this error:
```
[2020-04-08 14:32:01,802] [werkzeug] [INFO]  * Running on http://0.0.0.0:8200/ (Press CTRL+C to quit)
[2020-04-08 14:32:01,854] [label_studio.server] [ERROR] Exception on /welcome [GET]
Traceback (most recent call last):
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/server.py", line 151, in welcome_page
    project = project_get_or_create()
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/server.py", line 82, in project_get_or_create
    'multi_session': False
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/project.py", line 611, in get_or_create
    project = cls.get(project_name, args, context)
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/project.py", line 594, in get
    project = cls._load_from_dir(project_dir, project_name, args, context)
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/project.py", line 582, in _load_from_dir
    return cls(config, project_name, context)
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/project.py", line 44, in __init__
    self.load_tasks()
  File "/Users/asdfang/.conda/envs/bm-eval-dev/lib/python3.7/site-packages/label_studio/project.py", line 64, in load_tasks
    for task_id, task in tasks.items():
AttributeError: 'list' object has no attribute 'items'
```

**Expected behavior**
I expected to go to `http://localhost:8200/` and see two audio files, two radio buttons, and some headers and values.

**Screenshots**

**Environment (please complete the following information):**
 - macOS 10.14.6
 - Chrome
 - label-studio 0.5.1

**Additional context**
I have hundreds of pairs of audio to compare so I'm also looking to work towards a [directory with JSON files](https://labelstud.io/guide/tasks.html#Directory-with-JSON-files) for my tasks. It is my understanding that I can edit `tasks.json` myself without needing to import through the web interface, but I am confused on what the expected format is as the above doesn't work. Thanks!

**Comment by niklub** [comment]
Hi, @asdfang ! Instead of modifying tasks.json inside project directory, you have to provide your tasks.json as input file. Please check documentation about importing files https://labelstud.io/guide/tasks.html#Import-formats
