### ISSUE TITLE
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField',Sentry is attempting to send 2 pending error messages

### ISSUE THREAD

**Issue by monkeycc** [heartexlabs/label-studio#2996]
**Describe the bug**
```
label-studio
Current platform is win32, apply sqlite fix
Can't load sqlite3.dll from current directory
=> Database and media directory: C:\Users\AI\AppData\Local\label-studio\label-studio
=> Static URL is set to: /static/
Traceback (most recent call last):
  File "D:\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\label-studio.exe\__main__.py", line 7, in <module>
Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
  File "D:\Anaconda3\lib\site-packages\label_studio\server.py", line 282, in main
    _setup_env()
  File "D:\Anaconda3\lib\site-packages\label_studio\server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "D:\Anaconda3\lib\site-packages\django\core\wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "D:\Anaconda3\lib\site-packages\django\__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "D:\Anaconda3\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "D:\Anaconda3\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "D:\Anaconda3\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "D:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Anaconda3\lib\site-packages\label_studio\core\settings\label_studio.py", line 46, in <module>
    from label_studio.core.utils.common import collect_versions
  File "D:\Anaconda3\lib\site-packages\label_studio\core\utils\common.py", line 36, in <module>
    from drf_yasg.inspectors import CoreAPICompatInspector, NotHandled
  File "D:\Anaconda3\lib\site-packages\drf_yasg\inspectors\__init__.py", line 5, in <module>
    from .field import (
  File "D:\Anaconda3\lib\site-packages\drf_yasg\inspectors\field.py", line 406, in <module>
    (serializers.NullBooleanField, (openapi.TYPE_BOOLEAN, None)),
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
https://o227124.ingest.sentry.io:443 "POST /api/5820521/store/ HTTP/1.1" 200 41
```

**To Reproduce**
```
conda create --name label-studio
conda activate label-studio
pip install label-studio
label-studio
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [WIN11]
 - Label Studio Version [ label-studio  1.5.0.post0 ]
 - Python 3.9.12

**Additional context**

**resolvent**
`pip install djangorestframework==3.13.1`

**Comment by linhandev** [comment]
Same here.

**Comment by cs-mshah** [comment]
Yep, even I faced this issue.

**Comment by mattiasostmar** [comment]
Same here. An issue has been opened about this over at django-rest-framework aswell as it seems to be on that side. https://github.com/encode/django-rest-framework/discussions/8667

**Comment by makseq** [comment]
It was fixed in the latest develop branch commits.

**Comment by mattiasostmar** [comment]
@makseq It seems that this open issue is related https://github.com/encode/django-rest-framework/discussions/8667#discussioncomment-3741129

**Comment by makseq** [comment]
@mattiasostmar looks like yes. 
BTW LS 1.6 is release today, the fix is included there.

**Comment by tobiolusa** [comment]
I use drf 3.140 and still face the issue. Any remedy
