### ISSUE TITLE
pip install fails with python 3.8.13 and 3.10.6

### ISSUE THREAD

**Issue by udaylunawat** [heartexlabs/label-studio#3169]
**Describe the bug**
pip install fails with python 3.8.13 and 3.10.6.
docker image is very slow on M1 mac.

**To Reproduce**

```bash
conda create -n label-studio python=3.8 -y
conda activate label-studio
pip install label-studio
```

**Expected behavior**
Succesfully install label-studio

**Environment (please complete the following information):**
 - OS: macOS 12.6
 - Label Studio Version 1.6.0
 - Macbook Air M1 (arm64)

**Additional context**
- Does not works with 3.8.13 & 3.10.6
- Works with 3.9.13

```bash
File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/setup.py", line 540, in <module>
          setuptools.setup(
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
          cmd_obj.run()
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
          self.build_extensions()
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/src/python/grpcio/commands.py", line 284, in build_extensions
          raise CommandError(
      commands.CommandError: Failed `build_ext` step:
      Traceback (most recent call last):
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 186, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
          _classic_spawn(self, command)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/ccompiler.py", line 1007, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/spawn.py", line 70, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/src/python/grpcio/commands.py", line 280, in build_extensions
          build_ext.build_ext.build_extensions(self)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
          self._build_extensions_serial()
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
          self.build_extension(ext)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
          objects = self.compiler.compile(
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/src/python/grpcio/_parallel_compile_patch.py", line 58, in _parallel_compile
          multiprocessing.pool.ThreadPool(BUILD_EXT_COMPILER_JOBS).map(
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/multiprocessing/pool.py", line 364, in map
          return self._map_async(func, iterable, mapstar, chunksize).get()
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/multiprocessing/pool.py", line 771, in get
          raise self._value
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/multiprocessing/pool.py", line 125, in worker
          result = (True, func(*args, **kwds))
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
          return list(map(*args))
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/private/var/folders/6v/yt4tc8zn2fj34ywnff97tqp00000gp/T/pip-install-kmave9uw/grpcio_a793c6914210474389d16ead055f125b/src/python/grpcio/commands.py", line 263, in new_compile
          return old_compile(obj, src, ext, cc_args, extra_postargs,
        File "/Users/uday/miniforge3/envs/label-studio/lib/python3.8/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> grpcio

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by makseq** [comment]
@udaylunawat Try this solution:
https://stackoverflow.com/a/62500932/1045399
