### ISSUE TITLE
Unable to label NER tasks: TypeError: e.id.replace is not a function

### ISSUE THREAD

**Issue by wpnbos** [heartexlabs/label-studio#3171]
**Describe the bug**
When clicking `Label All Tasks`, the app shows an infinite loading screen and the console logs the following error: `TypeError: e.id.replace is not a function`.

**To Reproduce**
1. Create a NER project
2. Import the following JSON containing a task:
```json
[{"data": {"text": "Hi, I'd like to order 6 ST ABC123 (Power drill v3 with extensions)", "strapi_id": 1}, "predictions": [{"model_version": "Azure", "result": [{"id": 0, "from_name": "label", "to_name": "text", "type": "labels", "readonly": false, "value": {"start": 22, "end": 23, "score": 1.0, "text": "6", "labels": ["quantity"], "readonly": false}}, {"id": 1, "from_name": "label", "to_name": "text", "type": "labels", "readonly": false, "value": {"start": 24, "end": 26, "score": 1.0, "text": "ST", "labels": ["quantity_unit"], "readonly": false}}]}]}]
```
3. Click `Label All Tasks`
4. The screen is stuck on a permanent loading screen

**Expected behavior**
The labeling view should appear, allowing the user to label documents

**Screenshots**
<img width="1504" alt="afbeelding" src="https://user-images.githubusercontent.com/33165624/198996421-e7d0734c-54c0-4730-a311-8bef06c902e3.png">

**Environment (please complete the following information):**
 - Mac OS, Firefox
 - Label Studio Version 1.6.0rc5 (latest Docker image)

**Comment by wpnbos** [comment]
There's also an additional problem: the imported predictions are set to `readonly` even though the imported JSON specifies that they should not be.

**Comment by makseq** [comment]
1 Could you show your labeling config?
2 Could you switch to the latest develop version, as I remember it's a bug with readonly and it was fixed in the develop branch a few days ago.

**Comment by wpnbos** [comment]
> 1 Could you show your labeling config? 2 Could you switch to the latest develop version, as I remember it's a bug with readonly and it was fixed in the develop branch a few days ago.

The labeling config:
```
<View>
  <Labels name="label" toName="text">
    
    
    
    
  <Label value="person_requesting" background="#FFA39E"/><Label value="company_requesting" background="#D4380D"/><Label value="product_name" background="#FFC069"/><Label value="product_number" background="#AD8B00"/><Label value="quantity" background="#D3F261"/><Label value="quantity_unit" background="#389E0D"/><Label value="date_requested" background="#5CDBD3"/><Label value="period_requested" background="#096DD9"/><Label value="price" background="#ADC6FF"/><Label value="invoice_address" background="#9254DE"/><Label value="shipping_address" background="#F759AB"/><Label value="email_requesting" background="#FFA39E"/></Labels>

  <Text name="text" value="$text"/>
</View>
```

I'll try switching to the development branch, assuming there's a Docker image available for it.

Thanks for your response!

**Comment by makseq** [comment]
As I remember there should be `:develop` docker image

**Comment by wpnbos** [comment]
Yes I found it. I tried the develop branch but it seems the predictions are still locked in to `readonly`

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/33165624/199931605-eade7871-0aed-48e0-861b-946b03d9725f.png">

**Comment by zhbuaa0** [comment]
there is a bug in label-studio==1.6.0
1.try verson 1.4.1
2.try replace "predications" to "annotations"
3.add "readonly": false in result list(maybe not helpful)
 {
            "id": 1,
            "from_name": "bbox",
            "to_name": "image",
            "type": "rectangle",
            "readonly": false,
            "value": {
              "x": 4.193548387096774,
              "y": 3.249714937286203,
              "width": 17.177419354838708,
              "height": 1.7388825541619157,
              "rotation": 0
            }

**Comment by makseq** [comment]
Does the latest develop version of LS solve this problem?

**Comment by wpnbos** [comment]
@makseq I tried running the develop version but it fails at startup with this error:

```
sudo docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:develop
=> Database and media directory: /label-studio/data
=> Static URL is set to: /static/
=> Database and media directory: /label-studio/data
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 52124
Initializing database..
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 421, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/label-studio", line 33, in <module>
    sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
  File "/label-studio/label_studio/server.py", line 291, in main
    _apply_database_migrations()
  File "/label-studio/label_studio/server.py", line 67, in _apply_database_migrations
    call_command('migrate', '--no-color', verbosity=0)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/schema.py", line 330, in add_field
    self._remake_table(model, create_field=field)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/schema.py", line 282, in _remake_table
    self.create_model(new_model)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 345, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/django/__init__.py", line 563, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/sqlite3/base.py", line 421, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: attempt to write a readonly database
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

I tried the `latest` image as well afterwards to verify that the cause wasn't a problem with my setup. The `latest` image started and ran fine.

**Comment by farioas** [comment]
@wpnbos try to force pull the real "latest" version:
```
$ docker pull heartexlabs/label-studio:develop
$ docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:develop
```

By default docker daemon runs available tag instead of pulling a new one from the Hub

**Comment by wpnbos** [comment]
@farioas thanks for helping out! I did that already, just didn't include the command and output in the traceback I posted here.

**Comment by makseq** [comment]
@wpnbos if the problem is solved, please close the ticket :-)

**Comment by keithcallenberg** [comment]
I haven't tried the :develop / "latest" version yet, but I have this same issue on label-studio 1.6.0rc5. The problem goes away if I turn off "Show predictions to annotators in the Label Stream and Quick View" in the Project Settings > Machine Learning menu. But this turns off the predictions, and I would like to keep them on.

**Comment by keithcallenberg** [comment]
This other issue #2299 mentioned that the `id` of the pre-annotations should be a string. Changing this from int to str solved it for me.
https://github.com/heartexlabs/label-studio/issues/2299#issuecomment-1115824019
