### ISSUE TITLE
Key (id) already exists

### ISSUE THREAD

**Issue by ktobah** [heartexlabs/label-studio#3213]
**Describe the bug**
We had an instance of LS running using SQLite. Then, I created a new instance that uses Postgres.

I got a copy of the label_studio.sqlite3 db, and using Datagrip, I manually migrated the whole DB content to the new Postgres instance. I did not copy the users, instead, I recreated them.

I can log in, see all the projects and open them. I tried to open one image to annotate it, but once I finish and click submit I get an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "task_completion_pkey"
DETAIL:  Key (id)=(1614) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/./webhooks/utils.py", line 114, in wrap
    responce = func(self, request, *args, **kwargs)
  File "/label-studio/label_studio/./tasks/api.py", line 356, in post
    return super(AnnotationsListAPI, self).post(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/label-studio/label_studio/./tasks/api.py", line 397, in perform_create
    annotation = ser.save(**extra_args)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/label-studio/label_studio/./tasks/models.py", line 431, in save
    result = super().save(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/django/__init__.py", line 563, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "task_completion_pkey"
DETAIL:  Key (id)=(1614) already exists.
```

**To Reproduce**
1. Open an image to annotate
2. Finish and click Submit
3. See error

**Expected behavior**
Annotations should be saved.

**Environment (please complete the following information):**
 - Label Studio Version [1.6.1dev]

**Comment by makseq** [comment]
It sounds like DB tries to create an annotation with id that is already exists in DB. 
If you are trying to migration sqlite to postgres, you should copy everything and then do some db checkups (don't know exactly which one, but most likely they should be there). Also you can see VACUUM for postgres.

We have some plans about native LS ways for migrations between sqlite => postgres, hope they will be available after some time.

I can't say it's a normal way to use LS, so I have to close this issue.
