### ISSUE TITLE
Renaming labels error on PostgreSQL

### ISSUE THREAD

**Issue by shimuldn** [heartexlabs/label-studio#3330]
Contains lookup is not supported on this database backend is the error. Tried SQLite database and PostgreSQL

```
Traceback (most recent call last):
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/label_studio/data_manager/api.py", line 333, in post
    result = perform_action(action_id, project, queryset, request.user, **kwargs)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/label_studio/data_manager/actions/__init__.py", line 123, in perform_action
    raise e
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/label_studio/data_manager/actions/__init__.py", line 119, in perform_action
    result = action['entry_point'](project, queryset, **kwargs)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/label_studio/data_manager/actions/experimental.py", line 136, in rename_labels
    for annotation in annotations:
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 528, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/sql/where.py", line 81, in as_sql
    sql, params = compiler.compile(child)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/django/db/models/fields/json.py", line 143, in as_sql
    raise NotSupportedError(
django.db.utils.NotSupportedError: contains lookup is not supported on this database backend.

```
<img width="527" alt="image" src="https://user-images.githubusercontent.com/12117121/204553843-3c90418c-3131-4938-9699-d01f771ed23c.png">

**Comment by makseq** [comment]
![image](https://user-images.githubusercontent.com/501780/204708917-f2bfa4e2-07f1-4c69-89c9-9dae7fbe9955.png)

@shimuldn are you sure you are using the latest LS version? I don't see any suspicious code on this line 136 as mentioned in your logs.

**Comment by shimuldn** [comment]
Installed from pip
Also installed from https://github.com/heartexlabs/label-studio#install-for-local-development
Same error

<img width="646" alt="image" src="https://user-images.githubusercontent.com/12117121/204777544-42116f5d-ae1b-4aeb-98f2-466cd92b3324.png">

**Comment by makseq** [comment]
Please try the develop branch now, it should work. 
Seems you tried it only on sqlite, I found this error there only. 
Postgres works well.

**Comment by shimuldn** [comment]
@makseq Thank you, i am able to use the renaming now.
How can i set up systemd service to use postgresql and data dir?

The bellow file run label-studio with renaming future but i need to set up data_dir and db as postgresql

Thank you

```
[Unit]
Description=Label Studio

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/label-studio

Environment=EXPERIMENTAL_FEATURES=1
Environment=data-dir=/home/ubuntu/data
Environment=data_dir=/home/ubuntu/data

ExecStart=/home/ubuntu/label-studio/.venv/bin/python3 label_studio/manage.py runserver
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=3
SyslogIdentifier=hcaptcha-webhook

[Install]
WantedBy=multi-user.target
Alias=label.service
```

**Comment by makseq** [comment]
> How can i set up systemd service to use postgresql and data dir?

Sorry, this question is out of the Label Studio scope. Try `sudo apt install postgresql`.

**Comment by shimuldn** [comment]
Installing via pip install label-studio, we can use this to run from systemd

```
[Unit]
Description=Label Studio

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/label-studio

Environment=EXPERIMENTAL_FEATURES=1
ExecStart=/home/ubuntu/label-studio/.venv/bin/label-studio start demo --init -db postgresql --data-dir /home/ubuntu/data
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=3
SyslogIdentifier=hcaptcha-webhook

[Install]
WantedBy=multi-user.target
Alias=label.service
```
Or
`EXPERIMENTAL_FEATURES=1 /home/ubuntu/label-studio/.venv/bin/python3 /home/ubuntu/label-studio/.venv/bin/label-studio start demo --init -db postgresql --data-dir /home/ubuntu/data` to run from the terminal.

But using the https://github.com/heartexlabs/label-studio#install-for-local-development not working as i am not able to pass the `-db` and `--data-dir` args from systemd.

Using `EXPERIMENTAL_FEATURES=1 /home/ubuntu/label-studio/.venv/bin/python3 label_studio/manage.py runserver demo --init -db postgresql --data_dir /home/ubuntu/data`

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/12117121/205422746-36603d8c-3b54-4f8a-8ab1-952d22f29a99.png">


Using `EXPERIMENTAL_FEATURES=1 /home/ubuntu/label-studio/.venv/bin/python3 /home/ubuntu/label-studio/.venv/bin/label-studio start demo --init -db postgresql --data-dir /home/ubuntu/data`

```
Traceback (most recent call last):
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytz 2019.3 (/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages), Requirement.parse('pytz>=2020.1'), {'pandas'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/label-studio/.venv/bin/label-studio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytz 2019.3 (/home/ubuntu/label-studio/.venv/lib/python3.8/site-packages), Requirement.parse('pytz>=2020.1'), {'pandas'})
```

Installing `pytz==2020.1' creates problem with pandas


Sorry for the confusion.
