### ISSUE TITLE
Exporting the interpolated frames resulted in status- Failed

### ISSUE THREAD

**Issue by praveenporsche** [heartexlabs/label-studio#3355]
I have created a project with about 61 video files for annotation. After completing the annotation, I used the API `http://localhost:8080/api/projects/1/exports` to export my snapshot with the following headers
```

{
"title": "test",
"created_by": {
                "id": 1,
                "first_name": "",
                "last_name": "",
                "email": "[praveen@praveen.com](mailto:praveen@praveen.com)"
            },
"serialization_options": {
"drafts": {
"only_id": false
},
"predictions": {
"only_id": false
},
"annotations__completed_by": {
"only_id": false
},
"interpolate_key_frames": true
}
}
```

I however get a response that with the `status:failed` error code. 
In the console, I get the following error when I'm attempting to export a snapshot.

```
[2022-12-02 05:35:35,615] [data_export.mixins::export_to_file::264] [ERROR] Export was failed
Traceback (most recent call last):
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio/data_export/mixins.py", line 241, in export_to_file
    SerializableGenerator(
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio/core/utils/io.py", line 162, in __init__
    self._head = iter([next(tmp_body)])
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio/data_export/mixins.py", line 207, in get_export_data
    for task in serializer.data:
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio/data_export/serializers.py", line 58, in to_representation
    return super().to_representation(task)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_flex_fields/serializers.py", line 64, in to_representation
    return super().to_representation(instance)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_flex_fields/serializers.py", line 64, in to_representation
    return super().to_representation(instance)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio/data_export/serializers.py", line 39, in get_result
    return extract_key_frames(obj.result)
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio_tools/postprocessing/video.py", line 27, in extract_key_frames
    temp['value']['sequence'].extend(_construct_result_from_frames(frame1=frame_a,
  File "/Users/pxp04/opt/anaconda3/envs/Python39/lib/python3.9/site-packages/label_studio_tools/postprocessing/video.py", line 66, in _construct_result_from_frames
    delta = i / (frame_count - 1)
ZeroDivisionError: division by zero
```

Can you please help and advice in resolving this issue?

**Comment by KonstantinKorotaev** [comment]
Hi @praveenporsche 
Could you please post your annotation that you are trying to export?

**Comment by makseq** [comment]
It's fixed here: https://github.com/heartexlabs/label-studio-tools/pull/42
and will be delivered in upcoming releases.

**Comment by Raven888888** [comment]
@makseq When will this be delivered? We urgently need this feature back, thanks
