### ISSUE TITLE
Not work send POST /api/tasks

### ISSUE THREAD

**Issue by DimIsaev** [heartexlabs/label-studio#3366]
**Describe the bug**

data is not send in the method POST /api/tasks
return error 500

**To Reproduce**
send request  ```POST  /api/tasks```

```
payload  = {
    "data": {
        "annotations": [
            {
                "result": [
                    {
                        "value": {
                            "start": 288,
                            "end": 302,
                            "text": "...",
                            "labels": [
                                "CASE"
                            ]
                        },
                        "from_name": "label",
                        "to_name": "text",
                        "type": "labels",
                        "origin": "manual"
                    }
                ]
            }
        ],
        "predictions": [],
        "data": {
            "text": ".... "
        }
    },
    "project_id": "1"
}

```

```
result = requests.post(
    f'http://{URL_LABEL}/api/tasks',
    headers={'Authorization': f'Token {TOKEN}'},
    json=payload,
)
print(result.json())
```

**Expected behavior**
Added task with label data 

**Errorr response**

```
{'id': '01c13099-5a07-422c-8e01-a362d5765d1b',
 'status_code': 500,
 'version': '1.6.0rc5',
 'detail': "'str' object has no attribute 'get'",
 'exc_info': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper\n    return bound_method(*args, **kwargs)\n  File "/usr/local/lib/python3.10/dist-packages/rest_framework/generics.py", line 242, in post\n    return self.create(request, *args, **kwargs)\n  File "/usr/local/lib/python3.10/dist-packages/rest_framework/mixins.py", line 17, in create\n    serializer = self.get_serializer(data=request.data)\n  File "/usr/local/lib/python3.10/dist-packages/rest_framework/generics.py", line 109, in get_serializer\n    kwargs.setdefault(\'context\', self.get_serializer_context())\n  File "/label-studio/label_studio/tasks/api.py", line 85, in get_serializer_context\n    project_id = self.request.data.get(\'project\')\nAttributeError: \'str\' object has no attribute \'get\'\n'}
```

**Comment by makseq** [comment]
Your payload is incorrect, try to move everything from data outside to the project_id level.
Probably project_id is incorrect too, it should be project as I remember.

**Comment by DimIsaev** [comment]
> Your payload is incorrect, try to move everything from data outside to the project_id level.
> Probably project_id is incorrect too, it should be project as I remember.


```
payload  = {
        "annotations": [
            {
                "result": [
                    {
                        "value": {
                            "start": 288,
                            "end": 302,
                            "text": "...",
                            "labels": [
                                "CASE"
                            ]
                        },
                        "from_name": "label",
                        "to_name": "text",
                        "type": "labels",
                        "origin": "manual"
                    }
                ]
            }
        ],
        "predictions": [],
        "data": {
            "text": ".... "
         },
    "project": "1"
}

```

that's right?

**Comment by makseq** [comment]
Looks better.   "project": "1" =>   "project": 1

**Comment by makseq** [comment]
Hope the last message helped to solve this issue finally.
