### ISSUE TITLE
Bug: AttributeError: 'NoneType' object has no attribute 'allow_postpone'

### ISSUE THREAD

**Issue by filipsedivy** [heartexlabs/label-studio#3492]
**Describe the bug**
I started annotating the image data using bounding boxes. I added labels and started annotating the data. After adding another label during annotation, and then clicking the Label Tasks As Displayed button, an error occurs.

**To Reproduce**
1. Create a new project with the Object Detection with Bounding Boxes template
2. Annotating data
3. Adding more labels
4. In the data report, filtering the data
5. Click Label Tasks As Displayed

**Expected behavior**
Annotation-ready data filtering is displayed

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_manager/api.py", line 333, in post
    result = perform_action(action_id, project, queryset, request.user, **kwargs)
  File "/label-studio/label_studio/data_manager/actions/__init__.py", line 123, in perform_action
    raise e
  File "/label-studio/label_studio/data_manager/actions/__init__.py", line 119, in perform_action
    result = action['entry_point'](project, queryset, **kwargs)
  File "/label-studio/label_studio/data_manager/actions/next_task.py", line 25, in next_task
    next_task, queue_info = get_next_task(request.user, queryset, project, dm_queue)
  File "/label-studio/label_studio/projects/functions/next_task.py", line 254, in get_next_task
    next_task, queue_info = postponed_queue(next_task, prepared_tasks, project, user, queue_info)
  File "/label-studio/label_studio/projects/functions/next_task.py", line 204, in postponed_queue
    next_task.allow_postpone = False
AttributeError: 'NoneType' object has no attribute 'allow_postpone'
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: MacOS / Docker Image
 - Label Studio Version: v1.7.0

**Comment by makseq** [comment]
Thank you for pointing us to this bug. It's fixed here https://github.com/heartexlabs/label-studio/pull/3495 and merged to the develop branch.
