### ISSUE TITLE
Can't start label-studio after upgrade

### ISSUE THREAD

**Issue by hihosilvers** [heartexlabs/label-studio#3563]
**Describe the bug**
Getting `django.db.utils.OperationalError: no such column: project.pinned_at` error after updating from 1.5.0post0 to 1.7.0

Similar to https://github.com/heartexlabs/label-studio/issues/3301 but I would like to keep my sqlite db if possible

**To Reproduce**
1. execute label-studio
2. get error `return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: project.pinned_at`

**Expected behavior**
label-studio starts

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 11
 - Label Studio Version 1.7.0 running in a Python virtual environment

**Additional context**
Attempting to use manage.py migrate also results in the same error.

showmigrations output: 
$ python manage.py showmigrations
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 54959
Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
[2023-01-15 17:34:07,199] [django::register_actions_from_dir::97] [INFO] No module named 'data_manager.actions.__pycache_'
[2023-01-15 17:34:07,199] [django::register_actions_from_dir::97] [INFO] No module named 'data_manager.actions.__pycache_'
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
authtoken
 [X] 0001_initial
 [X] 0002_auto_20160226_1747
 [X] 0003_tokenproxy
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
core
 [X] 0001_initial
data_export
 [X] 0001_initial
 [X] 0002_auto_20210921_0954
 [X] 0003_auto_20211004_1416
 [X] 0004_auto_20211019_0852
 [X] 0005_auto_20211025_1137
data_import
 [X] 0001_initial
 [X] 0002_alter_fileupload_file
data_manager
 [X] 0001_squashed_0005_view_user (5 squashed migrations)
 [X] 0002_remove_annotations_ids
 [X] 0003_remove_predictions_model_versions
 [X] 0004_remove_avg_lead_time
 [X] 0005_remove_updated_by
 [X] 0006_remove_inner_id
 [X] 0007_auto_20220708_0832
 [ ] 0008_manual_counters_update
django_rq
 [X] 0001_initial
io_storages
 [X] 0001_squashed_0002_auto_20210302_1827 (2 squashed migrations)
 [X] 0002_auto_20210311_0530
 [X] 0003_localfilesimportstorage
 [X] 0004_gcsstoragemixin_google_application_credentials
 [X] 0005_s3importstorage_recursive_scan
 [X] 0006_auto_20210906_1323
 [X] 0007_auto_20210928_1252
 [X] 0008_auto_20211129_1132
 [X] 0009_auto_20220310_0922
 [ ] 0010_auto_20221014_1708
labels_manager
 [X] 0001_initial
 [X] 0002_auto_20220131_1325
 [ ] 0003_auto_20230115_1726
ml
 [X] 0001_initial
 [X] 0002_auto_20210308_1559
 [X] 0003_auto_20210309_1239
 [X] 0004_auto_20210820_1610
 [X] 0005_auto_20211010_1344
 [ ] 0006_mlbackend_auto_update
organizations
 [X] 0001_squashed_0008_auto_20201005_1552 (8 squashed migrations)
 [X] 0002_auto_20210310_2044
 [X] 0003_auto_20211010_1339
projects
 [X] 0001_squashed_0065_auto_20210223_2014 (66 squashed migrations)
 [X] 0002_auto_20210304_1457
 [X] 0003_project_color
 [X] 0004_auto_20210306_0506
 [X] 0003_auto_20210305_1008
 [X] 0005_merge_20210308_1141
 [X] 0006_auto_20210308_1559
 [X] 0007_auto_20210309_1304
 [X] 0008_auto_20210314_1840
 [X] 0009_project_evaluate_predictions_automatically
 [X] 0010_auto_20210505_2037
 [X] 0011_auto_20210517_2101
 [X] 0012_auto_20210906_1323
 [X] 0013_project_reveal_preannotations_interactively
 [X] 0014_project_parsed_label_config
 [X] 0013_project_skip_queue
 [X] 0015_merge_20220117_0749
 [X] 0016_auto_20220211_2218
 [ ] 0017_project_pinned_at
 [ ] 0018_alter_project_control_weights
sessions
 [X] 0001_initial
tasks
 [X] 0001_squashed_0041_taskcompletionhistory_was_cancelled (45 squashed migrations)
 [X] 0002_auto_20210305_2035
 [X] 0002_auto_20210304_1423
 [X] 0003_merge_20210308_1141
 [X] 0004_auto_20210308_1559
 [X] 0005_auto_20210309_1239
 [X] 0006_remove_annotation_state
 [X] 0007_auto_20210618_1653
 [X] 0008_auto_20210903_1332
 [X] 0009_auto_20210914_0020
 [X] 0010_auto_20210914_0032
 [X] 0009_auto_20210913_0739
 [X] 0011_merge_20210914_1036
 [X] 0012_auto_20211010_1339
 [X] 0013_task_updated_by
 [X] 0014_task_inner_id
 [X] 0015_task_fill_inner_id
 [X] 0016_auto_20220414_1408
 [X] 0017_auto_20220330_1310
 [X] 0018_manual_migrate_counters
 [X] 0017_new_index_anno_result
 [X] 0019_merge_20220512_2038
 [X] 0020_auto_20220515_2332
 [X] 0021_auto_20220515_2358
 [X] 0020_auto_20220516_0545
 [X] 0022_merge_20220517_1128
 [ ] 0023_auto_20220620_1007
 [ ] 0024_manual_migrate_counters_again
 [ ] 0025_auto_20220721_0110
 [ ] 0026_auto_20220725_1705
 [ ] 0027_auto_20220801_1728
 [ ] 0028_auto_20220802_2220
 [ ] 0029_annotation_project
 [ ] 0030_auto_20221102_1118
 [ ] 0031_alter_task_options
 [ ] 0032_auto_20230115_1726
users
 [X] 0001_squashed_0009_auto_20210219_1237 (9 squashed migrations)
 [X] 0002_auto_20210308_1559
 [X] 0003_user_active_organization
 [X] 0004_auto_20210914_0109
 [X] 0005_auto_20211010_1339
 [X] 0006_user_allow_newsletters
webhooks
 [X] 0001_initial
 [X] 0002_auto_20220319_0013
 [ ] 0003_alter_webhookaction_action

**Comment by makseq** [comment]
Did you use intermediate versions from develop branch of github repo?

**Comment by hihosilvers** [comment]
Hey, no I just used pip install --upgrade

**Comment by makseq** [comment]
Don't you have any logs when migrations were running?

**Comment by vbakhteev** [comment]
Just upgraded to 1.7.0 from 1.5.0 and faced the same issue.

label-studio start
```
=> Database and media directory: /Users/vladbakhteev/Library/Application Support/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /Users/vladbakhteev/Library/Application Support/label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 54959
Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
Initializing database..
Traceback (most recent call last):
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: project.pinned_at

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vladbakhteev/opt/anaconda3/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/label_studio/server.py", line 291, in main
    _apply_database_migrations()
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/label_studio/server.py", line 67, in _apply_database_migrations
    call_command('migrate', '--no-color', verbosity=0)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/label_studio/data_manager/migrations/0008_manual_counters_update.py", line 27, in forwards
    calculate_stats_all_orgs(from_scratch=True, redis=True, migration_name='data_manager-0008_manual_counters_update')
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/label_studio/tasks/functions.py", line 30, in calculate_stats_all_orgs
    start_job_async_or_sync(
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/label_studio/core/redis.py", line 112, in start_job_async_or_sync
    return job(*args, **kwargs)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/label_studio/tasks/functions.py", line 59, in redis_job_for_calculation
    for project in projects:
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/sentry_sdk/integrations/django/__init__.py", line 560, in execute
[2023-01-17 21:18:44,214] [urllib3.connectionpool::_new_conn::1003] [DEBUG] Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
2023-01-17 21:18:44,214 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
    return real_execute(self, sql, params)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/vladbakhteev/opt/anaconda3/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: project.pinned_at
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
[2023-01-17 21:18:44,386] [urllib3.connectionpool::_make_request::456] [DEBUG] https://o227124.ingest.sentry.io:443 "POST /api/5820521/store/ HTTP/1.1" 200 41
2023-01-17 21:18:44,386 - urllib3.connectionpool - DEBUG - https://o227124.ingest.sentry.io:443 "POST /api/5820521/store/ HTTP/1.1" 200 41
```

**Comment by hihosilvers** [comment]
> migrations

Not unless they are logged automatically? I downgraded back to 1.5.0 I can upgrade again and produce logs if you tell me how

**Comment by makseq** [comment]
Yes, it would be very helpful. Migration logs are not recorded automatically.

**Comment by hihosilvers** [comment]
Something like this?
https://stackoverflow.com/a/59076760

So should I set it up then run pip update?

**Comment by quantumdot** [comment]
I'm also seeing this error when upgrading from version `1.1.0` to `1.7.0`. I just ran `pip install -U label-studio` as the instructions suggest.

**Comment by makseq** [comment]
I need your logs at the first start of LS right after upgrade

**Comment by quantumdot** [comment]
@makseq I installed version 1.7.0 via `pip install -U label-studio`. Then I start label-studio via `label-studio start -b --port 80 --data-dir /home/lsuser/label-studio-root/ &`, and the following output is produced:

```
[1] 4167647
(label-studio) lsuser@hginj-labelstudio:~$ => Database and media directory: /home/lsuser/.local/share/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /home/lsuser/label-studio-root
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 54959
Initializing database..
Traceback (most recent call last):
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: project.pinned_at

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lsuser/anaconda3/envs/label-studio/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/server.py", line 291, in main
    _apply_database_migrations()
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/server.py", line 67, in _apply_database_migrations
    call_command('migrate', '--no-color', verbosity=0)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/data_manager/migrations/0008_manual_counters_update.py", line 27, in forwards
    calculate_stats_all_orgs(from_scratch=True, redis=True, migration_name='data_manager-0008_manual_counters_update')
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/tasks/functions.py", line 30, in calculate_stats_all_orgs
    start_job_async_or_sync(
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/core/redis.py", line 112, in start_job_async_or_sync
[2023-01-21 16:41:45,779] [urllib3.connectionpool::_new_conn::971] [DEBUG] Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
2023-01-21 16:41:45,779 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
    return job(*args, **kwargs)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/label_studio/tasks/functions.py", line 59, in redis_job_for_calculation
    for project in projects:
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/lsuser/anaconda3/envs/label-studio/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: project.pinned_at
[2023-01-21 16:41:45,827] [urllib3.connectionpool::_make_request::452] [DEBUG] https://o227124.ingest.sentry.io:443 "POST /api/5820521/store/ HTTP/1.1" 200 41
2023-01-21 16:41:45,827 - urllib3.connectionpool - DEBUG - https://o227124.ingest.sentry.io:443 "POST /api/5820521/store/ HTTP/1.1" 200 41
```

Please let me know if you need some other information and how to find it. Thanks!

**Comment by makseq** [comment]
@teejK @quantumdot could you please check the latest commit from the develop branch? will it migrate correctly? 

```
# Clone repo
git clone https://github.com/heartexlabs/label-studio.git
# Install dependencies
cd label-studio
pip install -e .
# Apply DB migrations
python label_studio/manage.py migrate
# Collect static files
python label_studio/manage.py collectstatic
# Launch
python label_studio/manage.py runserver
```

**Comment by hihosilvers** [comment]
Hey @makseq
Still getting:
`django.db.utils.OperationalError: no such column: project.pinned_at
[2023-01-24 14:30:49,468] [urllib3.connectionpool::_make_request::456] [DEBUG] https://o227124.ingest.sentry.io:443 "POST /api/5820521/store/ HTTP/1.1" 429 198`

At `python label_studio/manage.py migrate`

How do I turn on logging... I can't seem to find the config.yml for Django.

**Comment by makseq** [comment]
@teejK @quantumdot sorry, please try to install `pip install -U label-studio==1.7.1`. Now it must work.

**Comment by makseq** [comment]
Fixes are here:
https://github.com/heartexlabs/label-studio/pull/3606
https://github.com/heartexlabs/label-studio/pull/3585

**Comment by jelalsultanov** [comment]
@teejK I downgraded to 1.15.0 version and it worked for me. Error disappeared.
