### ISSUE TITLE
Hi @KonstantinKorotaev , I did a new test just now and the results are as follows:

### ISSUE THREAD

**Issue by sushant097** [heartexlabs/label-studio#3584]
Hi @KonstantinKorotaev , I did a new test just now and the results are as follows:
On pressing"Start Training" in the project settings I get (on the label studio ml terminal):
```
[2022-02-28 15:15:07,837] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:15:07] "POST /webhook HTTP/1.1" 201 -
[2022-02-28 15:15:07,850] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:15:07] "GET /health HTTP/1.1" 200 -
[2022-02-28 15:15:07,854] [ERROR] [label_studio_ml.model::get_result_from_last_job::128] 1646057677 job returns exception: 
Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 126, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
Transfer learning with a full ConvNet finetuning
[2022-02-28 15:15:08,471] [ERROR] [label_studio_ml.model::get_result::56] 
Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 54, in get_result
    job_result = self.get_result_from_job_id(model_version)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
Transfer learning with a full ConvNet finetuning
[2022-02-28 15:15:09,595] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:15:09] "POST /setup HTTP/1.1" 200 -
Collecting annotations...
Creating dataset with 0 images...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 81, in job
    result = model.process_event(event, data, job_id, additional_params)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 312, in process_event
    train_output = self.fit((), event=event, data=data, job_id=job_id, **additional_params)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/pytorch_backend/pytorch_transfer_learning.py", line 190, in fit
    dataloader = DataLoader(dataset, shuffle=True, batch_size=batch_size)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/env/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

On switching from image to image in the labeling view I get: 
```
[2022-02-28 15:17:44,045] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:17:44] "GET /health HTTP/1.1" 200 -
[2022-02-28 15:17:44,049] [ERROR] [label_studio_ml.model::get_result_from_last_job::128] 1646057707 job returns exception: 
Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 126, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
[2022-02-28 15:17:44,050] [ERROR] [label_studio_ml.model::get_result_from_last_job::128] 1646057677 job returns exception: 
Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 126, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
Transfer learning with a full ConvNet finetuning
[2022-02-28 15:17:45,622] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:17:45] "POST /setup HTTP/1.1" 200 -
[2022-02-28 15:17:45,647] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/api.py", line 32, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 570, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/pytorch_backend/pytorch_transfer_learning.py", line 160, in predict
    logits = self.model.predict(image_urls)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/pytorch_backend/pytorch_transfer_learning.py", line 99, in predict
    return self.model(images).to(device).data.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/api.py", line 32, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 570, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/pytorch_backend/pytorch_transfer_learning.py", line 160, in predict
    logits = self.model.predict(image_urls)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/pytorch_backend/pytorch_transfer_learning.py", line 99, in predict
    return self.model(images).to(device).data.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Use Tensor.cpu() to copy the tensor to host memory first.

[2022-02-28 15:17:45,648] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:17:45] "POST /predict HTTP/1.1" 500 -
```
If I change that line to `return self.model(images).to(device).data.cpu().numpy()` I get a new assertion error:
```
[2022-02-28 15:20:07,247] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:20:07] "GET /health HTTP/1.1" 200 -
[2022-02-28 15:20:07,251] [ERROR] [label_studio_ml.model::get_result_from_last_job::128] 1646057707 job returns exception: 
Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 126, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
[2022-02-28 15:20:07,251] [ERROR] [label_studio_ml.model::get_result_from_last_job::128] 1646057677 job returns exception: 
Traceback (most recent call last):
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 126, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
Transfer learning with a full ConvNet finetuning
[2022-02-28 15:20:08,798] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:20:08] "POST /setup HTTP/1.1" 200 -
[2022-02-28 15:20:08,824] [INFO] [werkzeug::_log::225] 192.168.178.68 - - [28/Feb/2022 15:20:08] "POST /predict HTTP/1.1" 200 -
```
I'm wondering if we may have an issue with library versions somehow? Thank you for tracking this down!

_Originally posted by @greyeagle in https://github.com/heartexlabs/label-studio/issues/2009#issuecomment-1054307932_

**Comment by KonstantinKorotaev** [comment]
Hi @sushant097 
```
 File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
    assert isinstance(result, dict)
AssertionError
```

This assertion error is because of training session ended without results (we added more user friendly error in next version). 

Please check your LS instance for predictions.

**Comment by sushant097** [comment]
> Hi @sushant097
> 
> ```
>  File "/home/lars/Progs/label-studio/label_studio_ml_git/label_studio_ml/model.py", line 108, in get_result_from_job_id
>     assert isinstance(result, dict)
> AssertionError
> ```
> 
> This assertion error is because of training session ended without results (we added more user friendly error in next version).
> 
> Please check your LS instance for predictions.

Okay. Thanks for your response.
