### ISSUE TITLE
Cannot resolve keyword 'cancelled_completions' into field after importing old project

### ISSUE THREAD

**Issue by alanbuxton** [heartexlabs/label-studio#3685]
**Describe the bug**
I ran `run label-studio start <project_name>` on an existing label-studio project created in an older version that used json to store completions rather than sqlite.

After the upgrade completed, I logged into the web UI and when clicking into the project got the following error:

```
[2023-02-12 16:27:14,087] [django.server::log_message::161] [INFO] "GET /api/dm/views?project=1 HTTP/1.1" 200 696
[2023-02-12 16:27:14,134] [core.utils.common::custom_exception_handler::79] [ERROR] cb94578e-6c28-492e-9524-ad072343123b Cannot resolve keyword 'cancelled_completions' into field. Choices are: annotations, cancelled_annotations, comment_authors, comment_count, created_at, data, drafts, file_upload, file_upload_id, id, inner_id, io_storages_azureblobimportstoragelink, io_storages_gcsimportstoragelink, io_storages_localfilesimportstoragelink, io_storages_redisimportstoragelink, io_storages_s3importstoragelink, is_labeled, last_comment_updated_at, locks, meta, overlap, predictions, project, project_id, total_annotations, total_predictions, unresolved_comment_count, updated_at, updated_by, updated_by_id
Traceback (most recent call last):

....

    raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'cancelled_completions' into field. Choices are: annotations, cancelled_annotations, comment_authors, comment_count, created_at, data, drafts, file_upload, file_upload_id, id, inner_id, io_storages_azureblobimportstoragelink, io_storages_gcsimportstoragelink, io_storages_localfilesimportstoragelink, io_storages_redisimportstoragelink, io_storages_s3importstoragelink, is_labeled, last_comment_updated_at, locks, meta, overlap, predictions, project, project_id, total_annotations, total_predictions, unresolved_comment_count, updated_at, updated_by, updated_by_id
[2023-02-12 16:27:14,172] [django.request::log_response::224] [ERROR] Internal Server Error: /api/tasks/
[2023-02-12 16:27:14,172] [django.request::log_response::224] [ERROR] Internal Server Error: /api/tasks/
[2023-02-12 16:27:14,174] [django.server::log_message::161] [ERROR] "GET /api/tasks?page=1&page_size=30&view=1&project=1 HTTP/1.1" 500 5068
[2023-02-12 16:27:14,174] [django.server::log_message::161] [ERROR] "GET /api/tasks?page=1&page_size=30&view=1&project=1 HTTP/1.1" 500 5068
```

**To Reproduce**
1. Run `run label-studio start <project_name>` on an old label studio project with json completion files rather than sqlite
2. Watch it upgrade the project
3. Open the web UI
4. Click into the project
5. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac OSX
 - Label Studio Version: 1.7.1

**Additional context**
I have some other projects that were upgraded from json-based to sqlite-based storage in a previous version of label-studio. Those are not experiencing this issue. This issue only applies to a project that I have tried to upgrade using 1.6 or 1.7 of label-studio

**Comment by makseq** [comment]
Please provide logs with the migration from old project. 
As a workaround you can try to make an upgrade using LS 1.5 and then switch to 1.7.

**Comment by alanbuxton** [comment]
The 1.7 logs didn't give much away - see below:

```
label_studio_projects git:(main) ✗ label-studio start test-upgrade -db test-upgrade/test-upgrade.sqlite3 --data-dir test-upgrade --username foo@example.com --password test
=> Database and media directory: /path/to/user/Library/Application Support/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /path/to/user/lsproject/label_studio_projects/test-upgrade
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 55841
Initializing database..
Project directory from previous verion of label-studio found
Start migrating..
Token None is not applied to user default_user@localhost because it's empty or len(token) < 5
Project with title "test-upgrade" successfully created

*** WARNING! ***
Project test-upgrade migrated to Label Studio Database
YOU DON'T NEED THIS FOLDER ANYMORE
****************

User foo@example.com already exists
Performing system checks...

[2023-02-17 22:24:13,932] [django::register_actions_from_dir::97] [INFO] No module named 'data_manager.actions.__pycache_'
[2023-02-17 22:24:13,932] [django::register_actions_from_dir::97] [INFO] No module named 'data_manager.actions.__pycache_'
System check identified no issues (1 silenced).
February 17, 2023 - 22:24:14
Django version 3.2.16, using settings 'label_studio.core.settings.label_studio'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
```

I tried with 1.5 and I got the same error. I have 2 or 3 other projects from an older label studio that upgraded fine. I am now wondering if there is some issue in the data for this particular project that is causing the upgrade problems. See below logs with 1.5 including logging in and seeing the error happen.

```
label_studio_projects git:(main) ✗ label-studio start test-product -db test-product/test-product.sqlite3 --data-dir test-product --username foo@example.com --password test
=> Database and media directory: /path/to/label_studio_projects/test-product
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 55841

  ╔═════════════════════════════════════╗
  ║                                     ║
  ║   Update available 1.5.0 → 1.7.1    ║
  ║   Run pip install -U label-studio   ║
  ║                                     ║
  ╚═════════════════════════════════════╝

Initializing database..
2023-02-17 23:05:04,152 - root - INFO - All organizations were recalculated.
2023-02-17 23:05:04,189 - tasks.migrations.0017_new_index_anno_result - INFO - Database vendor: sqlite
2023-02-17 23:05:04,189 - tasks.migrations.0017_new_index_anno_result - INFO - Skipping migration without attempting to CREATE INDEX
Project directory from previous verion of label-studio found
Start migrating..
Token None is not applied to user default_user@localhost because it's empty or len(token) < 5
2023-02-17 23:05:05,315 - organizations.models - DEBUG - User already exists in organization.
Project with title "test-product" successfully created
2023-02-17 23:05:05,344 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,352 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 1, 'classif': 1, 'text': 1}
2023-02-17 23:05:05,352 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,358 - tasks.models - DEBUG - Increase project.summary counters from Annotation object (1)
2023-02-17 23:05:05,359 - projects.models - DEBUG - summary.created_annotations = {'label|text|labels': 10}
2023-02-17 23:05:05,359 - projects.models - DEBUG - summary.created_labels = {'label': {'Benefit': 1}}
2023-02-17 23:05:05,361 - tasks.models - DEBUG - Update task stats for task=Task object (1)
2023-02-17 23:05:05,364 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,368 - projects.models - DEBUG - summary.all_data_columns = {}
2023-02-17 23:05:05,368 - projects.models - DEBUG - summary.common_data_columns = []
2023-02-17 23:05:05,372 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 2, 'classif': 2, 'text': 2}
2023-02-17 23:05:05,372 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,374 - tasks.models - DEBUG - Updated total_annotations and cancelled_annotations for 1.
2023-02-17 23:05:05,376 - tasks.models - DEBUG - 0 drafts removed from task Task object (1) after saving annotation Annotation object (1)
2023-02-17 23:05:05,382 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,386 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 1, 'classif': 1, 'text': 1}
2023-02-17 23:05:05,386 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,390 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 3, 'classif': 3, 'text': 3}
2023-02-17 23:05:05,390 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,393 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,397 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 4, 'classif': 4, 'text': 4}
2023-02-17 23:05:05,398 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,404 - tasks.models - DEBUG - Increase project.summary counters from Annotation object (2)
2023-02-17 23:05:05,404 - projects.models - DEBUG - summary.created_annotations = {'label|text|labels': 15}
2023-02-17 23:05:05,404 - projects.models - DEBUG - summary.created_labels = {'label': {'Benefit': 1, 'ProductTopic': 1, 'ProductOrg': 1, 'RelatedOrg': 1, 'What': 1, 'Feature': 1}}
2023-02-17 23:05:05,406 - tasks.models - DEBUG - Update task stats for task=Task object (2)
2023-02-17 23:05:05,410 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,413 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 3, 'classif': 3, 'text': 3}
2023-02-17 23:05:05,413 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,418 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 5, 'classif': 5, 'text': 5}
2023-02-17 23:05:05,418 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,420 - tasks.models - DEBUG - Updated total_annotations and cancelled_annotations for 2.
2023-02-17 23:05:05,422 - tasks.models - DEBUG - 0 drafts removed from task Task object (2) after saving annotation Annotation object (2)
2023-02-17 23:05:05,427 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,430 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 4, 'classif': 4, 'text': 4}
2023-02-17 23:05:05,430 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,434 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 6, 'classif': 6, 'text': 6}
2023-02-17 23:05:05,434 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,437 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
2023-02-17 23:05:05,442 - projects.models - DEBUG - summary.all_data_columns = {'art_id': 7, 'classif': 7, 'text': 7}
2023-02-17 23:05:05,442 - projects.models - DEBUG - summary.common_data_columns = ['art_id', 'classif', 'text']
2023-02-17 23:05:05,446 - core.feature_flags.base - DEBUG - Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': '', 'email': 'foo@example.com', 'last_activity': '2023-02-17T23:05:05.225665Z', 'avatar': None, 'initials': 'fo', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'foo@example.com', 'custom': {'organization': 'foo@example.com'}}
```

.... many similar lines removed, then

```
*** WARNING! ***
Project test-product migrated to Label Studio Database
YOU DON'T NEED THIS FOLDER ANYMORE
****************

User foo@example.com already exists
2023-02-17 23:05:08,067 - organizations.models - DEBUG - User already exists in organization.
2023-02-17 23:05:08,069 - label_studio.server - INFO - Checking if host & port is available :: localhost:8080
2023-02-17 23:05:08,072 - label_studio.core.utils.common - INFO - Start browser at URL: http://localhost:8080
Performing system checks...

2023-02-17 23:05:08,283 - django - INFO - No module named 'data_manager.actions.__pycache_'
System check identified no issues (1 silenced).
February 17, 2023 - 23:05:08
Django version 3.1.14, using settings 'label_studio.core.settings.label_studio'
Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
[17/Feb/2023 23:05:11] "GET / HTTP/1.1" 302 0
[17/Feb/2023 23:05:11] "GET /user/login/ HTTP/1.1" 200 2006
[17/Feb/2023 23:05:11] "GET /static/css/login.b79a5e51b1bf.css HTTP/1.1" 200 2319
[17/Feb/2023 23:05:11] "GET /static/css/main.de66392810e2.css HTTP/1.1" 200 15353
[17/Feb/2023 23:05:11] "GET /react-app/main.css?v=be324a HTTP/1.1" 200 68921
[17/Feb/2023 23:05:11] "GET /static/images/opossum_hanging.2fa77848bd0c.svg HTTP/1.1" 200 131567
[17/Feb/2023 23:05:11] "GET /static/images/favicon.58c0a5114450.ico HTTP/1.1" 200 21822
[17/Feb/2023 23:05:29] "POST /user/login/?next=/projects/ HTTP/1.1" 302 0
[17/Feb/2023 23:05:29] "GET /projects/ HTTP/1.1" 200 9915
[17/Feb/2023 23:05:29] "GET /static/fonts/roboto/roboto.css HTTP/1.1" 200 3431
[17/Feb/2023 23:05:29] "GET /static/js/helpers.9a01b074ff58.js HTTP/1.1" 200 13336
[17/Feb/2023 23:05:29] "GET /static/css/uikit.e49a7a43adbd.css HTTP/1.1" 200 3892
[17/Feb/2023 23:05:29] "GET /static/js/jquery.min.220afd743d9e.js HTTP/1.1" 200 88145
[17/Feb/2023 23:05:29] "GET /react-app/index.js?v=be324a HTTP/1.1" 200 790575
[17/Feb/2023 23:05:30] "GET /static/fonts/roboto/roboto-v20-latin_cyrillic-regular.woff2 HTTP/1.1" 200 22428
[17/Feb/2023 23:05:30] "GET /static/icons/logo-black.svg HTTP/1.1" 200 10236
[17/Feb/2023 23:05:30] "GET /api/version HTTP/1.1" 200 1010
[17/Feb/2023 23:05:30] "GET /static/fonts/roboto/roboto-v20-latin_cyrillic-500.woff2 HTTP/1.1" 200 22880
[17/Feb/2023 23:05:30] "GET /api/projects?page=1&page_size=30 HTTP/1.1" 200 3281
[17/Feb/2023 23:05:30] "GET /projects/ HTTP/1.1" 200 9915
[17/Feb/2023 23:05:30] "GET /static/images/favicon.58c0a5114450.ico HTTP/1.1" 200 21822
[17/Feb/2023 23:05:32] "GET /dm/css/main.css?v=fef237 HTTP/1.1" 200 65862
[17/Feb/2023 23:05:32] "GET /label-studio-frontend/css/main.css?v=1bdc91 HTTP/1.1" 200 639975
[17/Feb/2023 23:05:32] "GET /dm/js/main.js?v=fef237 HTTP/1.1" 200 1386044
[17/Feb/2023 23:05:32] "GET /api/projects/1 HTTP/1.1" 200 3229
[17/Feb/2023 23:05:32] "GET /label-studio-frontend/js/main.js?v=1bdc91 HTTP/1.1" 200 2417934
[17/Feb/2023 23:05:32] "GET /api/ml?project=1 HTTP/1.1" 200 2
[17/Feb/2023 23:05:33] "GET /api/dm/columns?project=1 HTTP/1.1" 200 3673
[17/Feb/2023 23:05:33] "GET /api/users?project=1 HTTP/1.1" 200 217
[17/Feb/2023 23:05:33] "GET /api/dm/project?project=1 HTTP/1.1" 200 3410
[17/Feb/2023 23:05:33] "GET /api/dm/actions?project=1 HTTP/1.1" 200 1537
[17/Feb/2023 23:05:33] "GET /api/dm/views?project=1 HTTP/1.1" 200 696
[2023-02-17 23:05:33,159] [core.utils.common::custom_exception_handler::82] [ERROR] ff7efcda-be03-4917-9d32-83af19d523a4 Cannot resolve keyword 'cancelled_completions' into field. Choices are: annotations, cancelled_annotations, created_at, data, drafts, file_upload, file_upload_id, id, inner_id, io_storages_azureblobimportstoragelink, io_storages_gcsimportstoragelink, io_storages_localfilesimportstoragelink, io_storages_redisimportstoragelink, io_storages_s3importstoragelink, is_labeled, locks, meta, overlap, predictions, project, project_id, total_annotations, total_predictions, updated_at, updated_by, updated_by_id
Traceback (most recent call last):
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1865, in add_fields
   join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1567, in setup_joins
   path, final_field, targets, rest = self.names_to_path(
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1483, in names_to_path
   raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'cancelled_completions' into field. Choices are: annotations, cancelled_annotations, created_at, data, drafts, file_upload, file_upload_id, id, inner_id, io_storages_azureblobimportstoragelink, io_storages_gcsimportstoragelink, io_storages_localfilesimportstoragelink, io_storages_redisimportstoragelink, io_storages_s3importstoragelink, is_labeled, locks, meta, overlap, predictions, project, project_id, total_annotations, total_predictions, updated_at, updated_by, updated_by_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/path/to/virtualenv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
   response = handler(request, *args, **kwargs)
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
   return bound_method(*args, **kwargs)
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
   return bound_method(*args, **kwargs)
 File "/path/to/virtualenv/lib/python3.9/site-packages/label_studio/data_manager/api.py", line 206, in get
   queryset = self.get_task_queryset(request, prepare_params)
 File "/path/to/virtualenv/lib/python3.9/site-packages/label_studio/data_manager/api.py", line 177, in get_task_queryset
   return Task.prepared.only_filtered(prepare_params=prepare_params)
 File "/path/to/virtualenv/lib/python3.9/site-packages/label_studio/data_manager/managers.py", line 611, in only_filtered
   return queryset.prepared(prepare_params=prepare_params)
 File "/path/to/virtualenv/lib/python3.9/site-packages/label_studio/data_manager/managers.py", line 451, in prepared
   queryset = apply_filters(queryset, prepare_params.filters, project)
 File "/path/to/virtualenv/lib/python3.9/site-packages/label_studio/data_manager/managers.py", line 326, in apply_filters
   value_type = type(queryset.values_list(field_name, flat=True)[0]).__name__
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/query.py", line 868, in values_list
   clone = self._values(*_fields, **expressions)
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/query.py", line 836, in _values
   clone.query.set_values(fields)
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 2176, in set_values
   self.add_fields(field_names, True)
 File "/path/to/virtualenv/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1887, in add_fields
   raise FieldError("Cannot resolve keyword %r into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'cancelled_completions' into field. Choices are: annotations, cancelled_annotations, created_at, data, drafts, file_upload, file_upload_id, id, inner_id, io_storages_azureblobimportstoragelink, io_storages_gcsimportstoragelink, io_storages_localfilesimportstoragelink, io_storages_redisimportstoragelink, io_storages_s3importstoragelink, is_labeled, locks, meta, overlap, predictions, project, project_id, total_annotations, total_predictions, updated_at, updated_by, updated_by_id
[2023-02-17 23:05:33,184] [django.request::log_response::224] [ERROR] Internal Server Error: /api/tasks/
[17/Feb/2023 23:05:33] "GET /api/tasks?page=1&page_size=30&view=1&project=1 HTTP/1.1" 500 4996
```

**Comment by makseq** [comment]
@alanbuxton Go to project settings => danger zone and reset the data manager tabs:

![image](https://user-images.githubusercontent.com/501780/219993079-e775fa8f-0529-4572-bb4d-d531e6ebd50d.png)

**Comment by alanbuxton** [comment]
Perfect thanks, all works now
