### ISSUE TITLE
Export to yolo fails with 'OSError: [Errno 22] Invalid argument'

### ISSUE THREAD

**Issue by louismustill** [heartexlabs/label-studio#3758]
**Describe the bug**
I have an annoted image set of 473 tasks, all completed.
i want to export in the Yolo format but label-studio gets stuck and throws the following error in the console.

```
[2023-03-01 18:01:39,555] [label_studio_converter.converter::convert_to_yolo::643] [WARNING] No completions found for item #36
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 184, in finish_response
    self.write(data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 293, in write
    self._write(data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/wsgiref/handlers.py", line 467, in _write
    result = self.stdout.write(data)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socketserver.py", line 826, in write
    self._sock.sendall(b)
OSError: [Errno 22] Invalid argument
```

**To Reproduce**
1. Export all items
2. choose the Yolo option
3. Click export, browser sits there and looks like its exporting
4. Error above appears in console

**Expected behavior**

should trigger the zip download

**Environment (please complete the following information):**
 - OS: Mac OS 12.5.1
 - Label Studio Version [e.g. 0.8.0]: 1.7.1

**Additional context**
JSON file attached showing the dataset
[project-3-at-2023-03-01-17-30-e9df08a0.json.zip](https://github.com/heartexlabs/label-studio/files/10864231/project-3-at-2023-03-01-17-30-e9df08a0.json.zip)

Only other thing to flag is some of the images are very large fle sizes, 10-15MB each, could that be the issue?  If so can i just resize them and swap them out in the data store so i dont have to re-label everything?

**Comment by louismustill** [comment]
Woth noting that i had managed to export to Yolo format from a smaller dataset on the same machine a few months ago.

**Comment by makseq** [comment]
@louismustill Try to export this way in the terminal:
https://labelstud.io/guide/export.html#Export-using-console-command

**Comment by kabilanmohanraj** [comment]
I had the same issue with exporting to COCO format. Exporting from the terminal worked for me! Thanks @makseq!
