### ISSUE TITLE
millisecond timeseries data

### ISSUE THREAD

**Issue by jdevoo** [heartexlabs/label-studio#3791]
**Describe the bug**
The dashboard balls keep spinning when I try to display the timeseries data in the dashboard for an annotation task.

**To Reproduce**
Using the following template
```
<View>
  <TimeSeriesLabels name="label" toName="TS">
    <Label value="normal" background="green"/>
    <Label value="anomaly" background="yellow"/>
  </TimeSeriesLabels>
  <TimeSeries name="TS" timeColumn="Datetime" timeFormat="%Y-%m-%d %H:%M:%S.%L" value="$csv" valueType="url">
    <Channel column="IO.TooTemperature"/>
    <Channel column="VibrationValue"/>
    <Channel column="IO.FilterPressure"/>
  </TimeSeries>
</View>
```
load the following data which *varies by increments of 10 milliseconds* only...
```
Datetime,IO.ToolTemperature,VibrationValue,IO.FilterPressure
2019-09-25 14:05:30.245,8360,1,13840
2019-09-25 14:05:30.255,8360,1,13840
2019-09-25 14:05:30.265,8360,1,13840
2019-09-25 14:05:30.275,8360,1,13840
2019-09-25 14:05:30.285,8360,1,13840
2019-09-25 14:05:30.295,8360,1,13840
2019-09-25 14:05:30.305,8360,1,13840
2019-09-25 14:05:30.315,8360,1,13840
2019-09-25 14:05:30.325,8360,1,13840
2019-09-25 14:05:30.335,8360,1,13840
2019-09-25 14:05:30.345,8360,1,13840
2019-09-25 14:05:30.355,8360,1,13840
2019-09-25 14:05:30.365,8360,1,13840
2019-09-25 14:05:30.375,8360,1,13840
2019-09-25 14:05:30.385,8360,1,13840
2019-09-25 14:05:30.395,8360,1,13840
2019-09-25 14:05:30.405,8360,1,13840
2019-09-25 14:05:30.415,8360,1,13840
2019-09-25 14:05:30.425,8360,1,13840
2019-09-25 14:05:30.435,8360,1,13840
2019-09-25 14:05:30.445,8360,1,13840
2019-09-25 14:05:30.455,8360,1,13840
2019-09-25 14:05:30.465,8360,1,13840
2019-09-25 14:05:30.475,8360,1,13840
2019-09-25 14:05:30.485,8360,1,13840
2019-09-25 14:05:30.495,8360,1,13840
2019-09-25 14:05:30.505,8360,1,13840
2019-09-25 14:05:30.515,8360,1,13840
2019-09-25 14:05:30.525,8360,1,13840
2019-09-25 14:05:30.535,8360,1,13840
2019-09-25 14:05:30.545,8360,1,13840
2019-09-25 14:05:30.555,8360,1,13840
2019-09-25 14:05:30.565,8360,1,13840
2019-09-25 14:05:30.575,8360,1,13840
2019-09-25 14:05:30.585,8360,1,13840
2019-09-25 14:05:30.595,8360,1,13840
2019-09-25 14:05:30.605,8360,1,13840
2019-09-25 14:05:30.615,8360,1,13840
2019-09-25 14:05:30.625,8360,1,13840
2019-09-25 14:05:30.635,8360,1,13840
2019-09-25 14:05:30.645,8360,1,13840
2019-09-25 14:05:30.655,8360,1,13840
2019-09-25 14:05:30.665,8360,1,13840
2019-09-25 14:05:30.675,8360,1,13840
2019-09-25 14:05:30.685,8360,1,13840
2019-09-25 14:05:30.695,8360,1,13840
2019-09-25 14:05:30.705,8360,1,13840
2019-09-25 14:05:30.715,8360,1,13840
2019-09-25 14:05:30.725,8360,1,13840
2019-09-25 14:05:30.735,8360,1,13840
2019-09-25 14:05:30.745,8360,1,13840
2019-09-25 14:05:30.755,8360,1,13840
2019-09-25 14:05:30.765,8360,1,13840
2019-09-25 14:05:30.775,8360,1,13840
2019-09-25 14:05:30.785,8360,1,13840
2019-09-25 14:05:30.795,8360,1,13840
2019-09-25 14:05:30.805,8360,1,13840
2019-09-25 14:05:30.815,8360,1,13840
2019-09-25 14:05:30.825,8360,1,13840
2019-09-25 14:05:30.835,8360,1,13840
2019-09-25 14:05:30.845,8360,1,13840
2019-09-25 14:05:30.855,8360,1,13840
2019-09-25 14:05:30.865,8360,1,13840
2019-09-25 14:05:30.875,8360,1,13840
2019-09-25 14:05:30.885,8360,1,13840
2019-09-25 14:05:30.895,8360,1,13840
2019-09-25 14:05:30.905,8360,1,13840
2019-09-25 14:05:30.915,8360,1,13840
```
Load the task defined as follows (in my case sync'ed from local minio)
```
{
	"data": {
		"csv": "http://127.0.0.1:9000/datasets/TaskData.csv?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=7HAWS7RESPAWIGPQ5UCS%2F20230228%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230228T172253Z&X-Amz-Expires=604800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI3SEFXUzdSRVNQQVdJR1BRNVVDUyIsImV4cCI6MTY3NzYwNjE5NSwicGFyZW50IjoibWluaW8ifQ.ErhPw_XYXcYLg8bvcSY4JXFYRbnyWyF3y7rFOgEgw27WGH9F5ZHTxVhUuQJomgLm0V463wusfXKqmLNRwg4Hsw&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=e69448781dddd51f94b0a9595c683f12bfa1cc63e7277a729b6ffe9ec30ad61c"
	}
}
```
Go to annotation task but nothing shows. Balls spinning on grey background.
See browser JS console output below:
```
instrument.js:109 Array(17)
instrument.js:109 Array(17)
attr.js:31 Error: <path> attribute d: Expected number, "M0,NaNL0.0603036182…".
(anonymous) @ attr.js:31
instrument.js:109 TypeError: Cannot read properties of undefined (reading '1')
    at Eq.setRangeWithScaling (Channel.js:739:17)
    at Eq.componentDidMount (Channel.js:690:10)
    at ml (react-dom.production.min.js:219:411)
    at Rs (react-dom.production.min.js:259:160)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at qo (react-dom.production.min.js:122:325)
    at Ns (react-dom.production.min.js:252:279)
    at bs (react-dom.production.min.js:243:371)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at qo (react-dom.production.min.js:122:325)
    at Yo (react-dom.production.min.js:123:61)
    at $o (react-dom.production.min.js:122:428)
    at ws (react-dom.production.min.js:244:190)
    at tt (mobx.module.js:1919:47)
    at nt (mobx.module.js:1895:5)
    at Ye (mobx.module.js:1595:9)
    at mobx.module.js:981:5
    at Ne (mobx.module.js:935:9)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at hr (mobx-state-tree.module.js:2456:16)
    at Object.r (mobx-state-tree.module.js:2483:16)
    at Object.preloadValue (TimeSeries.js:509:14)
    at async Object.updateValue (TimeSeries.js:521:19)
(anonymous) @ instrument.js:109
```

**Expected behavior**
I would expect to see three timeseries as per markup within a reasonable time.
The complete dataset is 1.5M rows.

**Environment (please complete the following information):**
 - Chrome 110.0.5481.178
 - partial docker-compose below
```
  #
  # heartex annotation tool
  #
  # add environment variable for local filesystem support
  #   - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
  #
  label-studio:
    image: heartexlabs/label-studio:1.7.1
    container_name: label-studio
    environment:
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
      - DJANGO_DB=default
      #- LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/data
      - POSTGRE_NAME=${PGSQL_LS_DATABASE}
      - POSTGRE_USER=${PGSQL_LS_USER}
      - POSTGRE_PASSWORD=${PGSQL_LS_PASSWORD}
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=label-db
      - REDIS_LOCATION=label-cache:6379
    command: label-studio --username "${LABEL_STUDIO_USER_EMAIL}" --password "${LABEL_STUDIO_USER_PASSWORD}" --database postgres
    #volumes:
    #  - heartex_data:/label-studio/data
    ports:
      - 8080:8080
    depends_on:
      - nginx
      - label-cache
      - label-db

  label-db:
    image: postgres:13.3-alpine
    container_name: label-db
    environment:
      - POSTGRES_USER=${PGSQL_LS_USER}
      - POSTGRES_PASSWORD=${PGSQL_LS_PASSWORD}
      - POSTGRES_DB=${PGSQL_LS_DATABASE}
      - PGDATA=/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      timeout: 10s
      retries: 3
    volumes:
      - heartex_db:/var/lib/postgresql/data

  label-cache:
    image: redis:6.2.2-alpine
    container_name: label-cache
    volumes:
      - heartex_cache:/data
```

**Additional context**
* Tried with additional nanoseconds on the data and template with `%H:%M:%S.%f` without success
* This earlier [issue 1675](https://github.com/heartexlabs/label-studio/issues/1675) was closed and seems to show same millisecond timestamps are not an issue

**Comment by bmartel** [comment]
Hey @jdevoo 👋. I will take a look into this issue you are seeing, and report back to you what I find. If there are still issues identified I will have a ticket generated for a fix.

**Comment by bmartel** [comment]
I believe I found the issue, it looks like there was a typo in the column name within the config versus what was in the csv data.

```diff
<View>
  <TimeSeriesLabels name="label" toName="TS">
    <Label value="normal" background="green"/>
    <Label value="anomaly" background="yellow"/>
  </TimeSeriesLabels>
  <TimeSeries name="TS" timeColumn="Datetime" timeFormat="%Y-%m-%d %H:%M:%S.%L" value="$csv" valueType="url">
-   <Channel column="IO.TooTemperature"/>
+   <Channel column="IO.ToolTemperature"/>
    <Channel column="VibrationValue"/>
    <Channel column="IO.FilterPressure"/>
  </TimeSeries>
</View>
```

Upon changing that, it loaded up the data without error. I checked the parsing of the timeFormat specified and it did correctly parse the times to numeric unix timestamps including the millisecond precision.

Let me know if there are any other issues observed, but if not we can probably close this ticket.

**Comment by jdevoo** [comment]
thank you @bmartel 😳

**Comment by bmartel** [comment]
> thank you @bmartel 😳

Glad I could help out 👍
