### ISSUE TITLE
Label Studio setup error 

### ISSUE THREAD

**Issue by WeemaUnseen** [heartexlabs/label-studio#3997]
Hey guys 

I am trying to install label studio with cmd in win10 x64 however there is an error shown in the below ;

```
COLLECT_GCC=C:\MinGW\bin\gfortran.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gfortran.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\system_info.py:1858: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  return getattr(self, '_calc_info_{}'.format(name))()
C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\system_info.py:1858: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  return getattr(self, '_calc_info_{}'.format(name))()
Warning: attempted relative import with no known parent package
C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
  warnings.warn(msg)
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gfortran.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
Using built-in specs.
COLLECT_GCC=C:\MinGW\bin\gfortran.exe
COLLECT_LTO_WRAPPER=c:/mingw/bin/../libexec/gcc/mingw32/6.3.0/lto-wrapper.exe
Target: mingw32
Configured with: ../src/gcc-6.3.0/configure --build=x86_64-pc-linux-gnu --host=mingw32 --with-gmp=/mingw --with-mpfr=/mingw --with-mpc=/mingw --with-isl=/mingw --prefix=/mingw --disable-win32-registry --target=mingw32 --with-arch=i586 --enable-languages=c,c++,objc,obj-c++,fortran,ada --with-pkgversion='MinGW.org GCC-6.3.0-1' --enable-static --enable-shared --enable-threads --with-dwarf2 --disable-sjlj-exceptions --enable-version-specific-runtime-libs --with-libiconv-prefix=/mingw --with-libintl-prefix=/mingw --enable-libstdcxx-debug --with-tune=generic --enable-libgomp --disable-libvtv --enable-nls
Thread model: win32
gcc version 6.3.0 (MinGW.org GCC-6.3.0-1)
C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py:535: UserWarning: Fallback spawn triggered. Please update distutils monkeypatch.
  warnings.warn("Fallback spawn triggered. Please update distutils monkeypatch.")
BUILD_ARCHITECTURE: 'AMD64', os.name='nt', sys.platform='win32'
non-existing path in 'numpy\\core': 'build\\src.win-amd64-3.11\\numpy\\core\\src\\common'
### Warning:  Using unoptimized lapack ###
### Warning:  Using unoptimized lapack ###
C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\egg_info.py:661: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
  warnings.warn(
warning: no previously-included files found matching 'LICENSES_bundled.txt'
warning: no previously-included files found matching 'azure-*.yml'
no previously-included directories found matching 'doc\build'
no previously-included directories found matching 'doc\source\generated'
no previously-included directories found matching 'benchmarks\env'
no previously-included directories found matching 'benchmarks\results'
no previously-included directories found matching 'benchmarks\html'
no previously-included directories found matching 'benchmarks\numpy'
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
CCompilerOpt.__init__[1159] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
CCompilerOpt.__init__[1159] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\setup.py", line 448, in <module>
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\setup.py", line 440, in setup_package
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\core.py", line 169, in setup
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
    self.run_command('build_clib')
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\command\build_clib.py", line 135, in run
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 2569, in new_ccompiler_opt
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 2137, in __init__
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1704, in __init__
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1209, in feature_names
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1508, in feature_is_supported
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1464, in feature_test
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1440, in feature_flags
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1015, in cc_test_flags
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 576, in dist_test
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 558, in dist_compile
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 419, in compile
    self.spawn(args)
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 685, in _dist_test_spawn_paths
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 701, in _dist_test_spawn
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1194, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 13: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\Desktop\label-studio-develop\label-studio-develop\setup.py", line 22, in <module>
    setuptools.setup(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 420, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 662, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 709, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 754, in process_distribution
    distros = WorkingSet([]).resolve(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 827, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 863, in _resolve_dist
    dist = best[req.key] = env.best_match(
                           ^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1133, in best_match
    return self.obtain(req, installer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\pkg_resources\__init__.py", line 1145, in obtain
    return installer(requirement)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 707, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 900, in install_eggs
    return self.build_and_install(setup_script, setup_base)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 1174, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\easy_install.py", line 1158, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 190, in setup_context
    with save_modules():
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\setup.py", line 448, in <module>
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\setup.py", line 440, in setup_package
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\core.py", line 169, in setup
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
    self.run_command('build_clib')
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\command\build_clib.py", line 135, in run
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 2569, in new_ccompiler_opt
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 2137, in __init__
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1704, in __init__
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1209, in feature_names
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1508, in feature_is_supported
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1464, in feature_test
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1440, in feature_flags
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 853, in cache_wrap_me
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 1015, in cc_test_flags
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 576, in dist_test
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 558, in dist_compile
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 419, in compile
    self.spawn(args)
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 685, in _dist_test_spawn_paths
  File "C:\Users\PC\AppData\Local\Temp\easy_install-2avns08b\numpy-1.21.6\numpy\distutils\ccompiler_opt.py", line 701, in _dist_test_spawn
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1194, in communicate
    stdout = self.stdout.read()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 13: character maps to <undefined>
Running from numpy source directory.
```

Can someone help me please about that 

PC specs ;

x64 win10

Thanks for now

**Comment by makseq** [comment]
Why do you use mingw instead of direct windows install of LS?

**Comment by WeemaUnseen** [comment]
I've used the code as it wrote it down on the instruction , thats why I do not understand what do you mean

**Comment by makseq** [comment]
I recommend you to use Anaconda, it already has pre-built binaries: 
https://labelstud.io/guide/install.html#Install-with-Anaconda

**Comment by WeemaUnseen** [comment]
oh , k I'll try it and let  u know , thanks

**Comment by pedoc** [comment]
> I recommend you to use Anaconda, it already has pre-built binaries:

Yes, I also had this problem when I tried to install with default python version on win11, but installed successfully with conda.

Of course, I had problems with not being able to load the sqlite3.dll file, which required some tweaking and hack

1. Download sqlite from https://www.sqlite.org/download.html and extract it to the ``DLLs`` directory of the virtual environment
2. Modify ``label_studio\core\utils\windows_sqlite_fix\_init_.py``,[repo url](https://github.com/heartexlabs/label-studio/blob/9d0e109691b3d048e4f1baf9a9567286f945d948/label_studio/core/utils/windows_sqlite_fix/__init__.py),Make it possible to load ``sqlite3.dll`` from the ``DLLs`` directory
```python
# set env
    import ctypes
    path_to_dll = os.path.abspath('.')
    raw_path = os.environ['PATH']
    os.environ['PATH'] = path_to_dll + os.pathsep + raw_path
    try:
        ctypes.CDLL(os.path.join(path_to_dll, 'sqlite3.dll'))
        print('Add current directory to PATH for DLL search: ' + path_to_dll)
    except OSError:
        try:
            print("Can't load sqlite3.dll from current directory,try to load from python DLLs directory")
            python_dir = os.path.dirname(sys.executable)
            path_to_dll = os.path.join(python_dir, 'DLLs')
            os.environ['PATH'] = path_to_dll + os.pathsep + raw_path
            ctypes.CDLL('sqlite3.dll')
            print('Add python DLLs path to PATH for DLL search: ' + path_to_dll)
        except OSError:
            print("Can't load sqlite3.dll")
```
3.If the ``ImportError: DLL load failed while importing _psycopg`` error still occurs,
Execute the following command to reinstall psyconpg2
```bash
python -m pip uninstall psycopg2
python -m pip install psycopg2
```
4.now,it's working

**Comment by hogepodge** [comment]
We've updated Label Studio dependency management in the 1.10.0 release, which should resolve a number of dependency issues. Thanks for your feedback, and I apologize for the delay in responding here.
