### ISSUE TITLE
`label-studio` ends with error 

### ISSUE THREAD

**Issue by hemangjoshi37a** [heartexlabs/label-studio#4042]
Command I ran : `label-studio`

Error I got :
```python
=> Database and media directory: /home/hemang/.local/share/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /home/hemang/.local/share/label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 56156
Can't read version file: ls-version_.py. Fall back to: version_.py
Can't read version file: version_.py
Traceback (most recent call last):
  File "/home/hemang/anaconda3/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio/server.py", line 296, in main
    _setup_env()
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/hemang/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio/data_export/models.py", line 19, in <module>
    from label_studio_converter import Converter
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/__init__.py", line 3, in <module>
    from .converter import Converter
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/converter.py", line 19, in <module>
    from label_studio_converter.exports import csv2
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/exports/csv2.py", line 9, in <module>
    from label_studio_converter.utils import ensure_dir, get_annotator, prettify_result
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/utils.py", line 18, in <module>
    from nltk.tokenize.treebank import TreebankWordTokenizer
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/__init__.py", line 132, in <module>
    from nltk.collocations import *
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/collocations.py", line 36, in <module>
    from nltk.metrics import (
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/metrics/__init__.py", line 18, in <module>
    from nltk.metrics.association import (
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/metrics/association.py", line 26, in <module>
    from scipy.stats import fisher_exact
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/stats/__init__.py", line 384, in <module>
    from .stats import *
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/stats/stats.py", line 179, in <module>
    from scipy.spatial.distance import cdist
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 97, in <module>
    from .kdtree import *
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
    import scipy.sparse
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .base import *
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/base.py", line 8, in <module>
    from .sputils import (isdense, isscalarlike, isintlike,
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <module>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <listcomp>
    supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
  File "/home/hemang/anaconda3/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
```

**Comment by makseq** [comment]
Try to explicitly install older versions of numpy, seems it's a dependency problem.

**Comment by hemangjoshi37a** [comment]
It is stock installed from the GitHub repo

**Comment by Lahari-77** [comment]
> Command I ran : `label-studio`
> 
> Error I got :
> 
> ```python
> => Database and media directory: /home/hemang/.local/share/label-studio
> => Static URL is set to: /static/
> => Database and media directory: /home/hemang/.local/share/label-studio
> => Static URL is set to: /static/
> Starting new HTTPS connection (1): pypi.org:443
> https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 56156
> Can't read version file: ls-version_.py. Fall back to: version_.py
> Can't read version file: version_.py
> Traceback (most recent call last):
>   File "/home/hemang/anaconda3/bin/label-studio", line 8, in <module>
>     sys.exit(main())
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio/server.py", line 296, in main
>     _setup_env()
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio/server.py", line 40, in _setup_env
>     application = get_wsgi_application()
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
>     django.setup(set_prefix=False)
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
>     app_config.import_models()
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
>     self.models_module = import_module(models_module_name)
>   File "/home/hemang/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio/data_export/models.py", line 19, in <module>
>     from label_studio_converter import Converter
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/__init__.py", line 3, in <module>
>     from .converter import Converter
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/converter.py", line 19, in <module>
>     from label_studio_converter.exports import csv2
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/exports/csv2.py", line 9, in <module>
>     from label_studio_converter.utils import ensure_dir, get_annotator, prettify_result
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/label_studio_converter/utils.py", line 18, in <module>
>     from nltk.tokenize.treebank import TreebankWordTokenizer
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/__init__.py", line 132, in <module>
>     from nltk.collocations import *
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/collocations.py", line 36, in <module>
>     from nltk.metrics import (
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/metrics/__init__.py", line 18, in <module>
>     from nltk.metrics.association import (
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/nltk/metrics/association.py", line 26, in <module>
>     from scipy.stats import fisher_exact
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/stats/__init__.py", line 384, in <module>
>     from .stats import *
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/stats/stats.py", line 179, in <module>
>     from scipy.spatial.distance import cdist
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 97, in <module>
>     from .kdtree import *
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/spatial/kdtree.py", line 8, in <module>
>     import scipy.sparse
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/__init__.py", line 229, in <module>
>     from .base import *
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/base.py", line 8, in <module>
>     from .sputils import (isdense, isscalarlike, isintlike,
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <module>
>     supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/scipy/sparse/sputils.py", line 17, in <listcomp>
>     supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
>   File "/home/hemang/anaconda3/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'typeDict'
> Sentry is attempting to send 2 pending error messages
> Waiting up to 2 seconds
> Press Ctrl-C to quit
> ```

Works for sureeeee.Give it a try
