### ISSUE TITLE
Yolo format export problem. Keyerror 'rotation'

### ISSUE THREAD

**Issue by sushant097** [heartexlabs/label-studio#4056]
Which version of label studio to get rid of this error. I am trying to export annotations in YOLO format.

Error:
```
'rotation'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_export/api.py", line 183, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "/label-studio/label_studio/data_export/models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "/usr/local/lib/python3.10/dist-packages/label_studio_converter/converter.py", line 191, in convert
    self.convert_to_yolo(input_data, output_data, output_image_dir=image_dir,
  File "/usr/local/lib/python3.10/dist-packages/label_studio_converter/converter.py", line 714, in convert_to_yolo
    x, y, w, h = self.rotated_rectangle(label)
  File "/usr/local/lib/python3.10/dist-packages/label_studio_converter/converter.py", line 748, in rotated_rectangle
    label["rotation"],
KeyError: 'rotation'
```

My Label config: 
![image](https://user-images.githubusercontent.com/30827903/232770419-41ab5666-80fc-4870-8f9c-75e0c63d0422.png)

Output of : `http://localhost:8080/version`:

```
{
  "release": "1.7.2",
  "label-studio-os-package": {
    "version": "1.7.2",
    "short_version": "1.7",
    "latest_version_from_pypi": "1.7.2",
    "latest_version_upload_time": "2023-03-20T16:52:30",
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {
    "message": "fix: LSDV-4740: Video Rectangles are displaying while drawing (#1258)  ...",
    "commit": "3de2ace9b53cf3ab213054a9106079aaf61796a7",
    "date": "2023-03-20 18:10:51 +0400",
    "branch": "HEAD",
    "version": "1.7.2+0.g3de2ace"
  },

  "label-studio-frontend": {
    "message": "fix: LSDV-4740: Video Rectangles are displaying while drawing (#1258)",
    "commit": "9329687afa56d7491f96f4aa2df81b15c12adf7f",
    "branch": "ls-release/1.7.2",
    "date": "2023/03/20 11:03:14"
  },

  "dm2": {
    "message": "Trigger build",
    "commit": "2ee2ddaf9596b9e600bbaf231768acd16815e498",
    "branch": "ls-release/1.7.2",
    "date": "2023-03-09T16:36:40Z"
  },

  "label-studio-converter": {
    "version": "0.0.50"
  }
}
```

I installed it with docker: `docker run -it -p 8080:8080 -v $(pwd)/mydata:/label-studio/data heartexlabs/label-studio:latest`.

[This](https://github.com/heartexlabs/label-studio/issues/3140) is the similar issue, but that not solve my problem.

![image](https://user-images.githubusercontent.com/30827903/232767992-b538bed8-e666-4218-b27e-2663bead31ea.png)

**Comment by makseq** [comment]
Similar: https://github.com/heartexlabs/label-studio/issues/4064#issuecomment-1515591584

**Comment by makseq** [comment]
@sushant097 try to use `heartexlabs/label-studio:develop` (but don't forget to make a DB dump before the upgrade). 
I see your converter version is 0.0.50, but this fix might have been done later.
