### ISSUE TITLE
COCO export failed

### ISSUE THREAD

**Issue by omoigwa93** [heartexlabs/label-studio#4064]
```
Traceback (most recent call last):
  File "C:\Users\Deltra\anaconda3\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Deltra\anaconda3\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\Deltra\anaconda3\lib\site-packages\label_studio\data_export\api.py", line 183, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "C:\Users\Deltra\anaconda3\lib\site-packages\label_studio\data_export\models.py", line 161, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "C:\Users\Deltra\anaconda3\lib\site-packages\label_studio_converter\converter.py", line 212, in convert
    self.convert_to_coco(
  File "C:\Users\Deltra\anaconda3\lib\site-packages\label_studio_converter\converter.py", line 623, in convert_to_coco
    x, y, w, h = self.rotated_rectangle(label)
  File "C:\Users\Deltra\anaconda3\lib\site-packages\label_studio_converter\converter.py", line 860, in rotated_rectangle
    label["x"],
KeyError: 'x'
```

**Comment by makseq** [comment]
show your labeling config, some of your annotations doesn't contain any regions with bboxes.

**Comment by wuzrionic** [comment]
> show your labeling config, some of your annotations doesn't contain any regions with bboxes.

<img width="480" alt="1694799513(1)" src="https://github.com/HumanSignal/label-studio/assets/144780274/3b74d8e8-e3bb-4e21-b507-0f13d03bf471">
i met the same question when i tried to export a xml formats datasets.

**Comment by Sishxo** [comment]
I met the same issue, key error:"x" problem. And this happens only when i choose to export pascal voc xml format and coco foramt. Json and jsonmin is ok with it.

**Comment by Sishxo** [comment]
There is some extra error information that may be helpful for fixing it:
![image](https://github.com/HumanSignal/label-studio/assets/54496724/28a72099-ac22-411f-aaac-8ffcf8685e55)
Above are normal bounding box dic, and below are bbox causing the bug.

**Comment by Sishxo** [comment]
I think it's a bug caused by label_studio_converter
