### ISSUE TITLE
AssertionError: Job 1682234771 was finished unsuccessfully

### ISSUE THREAD

**Issue by Yakuho** [heartexlabs/label-studio#4082]
When the program runs, I operate on the UI page, ML backend repeatedly error, unable to predict the task, how to do? I checked the documentation and couldn't find any similar problems.

```
[2023-04-23 15:26:18,185] [ERROR] [label_studio_ml.model::get_result_from_last_job::133] 1682234771 job returns exception: Job 1682234771 was finished unsuccessfully. No result was saved in job folder.Please clean up failed job folders to remove this error from log.
Traceback (most recent call last):
  File "/data/AIAnalysis/label-studio-backend/label_studio_ml/model.py", line 131, in get_result_from_last_job
    result = self.get_result_from_job_id(job_id)
  File "/data/AIAnalysis/label-studio-backend/label_studio_ml/model.py", line 112, in get_result_from_job_id
    assert isinstance(result, dict), f"Job {job_id} was finished unsuccessfully. No result was saved in job folder." \
AssertionError: Job 1682234771 was finished unsuccessfully. No result was saved in job folder.Please clean up failed job folders to remove this error from log.
```

**Comment by Yakuho** [comment]
Also, I don't understand the meaning of model version.  I have compared the front-end and back-end model version dir, and it seems that some do not match

**Comment by Yakuho** [comment]
Having another problem when I am using YOLOv5. According to the document, I write the code in the following form. However, it is found that every time the front-end calls predict APIs, the class is initialized once, which results in the creation of the model!!!
```python
from label_studio_ml.utils import get_image_size, get_single_tag_keys, get_local_path, get_env
from label_studio_ml.model import LabelStudioMLBase
from engine import YOLOV5DetectEngine
HOSTNAME = ""
APIKEY = ""


class LSBackendYOLOv5(LabelStudioMLBase):
    def __init__(self, **kwargs):
        super(LSBackendYOLOv5, self).__init__(**kwargs)
        self.from_name, self.to_name, self.value, self.labels_in_config = get_single_tag_keys(self.parsed_label_config, 'RectangleLabels', 'Image')
        self.labels_in_config = set(self.labels_in_config)	
        self.model = YOLOV5DetectEngine(device=3)

    def predict(self, tasks, **kwargs):
        predictions = []
        for task in tasks:
            # img_url = get_local_path(task['data'][self.value], hostname=HOSTNAME, access_token=APIKEY)
            frame = url2image(task['data'][self.value], hostname=HOSTNAME, access_token=APIKEY)
            height, width = frame.shape[:2]

            result, im0s = self.model.inference(frame, conf_thres=0.5)
            for index, item in enumerate(result):
                label = item["label"]
                conf = item["conf"]
                x, y = item["x_min"], item["y_min"]
                w, h = item["x_max"] - item["x_min"], item["y_max"] - item["y_min"]

                if label not in self.labels_in_config:
                    print(label + ' label not found in project config.')
                    continue

                predictions.append({
                    "original_width": width,
                    "original_height": height,
                    "image_rotation": 0,
                    "value": {
                        "x": x / width * 100,
                        "y": y / height * 100,
                        "width": w / width * 100,
                        "height": h / height * 100,
                        "rotation": 0,
                        "rectanglelabels": [label],
                    },
                    "id": f"YOLOv5-{time.time() * 1000}",
                    "from_name": self.from_name,
                    "to_name": self.to_name,
                    "type": "rectanglelabels",
                    "score": conf * 100
                })

        results = [{'result': predictions, 'score': 88.888}]
        return results
```
```
[2023-04-23 16:25:52,124] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:25:52] "GET /health HTTP/1.1" 200 -
YOLOv5 🚀 2023-2-22 Python-3.8.0 torch-1.12.1 CUDA:3 (Tesla P4, 7612MiB)

Fusing layers... 
YOLOv5s summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
[2023-04-23 16:25:52,602] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:25:52] "POST /setup HTTP/1.1" 200 -
[2023-04-23 16:25:52,703] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:25:52] "GET /health HTTP/1.1" 200 -
YOLOv5 🚀 2023-2-22 Python-3.8.0 torch-1.12.1 CUDA:3 (Tesla P4, 7612MiB)

Fusing layers... 
YOLOv5s summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
[2023-04-23 16:25:53,114] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:25:53] "POST /setup HTTP/1.1" 200 -
[2023-04-23 16:25:58,045] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:25:58] "GET /health HTTP/1.1" 200 -
YOLOv5 🚀 2023-2-22 Python-3.8.0 torch-1.12.1 CUDA:3 (Tesla P4, 7612MiB)

Fusing layers... 
YOLOv5s summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
[2023-04-23 16:25:58,398] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:25:58] "POST /setup HTTP/1.1" 200 -
[2023-04-23 16:26:09,399] [INFO] [werkzeug::_log::225] 172.17.0.8 - - [23/Apr/2023 16:26:09] "GET /health HTTP/1.1" 200 -
YOLOv5 🚀 2023-2-22 Python-3.8.0 torch-1.12.1 CUDA:3 (Tesla P4, 7612MiB)

Fusing layers... 
YOLOv5s summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
```
I think I really need some information about the model version!!

**Comment by AkashDataScience** [comment]
I am facing same issue with YOLOv7. @Yakuho Did you find any solution?

**Comment by Yakuho** [comment]
> I am facing same issue with YOLOv7. @Yakuho Did you find any solution?

you can go [label-studio-ml-backend](https://github.com/heartexlabs/label-studio-ml-backend/issues/164), you can solve some problems in related topics. And you can go project with ```label-studio-ml-backend/label_studio_ml/model.py```, turn it True ```LABEL_STUDIO_ML_BACKEND_V2_DEFAULT = False```, It seems to have had some effect.

**Comment by KonstantinKorotaev** [comment]
Hi @Yakuho 
You can use IGNORE_FAILED_TRAINING environment variable to switch off Assertion errors.

**Comment by KonstantinKorotaev** [comment]
> And you can go project with label-studio-ml-backend/label_studio_ml/model.py, turn it True LABEL_STUDIO_ML_BACKEND_V2_DEFAULT = False, It seems to have had some effect.

This flag turns off active learning cycle in ML backend, please check [our guide](https://docs.heartex.com/guide/active_learning.html) on it

**Comment by Yakuho** [comment]
> 你好@Yakuho 您可以使用 IGNORE_FAILED_TRAINING 环境变量来关闭断言错误。

Is there any downside to turning off assertions？I'm worried that it keeps new object

**Comment by Yakuho** [comment]
> > And you can go project with label-studio-ml-backend/label_studio_ml/model.py, turn it True LABEL_STUDIO_ML_BACKEND_V2_DEFAULT = False, It seems to have had some effect.
> 
> This flag turns off active learning cycle in ML backend, please check [our guide](https://docs.heartex.com/guide/active_learning.html) on it

I notice source code, model version will lose efficacy when turn it True, so I gaust it will reduce raise some Error :-)

**Comment by KonstantinKorotaev** [comment]
> Is there any downside to turning off assertions？I'm worried that it keeps new object

You won't get assertion messages about training errors.

**Comment by AkashDataScience** [comment]
Disabling the webhook solved the assertion error.  But, the model is still initialized for each prediction call from UI.
