### ISSUE TITLE
Error in Ubuntu 23.04 using `python3.11-venv`

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [heartexlabs/label-studio#4120]
After upgrading to Ubuntu 23.04 with Python 3.11, label-studio will install without errors but will not launch using a Python 3.11 venv. 

For a workaround, as `python3.10-venv` is uninstalled during upgrade, I used `python3-virtualenv` as per the below:
```
sudo apt-get install python3-virtualenv
virtualenv --python=/usr/bin/python3.10 env3.10
source env3.10/bin/activate
pip install label-studio
export PATH=$PATH:`which python`
label-studio
```

To reproduce the issue:
```
python3 -m venv env3.11
source env3.11/bin/activate
pip install label-studio
label-studio                               
=> Database and media directory: /home/[user]/.local/share/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /home/[user]/.local/share/label-studio
=> Static URL is set to: /static/
Traceback (most recent call last):
  File "/home/[user]/env/bin/label-studio", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/[user]/env/lib/python3.11/site-packages/label_studio/server.py", line 290, in main
    _setup_env()
  File "/home/[user]/env/lib/python3.11/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[user]/env/lib/python3.11/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/[user]/env/lib/python3.11/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[user]/env/lib/python3.11/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/[user]/env/lib/python3.11/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/[user]/env/lib/python3.11/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/[user]/env/lib/python3.11/site-packages/label_studio/core/settings/label_studio.py", line 48, in <module>
    from label_studio.core.utils.common import collect_versions
  File "/home/[user]/env/lib/python3.11/site-packages/label_studio/core/utils/common.py", line 19, in <module>
    import drf_yasg.openapi as openapi
  File "/home/[user]/env/lib/python3.11/site-packages/drf_yasg/openapi.py", line 11, in <module>
    from .utils import dict_has_ordered_keys, filter_none, force_real_str
  File "/home/[user]/env/lib/python3.11/site-packages/drf_yasg/utils.py", line 10, in <module>
    from rest_framework import serializers, status
  File "/home/[user]/env/lib/python3.11/site-packages/rest_framework/serializers.py", line 27, in <module>
    from rest_framework.compat import postgres_fields
  File "/home/[user]/env/lib/python3.11/site-packages/rest_framework/compat.py", line 25, in <module>
    from django.contrib.postgres import fields as postgres_fields
  File "/home/[user]/env/lib/python3.11/site-packages/django/contrib/postgres/fields/__init__.py", line 1, in <module>
    from .array import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^^
  File "/home/[user]/env/lib/python3.11/site-packages/django/contrib/postgres/fields/array.py", line 3, in <module>
    from django.contrib.postgres import lookups
  File "/home/[user]/env/lib/python3.11/site-packages/django/contrib/postgres/lookups.py", line 4, in <module>
    from .search import SearchVector, SearchVectorExact, SearchVectorField
  File "/home/[user]/env/lib/python3.11/site-packages/django/contrib/postgres/search.py", line 1, in <module>
    import psycopg2
  File "/home/[user]/env/lib/python3.11/site-packages/psycopg2/__init__.py", line 51, in <module>
    from psycopg2._psycopg import (                     # noqa
SystemError: initialization of _psycopg raised unreported exception
Starting new HTTPS connection (1): o227124.ingest.sentry.io:443
https://o227124.ingest.sentry.io:443 "POST /api/5820521/envelope/ HTTP/1.1" 429 198
```

**Comment by thak123** [comment]
same problem

**Comment by makseq** [comment]
Python 3.11 is not yet support by LS.

**Comment by sheldonmaschmeyer** [comment]
That is correct. I have **not** tried 3.11 for latest version released two days ago (upgrading went well) as python patches don't seem to be in the release notes: https://github.com/heartexlabs/label-studio/releases/tag/1.8.0
