### ISSUE TITLE
Following frontend#readme lead to Error: Cannot find module 'puppeteer/internal/node/install.js'

### ISSUE THREAD

**Issue by druzhynin-oleksii** [heartexlabs/label-studio#4223]
**Describe the bug**
I follow https://github.com/heartexlabs/label-studio/tree/develop/label_studio/frontend#readme in clean develop branch and can't build the frontend.

**To Reproduce**
> npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.

I fix it with
npm install --package-lock-only

> npm ci

> puppeteer@19.11.1 postinstall /data/lib/labelig/label-studio/label_studio/frontend/node_modules/puppeteer
> node install.js

Browser download failed { Error: Cannot find module 'puppeteer/internal/node/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/data/lib/labelig/label-studio/label_studio/frontend/node_modules/puppeteer/install.js:39:29)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
added 1528 packages in 10.254s

**Expected behavior**
following https://github.com/heartexlabs/label-studio/tree/develop/label_studio/frontend#readme should give no errors

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.6 LTS
 - Label Studio Version 1.5.0dev
 - NPM 6.14.4

**Additional context**
I want to change opacity of BrushLabel from 0.6 to 0.2

**Comment by druzhynin-oleksii** [comment]
Fixed using https://stackoverflow.com/questions/75003342/using-npm-to-install-puppetteer-gives-error-cannot-find-module-puppeteer-inter

but **npm ci** work only with **--force**

**Comment by druzhynin-oleksii** [comment]
**npm ci --force** for the develop branch
```
npm WARN Could not resolve dependency:
npm WARN peer react@">=15.5 <=16.x" from react-codemirror2@7.2.1
npm WARN node_modules/react-codemirror2
npm WARN   dev react-codemirror2@"^7.2.1" from the root project
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@">=15.5 <=16.x" from react-codemirror2@7.2.1
npm WARN   node_modules/react-codemirror2
npm WARN     dev react-codemirror2@"^7.2.1" from the root project
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: enzyme-adapter-utils@1.14.0
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   dev react@"^17.0.1" from the root project
npm WARN   10 more (@sentry/react, @wojtekmaj/enzyme-adapter-react-17, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0" from enzyme-adapter-utils@1.14.0
npm WARN node_modules/@wojtekmaj/enzyme-adapter-react-17/node_modules/enzyme-adapter-utils
npm WARN   enzyme-adapter-utils@"^1.14.0" from @wojtekmaj/enzyme-adapter-react-17@0.4.1
npm WARN   node_modules/@wojtekmaj/enzyme-adapter-react-17
npm WARN 
npm WARN Conflicting peer dependency: react@16.14.0
npm WARN node_modules/react
npm WARN   peer react@"0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0" from enzyme-adapter-utils@1.14.0
npm WARN   node_modules/@wojtekmaj/enzyme-adapter-react-17/node_modules/enzyme-adapter-utils
npm WARN     enzyme-adapter-utils@"^1.14.0" from @wojtekmaj/enzyme-adapter-react-17@0.4.1
npm WARN     node_modules/@wojtekmaj/enzyme-adapter-react-17
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-test-renderer@17.0.2
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   dev react@"^17.0.1" from the root project
npm WARN   10 more (@sentry/react, @wojtekmaj/enzyme-adapter-react-17, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"17.0.2" from react-test-renderer@17.0.2
npm WARN node_modules/@wojtekmaj/enzyme-adapter-react-17/node_modules/react-test-renderer
npm WARN   react-test-renderer@"^17.0.0" from @wojtekmaj/enzyme-adapter-react-17@0.4.1
npm WARN   node_modules/@wojtekmaj/enzyme-adapter-react-17
npm WARN 
npm WARN Conflicting peer dependency: react@17.0.2
npm WARN node_modules/react
npm WARN   peer react@"17.0.2" from react-test-renderer@17.0.2
npm WARN   node_modules/@wojtekmaj/enzyme-adapter-react-17/node_modules/react-test-renderer
npm WARN     react-test-renderer@"^17.0.0" from @wojtekmaj/enzyme-adapter-react-17@0.4.1
npm WARN     node_modules/@wojtekmaj/enzyme-adapter-react-17
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: airbnb-prop-types@2.16.0
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   dev react@"^17.0.1" from the root project
npm WARN   10 more (@sentry/react, @wojtekmaj/enzyme-adapter-react-17, ...)
```

**Comment by AbubakarSaad** [comment]
Are you still running into this issue? Also, just friendly reminder about LSF. https://label-studio.slack.com/archives/C01SGRVH4MR/p1686617632135849

**Comment by druzhynin-oleksii** [comment]
Hi Abubakar.
I just ignored it and able to run the code.

**Comment by druzhynin-oleksii** [comment]
To be honest. I am still confused who generates this https://raw.githubusercontent.com/heartexlabs/label-studio/develop/label_studio/frontend/dist/lsf/js/main.js

I have beatified this file and and edit manually.
