### ISSUE TITLE
label studio start error: AttributeError: module 'attr' has no attribute 's'

### ISSUE THREAD

**Issue by kulnor** [heartexlabs/label-studio#4293]
**Describe the bug**
I just installed label studio on a fresh AWS t3 instance and am seeing the error below when trying to start.

**To Reproduce**
1. Create a new AWS t3 Linux  instance and SSH
2. sudo yum install python3-pip
3. pip3 install label-studio
4. label-studio

**Expected behavior**
label studio starts without error

**Environment (please complete the following information):**
 - OS: Amazon Linux ami-0ab193018f3e9351b / al2023-ami-2023.0.20230517.1-kernel-6.1-x86_64
 - Python: 3.9.16
 - Label Studio Version: 1.7.3

**Additional context**
=> Database and media directory: /home/ec2-user/.local/share/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /home/ec2-user/.local/share/label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 56465
Can't read version file: ls-version_.py. Fall back to: version_.py
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/server.py", line 296, in main
    _setup_env()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/.local/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/users/models.py", line 18, in <module>
    from projects.models import Project
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/projects/models.py", line 15, in <module>
    from projects.functions.utils import make_queryset_from_iterable
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/projects/functions/__init__.py", line 4, in <module>
    from tasks.models import Annotation, Task
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/tasks/models.py", line 32, in <module>
    from core.label_config import SINGLE_VALUED_TAGS
  File "/home/ec2-user/.local/lib/python3.9/site-packages/label_studio/core/label_config.py", line 9, in <module>
    import jsonschema
  File "/usr/lib/python3.9/site-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/usr/lib/python3.9/site-packages/jsonschema/exceptions.py", line 152, in <module>
    @attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'

**Comment by klgsnd** [comment]
Bumped into this as well. There are two functionally similar dependencies **attr** and **attrs**, except for **attrs** if a more feature-full option. After I had removed the **attr** package, the issue gone. My dumb guess would be: because their module names clashes python resolves **attr** from **attr** first, not giving the way to the **attr** from **attrs**

**Comment by kulnor** [comment]
Removing the attr package as suggested by @dns-xyz-glk solves this problem (thanks!):
`pip3 uninstall attr`

**Comment by BhooshanDeshpande** [comment]
This worked for me

**Comment by nszceta** [comment]
This is still a problem when following the quick start guide on a fresh installation. Kulnor's workaround works.

**Comment by gsriramit** [comment]
The workaround worked for me as well. Thank you @kulnor

**Comment by mussandi** [comment]
@BhooshanDeshpande , thanks. It's working well.

**Comment by hichys** [comment]
got the same issue , 
pip3 uninstall attr << solved the issue

**Comment by hl037** [comment]
Still, it's in the dependency, and get reinstalled each time...
