### ISSUE TITLE
Getting error while starting label-studio

### ISSUE THREAD

**Issue by gandhipurav** [heartexlabs/label-studio#4388]
**Describe the bug**
When I start label-studio it get the following error

`$ label-studio 
=> Database and media directory: /home/privategpt/.local/share/label-studio
=> Static URL is set to: /static/
=> Database and media directory: /home/privategpt/.local/share/label-studio
=> Static URL is set to: /static/
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 57083
Can't read version file: ls-version_.py. Fall back to: version_.py
Traceback (most recent call last):
  File "/home/privategpt/.local/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/server.py", line 296, in main
    _setup_env()
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/server.py", line 40, in _setup_env
    application = get_wsgi_application()
  File "/home/privategpt/env/lib/python3.8/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/home/privategpt/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/privategpt/env/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/privategpt/env/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/users/models.py", line 18, in <module>
    from projects.models import Project
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/projects/models.py", line 15, in <module>
    from projects.functions.utils import make_queryset_from_iterable
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/projects/functions/__init__.py", line 4, in <module>
    from tasks.models import Annotation, Task
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/tasks/models.py", line 32, in <module>
    from core.label_config import SINGLE_VALUED_TAGS
  File "/home/privategpt/.local/lib/python3.8/site-packages/label_studio/core/label_config.py", line 9, in <module>
    import jsonschema
  File "/usr/lib/python3/dist-packages/jsonschema/__init__.py", line 11, in <module>
    from jsonschema.exceptions import (
  File "/usr/lib/python3/dist-packages/jsonschema/exceptions.py", line 152, in <module>
    @attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
`

**To Reproduce**
1. label-studio start

**Expected behavior**
It should start the label-studio

**Screenshots**
<img width="463" alt="Screenshot 2023-06-15 at 6 28 52 PM" src="https://github.com/heartexlabs/label-studio/assets/3352139/d2476f0d-2614-4c09-8800-f00ff623d897">

**Environment (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Label Studio Version - Latest

**Additional context**

**Comment by jahangirli** [comment]
same here

**Comment by Marc-JuBo** [comment]
Had the same issue. Got it solved thanks to this page: [https://github.com/HumanSignal/label-studio/issues/2460](url)

They essentally suggested using this command:     (un-installing and installing a few packages)
`pip uninstall attr && pip install jsonschema==4.9.1 attrs==22.1.0`

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
