### ISSUE TITLE
COCO export error

### ISSUE THREAD

**Issue by Mrasipila** [heartexlabs/label-studio#4399]
I get a keyerror exception when trying to export to COCO. 
I deleted a label and removed every of it's annotations, but when i export to JSON format, this specific label won't disappear from the file, which explains the keyerror. 

Steps to reproduce the behavior :
1. From the setting menu : delete the label (class)
2. Remove every of the annotation appearance of this label from the tasks

Traceback (most recent call last):
  File "C:\root\anaconda3\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\root\anaconda3\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\root\anaconda3\lib\site-packages\label_studio\data_export\api.py", line 190, in get
    export_stream, content_type, filename = DataExport.generate_export_file(
  File "C:\root\anaconda3\lib\site-packages\label_studio\data_export\models.py", line 162, in generate_export_file
    converter.convert(input_json, tmp_dir, output_format, is_dir=False)
  File "C:\root\anaconda3\lib\site-packages\label_studio_converter\converter.py", line 212, in convert
    self.convert_to_coco(
  File "C:\root\anaconda3\lib\site-packages\label_studio_converter\converter.py", line 618, in convert_to_coco
    category_id = category_name_to_id[category_name]
KeyError: 'numero de compte'

![image](https://github.com/heartexlabs/label-studio/assets/30113273/d35806f8-f50c-4bde-8a4f-f024038a2627)

Environment :
 - OS: Windows
 - Label Studio Version 1.8.0

**Comment by AbubakarSaad** [comment]
Hello Mrasipila,

Check in the task source of the task if there label does exist.
