### ISSUE TITLE
'NoneType' object has no attribute 'get_parsed_config' in LabelStudio 1.7+

### ISSUE THREAD

**Issue by Raven888888** [heartexlabs/label-studio#4413]
**Describe the bug**
I use docker container Label Studio 1.6.0 mounted with /label-studio/data, then I upgrade to LabelStudio 1.8.0 by simply kill the container, rerun the docker command with the same mounted volume and newer version. 
```
docker run -d --restart always  -p 8080:8080 -v /home/meta/.local/share/label-studio/:/label-studio/data heartexlabs/label-studio:1.8.0
```

From the container logs, there is no error or no logs about database schema update or anything.

However, when I create export for Video Object Tracking Annotation project, using POST `http://localhost:8080/api/projects/1545/exports` with payload 
```json
{
  "title": "test2",
  "status": "created",
  "md5": "string",
  "counters": {},
  "task_filter_options": {
      "annotated": "only"
  },
  "serialization_options": {
    "interpolate_key_frames": true
  }
}
```

It failed with status 201 Created. The container logs show
```
[2023-06-19 16:38:12,417] [data_export.mixins::export_to_file::265] [ERROR] Export was failed
Traceback (most recent call last):
  File "/label-studio/label_studio/data_export/mixins.py", line 242, in export_to_file
    SerializableGenerator(
  File "/label-studio/label_studio/core/utils/io.py", line 162, in __init__
    self._head = iter([next(tmp_body)])
  File "/label-studio/label_studio/data_export/mixins.py", line 208, in get_export_data
    for task in serializer.data:
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/label-studio/label_studio/data_export/serializers.py", line 64, in to_representation
    return super().to_representation(task)
  File "/usr/local/lib/python3.10/dist-packages/rest_flex_fields/serializers.py", line 64, in to_representation
    return super().to_representation(instance)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.10/dist-packages/rest_flex_fields/serializers.py", line 64, in to_representation
    return super().to_representation(instance)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/serializers.py", line 522, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/fields.py", line 1886, in to_representation
    return method(value)
  File "/label-studio/label_studio/data_export/serializers.py", line 39, in get_result
    is_video_object_tracking(parsed_config=obj.project.get_parsed_config()):
AttributeError: 'NoneType' object has no attribute 'get_parsed_config'
/usr/local/lib/python3.10/dist-packages/django/db/models/fields/__init__.py:1416: RuntimeWarning: DateTimeField Export.finished_at received a naive datetime (2023-06-19 16:38:12.574332) while time zone support is active.
  warnings.warn("DateTimeField %s received a naive datetime (%s)"
```

This api is working totally fine in 1.6.0.
This bug can be reproduced in 1.7.0 as well.

**Environment (please complete the following information):**
 - Label Studio 1.8.0
 - Docker container

**Comment by AbubakarSaad** [comment]
Hello Raven,

Was migrations run on the database when you updated the image tag? I think its because of migrations. Try this way. Just make sure to back up your db before trying

1. Navigate to the Label Studio directory where the `manage.py` file is located. If you installed Label Studio using pip, the directory should be in your Python environment's `site-packages/label_studio` folder.

2. Run the following command to apply any necessary database migrations:

```bash
python manage.py migrate
```

3. (Optional) If you have static files, run the following command to collect them:

```bash
python manage.py collectstatic
```

4. Start Label Studio and verify that your projects and data have been migrated successfully.

**Comment by Raven888888** [comment]
Hi @AbubakarSaad 

Thanks for the advice, I'll try it.

Just a few questions:

1. This migration steps are not in the [official upgrade guide](https://labelstud.io/guide/install.html#Upgrade-Label-Studio) (pip installation), why? Is it because pip already handles it behind the scene?

2. What are static files? Where are they located? What exactly does the `collectstatic` do?

**Comment by Raven888888** [comment]
@AbubakarSaad @makseq 

Unfortunately, this does not work. I tried `makemigrations` and `migrate` at each major version docker image (1.6.0, 1.7.0, 1.8.0), and still gets the error when export video tracking annotation with interpolate_key_frames

Note that I am using sqlite db

**Comment by Raven888888** [comment]
I dig deeper, and found out the reason is due to `task_completion` does not have `project_id`, hence when export annotation, it will hit error at https://github.com/heartexlabs/label-studio/blob/35618d5209b9d06f2bfe82a65bc7a4b2a3f2a713/label_studio/data_export/serializers.py#L39
because `obj.project` is `NULL` in the db.

It used to have `project_id` all the time, until last month when I tried to "upgrade" LS from 1.6.0 to 1.7.0 _without explicitly run manage.py migrate_ (because I did not know this). Then I started to realised export annotation not working anymore.

Immediately, I revert the docker image to LS 1.6.0, and export annotation continues to work, _even for `obj.project` is `NULL`  annotations_. I believe the line of code above is only added after LS 1.6.0.

Now, I try to debug why after that "failed upgrade and download", my LS 1.6.0 no longer able to create new annotations with proper `project_id`? 

When I create a new annotation, this is the server logs

```
[2023-06-25 01:24:26,314] [tasks.api::perform_create::382] [DEBUG] User=xxx: there are no predictions for task=Task object (48822)
[2023-06-25 01:24:26,314] [tasks.api::perform_create::396] [DEBUG] User=xxx: save annotation
[2023-06-25 01:24:26,403] [tasks.models::increase_project_summary_counters::405] [DEBUG] Increase project.summary counters from Annotation object (62001)
[2023-06-25 01:24:26,403] [projects.models::update_created_annotations_and_labels::1041] [DEBUG] summary.created_annotations = {'label|ts|timeserieslabels': 118, 'label1|ts1|timeserieslabels': 136}
[2023-06-25 01:24:26,403] [projects.models::update_created_annotations_and_labels::1042] [DEBUG] summary.created_labels = {'label': {'Spike': 117}, 'label1': {'Out Spike': 135}}
[2023-06-25 01:24:26,429] [tasks.models::update_project_summary_annotations_and_is_labeled::683] [DEBUG] Update task stats for task=Task object (48822)
[2023-06-25 01:24:26,433] [projects.models::remove_data_columns::984] [DEBUG] summary.all_data_columns = {'image': 597}
[2023-06-25 01:24:26,433] [projects.models::remove_data_columns::985] [DEBUG] summary.common_data_columns = ['image']
[2023-06-25 01:24:26,509] [projects.models::update_data_columns::960] [DEBUG] summary.all_data_columns = {'image': 599}
[2023-06-25 01:24:26,509] [projects.models::update_data_columns::961] [DEBUG] summary.common_data_columns = ['image']
[2023-06-25 01:24:26,613] [tasks.models::update_project_summary_annotations_and_is_labeled::690] [DEBUG] Updated total_annotations and cancelled_annotations for 48822.
[2023-06-25 01:24:26,615] [tasks.models::delete_draft::718] [DEBUG] 0 drafts removed from task Task object (48822) after saving annotation Annotation object (62001)
[2023-06-25 01:24:26,625] [projects.models::remove_data_columns::984] [DEBUG] summary.all_data_columns = {'image': 598}
[2023-06-25 01:24:26,625] [projects.models::remove_data_columns::985] [DEBUG] summary.common_data_columns = ['image']
[2023-06-25 01:24:26,840] [projects.models::update_data_columns::960] [DEBUG] summary.all_data_columns = {'image': 600}
[2023-06-25 01:24:26,840] [projects.models::update_data_columns::961] [DEBUG] summary.common_data_columns = ['image']
[2023-06-25 01:24:26,939] [tasks.api::perform_create::398] [DEBUG] Save activity for user=xxx
[2023-06-25 01:24:27,065] [tasks.api::perform_create::403] [DEBUG] User=xxx releases task=Task object (48822)
[2023-06-25 01:24:27,068] [tasks.api::perform_create::409] [DEBUG] Remove draft 0 after creating annotation 62001
[2023-06-25 01:24:27,080] [urllib3.connectionpool::_new_conn::1003] [DEBUG] Starting new HTTPS connection (1): tele.labelstud.io:443
[2023-06-25 01:24:27,081] [django.server::log_message::161] [INFO] "POST /api/tasks/48822/annotations?project=1058 HTTP/1.1" 201 535
[2023-06-25 01:24:27,081] [django.server::log_message::161] [INFO] "POST /api/tasks/48822/annotations?project=1058 HTTP/1.1" 201 535
[2023-06-25 01:24:27,204] [core.feature_flags.base::_get_user_repr::71] [DEBUG] Read user properties: {'id': 1, 'first_name': '', 'last_name': '', 'username': 'xxx', 'email': 'xxx', 'last_activity': '2023-06-01T08:00:47.792927Z', 'avatar': None, 'initials': 'ch', 'phone': '', 'active_organization': 1, 'allow_newsletters': None, 'key': 'xxx', 'custom': {'organization': 'xxx'}}
[2023-06-25 01:24:27,225] [django.server::log_message::161] [INFO] "GET /api/tasks/48822?project=1058 HTTP/1.1" 200 2527
[2023-06-25 01:24:27,225] [django.server::log_message::161] [INFO] "GET /api/tasks/48822?project=1058 HTTP/1.1" 200 2527
[2023-06-25 01:24:27,226] [urllib3.connectionpool::_new_conn::1003] [DEBUG] Starting new HTTPS connection (1): tele.labelstud.io:443
/usr/local/lib/python3.10/dist-packages/rest_framework/pagination.py:200: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'labels_manager.models.LabelLink'> QuerySet.
  paginator = self.django_paginator_class(queryset, page_size)
[2023-06-25 01:24:27,285] [urllib3.connectionpool::_new_conn::1003] [DEBUG] Starting new HTTPS connection (1): tele.labelstud.io:443
[2023-06-25 01:24:27,285] [django.server::log_message::161] [INFO] "GET /api/label_links?project=1058&expand=label HTTP/1.1" 200 52
[2023-06-25 01:24:27,285] [django.server::log_message::161] [INFO] "GET /api/label_links?project=1058&expand=label HTTP/1.1" 200 52
[2023-06-25 01:24:27,300] [data_import.api::get::457] [DEBUG] Fetch uploaded file by user xxx => upload/1058/523c59ab-Spike_Detection_2023-04-13_00000000d6784357.csv
[2023-06-25 01:24:27,307] [django.server::log_message::161] [INFO] "GET /data/upload/1058/523c59ab-Spike_Detection_2023-04-13_00000000d6784357.csv HTTP/1.1" 200 1241
[2023-06-25 01:24:27,307] [django.server::log_message::161] [INFO] "GET /data/upload/1058/523c59ab-Spike_Detection_2023-04-13_00000000d6784357.csv HTTP/1.1" 200 1241
[2023-06-25 01:24:27,308] [urllib3.connectionpool::_new_conn::1003] [DEBUG] Starting new HTTPS connection (1): tele.labelstud.io:443
[2023-06-25 01:24:27,333] [data_import.api::get::457] [DEBUG] Fetch uploaded file by user xxx => upload/1058/523c59ab-Spike_Detection_2023-04-13_00000000d6784357.csv
[2023-06-25 01:24:27,344] [urllib3.connectionpool::_new_conn::1003] [DEBUG] Starting new HTTPS connection (1): tele.labelstud.io:443
[2023-06-25 01:24:27,345] [django.server::log_message::161] [INFO] "GET /data/upload/1058/523c59ab-Spike_Detection_2023-04-13_00000000d6784357.csv HTTP/1.1" 200 1241
[2023-06-25 01:24:27,345] [django.server::log_message::161] [INFO] "GET /data/upload/1058/523c59ab-Spike_Detection_2023-04-13_00000000d6784357.csv HTTP/1.1" 200 1241
[2023-06-25 01:24:28,204] [urllib3.connectionpool::_make_request::456] [DEBUG] https://tele.labelstud.io:443 "POST / HTTP/1.1" 200 0
[2023-06-25 01:24:28,259] [urllib3.connectionpool::_make_request::456] [DEBUG] https://tele.labelstud.io:443 "POST / HTTP/1.1" 200 0
[2023-06-25 01:24:28,382] [urllib3.connectionpool::_make_request::456] [DEBUG] https://tele.labelstud.io:443 "POST / HTTP/1.1" 200 0
[2023-06-25 01:24:28,399] [urllib3.connectionpool::_make_request::456] [DEBUG] https://tele.labelstud.io:443 "POST / HTTP/1.1" 200 0
[2023-06-25 01:24:28,432] [urllib3.connectionpool::_make_request::456] [DEBUG] https://tele.labelstud.io:443 "POST / HTTP/1.1" 200 0
```

And this is in the db

```
select * from task_completion where task_id = 78372;

id|result|was_cancelled|created_at|updated_at|task_id|prediction|lead_time|result_count|completed_by_id|ground_truth|parent_prediction_id|last_action|last_created_by_id|project_id|updated_by_id|unique_id|draft_created_at|parent_annotation_id
49998|[...]|0|2023-05-05 07:51:05.813895|2023-06-08 07:06:06.885941|78372|{}|171.004|0|20|0||||1454|2|||
56056|[...]|0|2023-06-24 08:53:55.574052|2023-06-24 08:54:11.031614|78372|{}|2071.171|0|20|0||||||||
```

*Why this happens?*

**Comment by Raven888888** [comment]
Looking further into the history, this `project_id` change is introduced in https://github.com/heartexlabs/label-studio/commit/a698145ec2f1f5c49c4a42bc106cca83cdc8a2f1

The fact that all of the older `task_completion` have non-null `project_id` means somehow the migration script did run?

**Comment by AbubakarSaad** [comment]
I think that is happening because its apply migrations of 1.8 instead of 1.8. I'll look into a bit more

**Comment by Raven888888** [comment]
Now that I know which migration script to run, is it possible to rerun the migration manually _without using manage.py_? (because the migration already completed once in the past, now I want to do it again)

For example, I want to run https://github.com/heartexlabs/label-studio/blob/bfd332b6766988dc7334449eacfbb00fc65cdeb3/label_studio/tasks/migrations/0030_auto_20221102_1118.py to fill up those empty `project_id`.

Or, how do I modify the table `django_migrations` so that it can rerun the migrations?

**Comment by Raven888888** [comment]
Any update or any comment to my last post? @AbubakarSaad @makseq

**Comment by Raven888888** [comment]
Resolved, the root cause is due database corrupted due to skipped migrations and version rollback. I have to manually delete `django_migrations` and `core_asyncmigrationstatus`, and redo the migrations again
