### ISSUE TITLE
Error when adding local source storage path

### ISSUE THREAD

**Issue by JulianWi21** [heartexlabs/label-studio#4442]
Hey all,

I am trying to import some labels on label studio. I've activated the venv in command line then entered:

set LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true

LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=C:\\Users\\..\\..\\..

label-studio

I've then added the absolute path to the images in la
bel studio cloud storage options but get the following error output:
![test2](https://github.com/heartexlabs/label-studio/assets/56548020/152945bd-6a63-45f1-a15d-b2445fddb9ab)

Here's the log from label-studio:

`Traceback (most recent call last):
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: io_storages_localfilesimportstorage.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\rest_framework\generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\rest_framework\serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\base.py", line 776, in save_base
    updated = self._save_table(
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\base.py", line 919, in _do_insert
    return manager._insert(
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\models\sql\compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\sentry_sdk\integrations\django\__init__.py", line 596, in execute
    return real_execute(self, sql, params)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "c:\users\admin\projects\python-envs\label-studio-venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: io_storages_localfilesimportstorage.status`

Any ideas how to fix this?

**Comment by CarlosModinez** [comment]
I had the same problem and I found the solution on Slack. I would love to say it was super hard to solve but I just needed to update to version 1.8

**Comment by makseq** [comment]
Upgrade to the latest versions of LS should solve this problem.
