### ISSUE TITLE
v1.8.0, Add Model, examples mmdetection, runtime error

### ISSUE THREAD

**Issue by gitgotcha77** [heartexlabs/label-studio#4490]
I installed label-studio and cloned "https://github.com/heartexlabs/label-studio-ml-backend", to add mmdetection, from examples, as a model to an empty project.
My OS is KUbuntu 23.

I've created a conda env for it, with all requirements.
[Label Studio - conda env.txt](https://github.com/heartexlabs/label-studio/files/11995234/Label.Studio.-.conda.env.txt)

From https://labelstud.io/guide/ml.html i tried to start an ML backend, provided in your examples: mmdetection
I've altered the docker-compose.yml to use different volumes:
[docker-compose.yml.txt](https://github.com/heartexlabs/label-studio/files/11995242/docker-compose.yml.txt)

After `docker compose up` i started label-studio and then:
1. Create an empty project
2. Settings
3. Machine Learning
4. Add Model
5. Some random title and description, URL http://localhost:9090/
6. Validate and Save shows "RUNTIME ERROR"

From docker logs:
```
server: [pid: 33|app: 0|req: 5/5] 172.19.0.1 () {32 vars in 655 bytes} [Sun Jul  9 12:53:38 2023] GET /health => generated 54 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
server: [2023-07-09 12:53:38,964] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
server:     return f(*args, **kwargs)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 50, in _setup
server:     model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 507, in fetch
server:     return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 492, in get_or_create
server:     cls.create(project, label_config, train_output, version, **kwargs)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 473, in create
server:     model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
server:   File "./mmdetection.py", line 61, in __init__
server:     self.parsed_label_config, 'RectangleLabels', 'Image')
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/utils.py", line 22, in get_single_tag_keys
server:     assert len(parsed_label_config) == 1
server: AssertionError
server: 
server: Traceback (most recent call last):
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
server:     return f(*args, **kwargs)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/api.py", line 50, in _setup
server:     model = _manager.fetch(project, schema, force_reload, hostname=hostname, access_token=access_token)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 507, in fetch
server:     return cls.get_or_create(project, label_config, force_reload, train_output, version, **kwargs)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 492, in get_or_create
server:     cls.create(project, label_config, train_output, version, **kwargs)
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/model.py", line 473, in create
server:     model=cls.model_class(label_config=label_config, train_output=train_output, **kwargs),
server:   File "./mmdetection.py", line 61, in __init__
server:     self.parsed_label_config, 'RectangleLabels', 'Image')
server:   File "/usr/local/lib/python3.7/site-packages/label_studio_ml/utils.py", line 22, in get_single_tag_keys
server:     assert len(parsed_label_config) == 1
server: AssertionError
server: 
```

Repository version details:
[Label Studio - git version.txt](https://github.com/heartexlabs/label-studio/files/11995232/Label.Studio.-.git.version.txt)

**Comment by hogepodge** [comment]
@gitgotcha77 It looks like your model configuration might be incorrect. Can you please join the [Slack community](https://slack.labelstud.io/?source=github) and ask there, where the openmmlab team is available to help out. My suspicion is that because you're running in docker, the localhost URL isn't resolvable by one of the components.
