### ISSUE TITLE
Null Context send to ml backend api on interactive Annotations

### ISSUE THREAD

**Issue by DaMuBo** [heartexlabs/label-studio#4493]
**Describe the bug**
Using ML Backend for Segment Anything Model predictions.
Getting no predictions.
The Context object sent from label-studio appears to be None. Therefore no prediction could be made

This seems to be a server side issue ( label-studio) that's why i'm adressing it here as well.

**To Reproduce**
1. Go to https://github.com/heartexlabs/label-studio-ml-backend/tree/master/label_studio_ml/examples/segment_anything_model
2. Install the ml backend as described
3. use the ml backend in the frontend
4. try to label an image and click on an object

**Expected behavior**
the object should be getting labelled by the model. But it doesn't
On the logs there is written sth:

```
the kwargs are {'login': None, 'password': None, 'context': None}
the tasks are [{'id': 451102, 'data': {'image': 's3://....jpg', 'ref_id': 3602}, 'meta': {}, 'created_at': '2023-06-20T16:29:12.201416Z', 'updated_at': '2023-06-20T16:29:12.201442Z', 'is_labeled': False, 'overlap': 1, 'inner_id': 2, 'total_annotations': 0, 'cancelled_annotations': 0, 'total_predictions': 0, 'comment_count': 0, 'unresolved_comment_count': 0, 'last_comment_updated_at': None, 'project': 218, 'updated_by': None, 'file_upload': None, 'comment_authors': [], 'annotations': [], 'predictions': []}]
[2023-06-27 14:13:42,314] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 617, in predict
predictions = cls._current_model.model.predict(tasks, **kwargs)
File "/app/segment_anything_model.py", line 70, in predict
height = kwargs['context']['result'][0]['original_height']
TypeError: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
return f(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 51, in _predict
predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
File "/usr/local/lib/python3.8/site-packages/label_studio_ml/model.py", line 617, in predict
predictions = cls._current_model.model.predict(tasks, **kwargs)
File "/app/segment_anything_model.py", line 70, in predict
height = kwargs['context']['result'][0]['original_height']
TypeError: 'NoneType' object is not subscriptable
```

**Environment (please complete the following information):**
 - label-studio: 1.7.3, 1.8.0 ( see also the linked issue)

**Additional context**
see also issue in ml backend:
https://github.com/heartexlabs/label-studio-ml-backend/issues/287

**Comment by hogepodge** [comment]
Thanks @DaMuBo, we're going to dig into this a bit more and see if we can reproduce or find a workaround. I have a feeling this is related to the version of the ML backend API that's being used, but we need to investigate more deeply.

**Comment by dimtsiakm** [comment]
Unfortunately, I have the same issue. I tried also the label-studio's version 1.6.0 with no success.

the kwargs are {'login': None, 'password': None, 'context': None}

**Comment by DimIsaev** [comment]
label studio: "release": "1.8.0",
label-studio-ml-backend  commit  [92afc8c](https://github.com/heartexlabs/label-studio-ml-backend/commit/92afc8c19dd81bf0180c094c78456a05e397024c)

```
[2023-07-18 16:28:35,342] [INFO] [werkzeug::_log::225] 172.31.176.1 - - [18/Jul/2023 16:28:35] "GET /health HTTP/1.1" 200 -
[2023-07-18 16:28:35,516] [INFO] [werkzeug::_log::225] 172.31.176.1 - - [18/Jul/2023 16:28:35] "POST /setup HTTP/1.1" 200 -
the kwargs are {'login': None, 'password': None, 'context': None}
the tasks are [{'id': 3821, 'data': {'image': '/data/local-files/?d=dataset3/CAM01_15-07-2023_15-16-47.jpg'}, 'meta': {}, 'created_at': '2023-07-18T09:09:11.447402Z', 'updated_at': '2023-07-18T09:09:11.447439Z', 'is_labeled': False, 'overlap': 1, 'inner_id': 2, 'total_annotations': 0, 'cancelled_annotations': 0, 'total_predictions': 0, 'comment_count': 0, 'unresolved_comment_count': 0, 'last_comment_updated_at': None, 'project': 3, 'updated_by': None, 'file_upload': None, 'comment_authors': [], 'annotations': [], 'predictions': []}]
[2023-07-18 16:28:35,707] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/label_studio_ml/api.py", line 51, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/user/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 617, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/home/user/label-studio-ml-backend/my_ml_backend/segment_anything_model.py", line 69, in predict
    height = kwargs['context']['result'][0]['original_height']
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/label_studio_ml/api.py", line 51, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/home/user/.local/lib/python3.10/site-packages/label_studio_ml/model.py", line 617, in predict
    predictions = cls._current_model.model.predict(tasks, **kwargs)
  File "/home/user/label-studio-ml-backend/my_ml_backend/segment_anything_model.py", line 69, in predict
    height = kwargs['context']['result'][0]['original_height']
TypeError: 'NoneType' object is not subscriptable

[2023-07-18 16:28:35,708] [INFO] [werkzeug::_log::225] 172.31.176.1 - - [18/Jul/2023 16:28:35] "POST /predict HTTP/1.1" 500 -
```

**Comment by DimIsaev** [comment]
Also  https://github.com/heartexlabs/label-studio-ml-backend/issues/287

?

**Comment by DimIsaev** [comment]
> Thanks @DaMuBo, we're going to dig into this a bit more and see if we can reproduce or find a workaround. I have a feeling this is related to the version of the ML backend API that's being used, but we need to investigate more deeply.

Do you know the approximate time frame for solving the problem?

@hogepodge @makseq

**Comment by dimtsiakm** [comment]
The truth is that after the first attempt that was unsuccessful, the program doesn't stop. After using again the keystrokes (Keypoint and Auto-Detect button) the label-studio-ml-backend is able to provide me with masks. 

Label-Studio version: 1.7.3
label-studio-ml-backend version: latest

**Comment by Francesko90** [comment]
I'm agree with @dimtsiakm 

See https://github.com/HumanSignal/label-studio-ml-backend/issues/294#issuecomment-1651223377

**Comment by DimIsaev** [comment]
without changes
error persisted

the individual setting is incomprehensible, maybe it decides something, but it is necessary that it would work in other conditions
or describe exactly what each setting affects

**Comment by pritamfocal** [comment]
@DimIsaev  did you solve this issue ?

**Comment by hogepodge** [comment]
The `TypeError: 'NoneType' object is not subscriptable` is not fatal, and sometimes happens at the first initialization. I'm working up some additional documentation to help make connecting ML backends easier and clearer, and we're also working on software improvements to the ML backend for a near-future release. Unfortunately I don't have a timeline on these, but I sincerely hear how difficult this has been for everyone and I want to assure you that we're working on a solution.

**Comment by DimIsaev** [comment]
> @DimIsaev did you solve this issue ?

No !
