### ISSUE TITLE
setup.py failing: no such file requirements.txt since 0.7.5

### ISSUE THREAD

**Issue by Zahlii** [heartexlabs/label-studio#453]
```
11:15:13  #8 1.281 Collecting label-studio
11:15:13  #8 1.315   Downloading label-studio-0.7.5-1.tar.gz (10.1 MB)
11:15:14  #8 2.317     ERROR: Command errored out with exit status 1:
11:15:14  #8 2.317      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dnwcebdi/label-studio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dnwcebdi/label-studio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6m8lje95
11:15:14  #8 2.317          cwd: /tmp/pip-install-dnwcebdi/label-studio/
11:15:14  #8 2.317     Complete output (6 lines):
11:15:14  #8 2.317     Label Studio 0.7.5
11:15:14  #8 2.317     Traceback (most recent call last):
11:15:14  #8 2.317       File "<string>", line 1, in <module>
11:15:14  #8 2.317       File "/tmp/pip-install-dnwcebdi/label-studio/setup.py", line 11, in <module>
11:15:14  #8 2.317         with open('requirements.txt') as f:
11:15:14  #8 2.317     FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by makseq** [comment]
What pip version do you use? Try to upgrade to the latest:
```
pip install -U pip 
```

**Comment by Zahlii** [comment]
Happening as part of a Docker build (latest pip installed!). You should be able to reproduce using:

```
FROM python:3.7.3-slim-stretch

RUN apt-get -y update && apt-get install -y git build-essential cargo \
    && pip install --upgrade pip

RUN echo 'manylinux1_compatible = True' > /usr/lib/python3/_manylinux.py \
    && pip install label-studio \
    && rm  /usr/lib/python3/_manylinux.py
```

**Comment by czrcbl** [comment]
Hi, same problema here, using pip 20.2.3:

```
    ERROR: Command errored out with exit status 1:
     command: /home/work/Programs/miniconda3/envs/label-studio/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-12zdr00s/label-studio/setup.py'"'"'; __file__='"'"'/tmp/pip-install-12zdr00s/label-studio/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9tt2xo2k
         cwd: /tmp/pip-install-12zdr00s/label-studio/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-12zdr00s/label-studio/setup.py", line 11, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    Label Studio 0.7.5
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by fromnorthpole** [comment]
Hi, @Zahlii !
Probably you've missed copying requirements.txt inside docker? https://github.com/heartexlabs/label-studio/blob/master/Dockerfile#L7

**Comment by Zahlii** [comment]
> Hi, @Zahlii !
> Probably you've missed copying requirements.txt inside docker? https://github.com/heartexlabs/label-studio/blob/master/Dockerfile#L7

As you can see above, I am not using the Dockerfile provided here; I am simply attempted to install the self-contained pip package. I.e., all I am trying to do is a "pip install label-studio". The Dockerfile I posted above was just to provide a reliable source of reproducing this issue. 
For now, I have pinned label-studio at 0.7.4 until this bug is resolved for our CI pipelines.

**Comment by fromnorthpole** [comment]
@Zahlii, @czrcbl Can you please try using `label-studio==0.7.5.post1` with the same setup?

**Comment by Zahlii** [comment]
> @Zahlii, @czrcbl Can you please try using `label-studio==0.7.5.post1` with the same setup?

pip install "label-studio==0.7.5.post1" worked as expected

**Comment by makseq** [comment]
@Zahlii it's post2 available now, there is fixed some issues with task validation on S3 and GCS.
