### ISSUE TITLE
I encountered an error while migrating from SQLite to MySQL when using the MySQL database. Is it possible to resolve this issue?

### ISSUE THREAD

**Issue by vincent434421** [heartexlabs/label-studio#4543]
**Describe the bug**
When I tried to migrate the database using the "runserver migrate" command, I encountered an issue. My MySQL version is 8.0.33, and it is using the "utf8mb3" encoding. Below is the error message:
```
C:\ProgramData\miniconda3\envs\label-install-local\python.exe C:\Users\xxx\Documents\pythonProject\label-studio-1.1\label-studio\label_studio\manage.py migrate 
=> Database and media directory: C:\Users\xxx\AppData\Local\label-studio\label-studio
=> Static URL is set to: /static/
[Tracing] Create new propagation context: {'trace_id': '2acb0b7776774d83bafdeb83709e6e4a', 'span_id': 'ad7609c863cfd1b7', 'parent_span_id': None, 'dynamic_sampling_context': None}
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /pypi/label-studio/json HTTP/1.1" 200 57083
Can't read version file: ls-version_.py. Fall back to: version_.py
Can't read version file: version_.py
[2023-07-19 21:13:51,337] [root::_read_py::61] [WARNING] Can't read version file: ls-version_.py. Fall back to: version_.py
[2023-07-19 21:13:51,338] [root::_read_py::67] [WARNING] Can't read version file: version_.py
[2023-07-19 21:13:51,441] [root::_read_py::61] [WARNING] Can't read version file: ls-version_.py. Fall back to: version_.py
[2023-07-19 21:13:51,442] [root::_read_py::67] [WARNING] Can't read version file: version_.py
System check identified some issues:

WARNINGS:
organizations.Organization.token: (mysql.W003) MySQL may not allow unique CharFields to have a max_length > 255.
	HINT: See: https://docs.djangoproject.com/en/3.2/ref/databases/#mysql-character-fields
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, core, data_export, data_import, data_manager, django_rq, io_storages, labels_manager, ml, organizations, projects, sessions, tasks, users, webhooks
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying users.0001_squashed_0009_auto_20210219_1237... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying organizations.0001_squashed_0008_auto_20201005_1552... OK
  Applying projects.0001_squashed_0065_auto_20210223_2014... OK
  Applying projects.0002_auto_20210304_1457... OK
  Applying projects.0003_project_color... OK
  Applying projects.0004_auto_20210306_0506... OK
  Applying projects.0003_auto_20210305_1008... OK
  Applying projects.0005_merge_20210308_1141... OK
  Applying projects.0006_auto_20210308_1559... OK
  Applying projects.0007_auto_20210309_1304... OK
  Applying projects.0008_auto_20210314_1840... OK
  Applying projects.0009_project_evaluate_predictions_automatically... OK
  Applying projects.0010_auto_20210505_2037... OK
  Applying projects.0011_auto_20210517_2101... OK
  Applying projects.0012_auto_20210906_1323... OK
  Applying projects.0013_project_reveal_preannotations_interactively... OK
  Applying projects.0014_project_parsed_label_config... OK
  Applying projects.0013_project_skip_queue... OK
  Applying projects.0015_merge_20220117_0749... OK
  Applying projects.0016_auto_20220211_2218... OK
  Applying core.0001_initial... OK
  Applying projects.0017_project_pinned_at... OK
  Applying projects.0018_alter_project_control_weights... OK
  Applying projects.0019_labelstreamhistory... OK
  Applying projects.0020_labelstreamhistory_unique_history... OK
  Applying projects.0019_project_project_pinned__a39ccb_idx... OK
  Applying projects.0021_merge_20230215_1943... OK
  Applying organizations.0002_auto_20210310_2044... OK
  Applying organizations.0003_auto_20211010_1339... OK
  Applying data_export.0001_initial... OK
  Applying data_export.0002_auto_20210921_0954... OK
  Applying data_export.0003_auto_20211004_1416... OK
  Applying data_export.0004_auto_20211019_0852... OK
  Applying data_export.0005_auto_20211025_1137... OK
  Applying data_export.0006_convertedformat... OK
  Applying data_export.0007_auto_20230327_1910... OK
  Applying data_export.0008_convertedformat_traceback... OK
  Applying data_export.0009_alter_convertedformat_traceback... OK
  Applying data_export.0010_alter_convertedformat_export_type... OK
  Applying data_import.0001_initial... OK
  Applying data_import.0002_alter_fileupload_file... OK
  Applying tasks.0001_squashed_0041_taskcompletionhistory_was_cancelled... OK
  Applying tasks.0002_auto_20210305_2035... OK
  Applying io_storages.0001_squashed_0002_auto_20210302_1827... OK
  Applying tasks.0002_auto_20210304_1423... OK
  Applying tasks.0003_merge_20210308_1141... OK
  Applying tasks.0004_auto_20210308_1559... OK
  Applying tasks.0005_auto_20210309_1239... OK
  Applying tasks.0006_remove_annotation_state... OK
  Applying tasks.0007_auto_20210618_1653... OK
  Applying tasks.0008_auto_20210903_1332... OK
  Applying tasks.0009_auto_20210914_0020... OK
  Applying tasks.0010_auto_20210914_0032... OK
  Applying tasks.0009_auto_20210913_0739... OK
  Applying tasks.0011_merge_20210914_1036... OK
  Applying tasks.0012_auto_20211010_1339... OK
  Applying tasks.0013_task_updated_by... OK
  Applying tasks.0014_task_inner_id... OK
  Applying tasks.0015_task_fill_inner_id... OK
  Applying tasks.0016_auto_20220414_1408... OK
  Applying tasks.0017_auto_20220330_1310... OK
  Applying tasks.0018_manual_migrate_counters... OK
  Applying tasks.0017_new_index_anno_result... OK
  Applying tasks.0019_merge_20220512_2038... OK
  Applying tasks.0020_auto_20220515_2332... OK
  Applying tasks.0021_auto_20220515_2358... OK
  Applying tasks.0020_auto_20220516_0545... OK
  Applying tasks.0022_merge_20220517_1128... OK
  Applying tasks.0023_auto_20220620_1007... OK
  Applying data_manager.0001_squashed_0005_view_user... OK
  Applying data_manager.0002_remove_annotations_ids... OK
  Applying data_manager.0003_remove_predictions_model_versions... OK
  Applying data_manager.0004_remove_avg_lead_time... OK
  Applying data_manager.0005_remove_updated_by... OK
  Applying data_manager.0006_remove_inner_id... OK
  Applying data_manager.0007_auto_20220708_0832... OK
  Applying data_manager.0008_manual_counters_update... OK
  Applying data_manager.0009_alter_view_user... OK
  Applying django_rq.0001_initial... OK
  Applying io_storages.0002_auto_20210311_0530... OK
  Applying io_storages.0003_localfilesimportstorage... OK
  Applying io_storages.0004_gcsstoragemixin_google_application_credentials... OK
  Applying io_storages.0005_s3importstorage_recursive_scan... OK
  Applying io_storages.0006_auto_20210906_1323... OK
  Applying io_storages.0007_auto_20210928_1252... OK
  Applying io_storages.0008_auto_20211129_1132... OK
  Applying io_storages.0009_auto_20220310_0922... OK
  Applying io_storages.0010_auto_20221014_1708... OK
  Applying io_storages.0011_gcsstoragemixin_google_project_id... OK
  Applying io_storages.0012_auto_20230418_1510... OK
  Applying io_storages.0013_auto_20230420_0259... OK
  Applying io_storages.0014_init_statuses... OK
  Applying labels_manager.0001_initial...Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xxx\Documents\pythonProject\label-studio-1.1\label-studio\label_studio\manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\core\management\commands\migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\migrations\executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\migrations\migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\migrations\operations\models.py", line 858, in database_forwards
    schema_editor.add_constraint(model, self.constraint)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\base\schema.py", line 397, in add_constraint
    self.execute(sql, params=None)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\base\schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\sentry_sdk\integrations\django\__init__.py", line 616, in execute
    return real_execute(self, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\utils.py", line 82, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
  File "C:\ProgramData\miniconda3\envs\label-install-local\Lib\site-packages\MySQLdb\connections.py", line 255, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1071, 'Specified key was too long; max key length is 3072 bytes')
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit

Process finished with exit code 1

``` 
**To Reproduce**

1. Configuring MySQL in Django.
2. Running the "runserver migrate" command.
3. The error is as mentioned above.

**Expected behavior**
I hope to successfully migrate to MySQL.

**Screenshots**

**Environment (please complete the following information):**
 - OS: window11
 - Label Studio Version : 1.8.2dev

**Additional context**
null

**Comment by hogepodge** [comment]
MySQL isn't a supported database configuration. Currently Label Studio supports Postgres and SQLite.
https://labelstud.io/guide/storedata.html

**Comment by 984958198** [comment]
```
migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('title', 'organization'), name='unique_title'),
        ),
        
migrations.RemoveIndex(
            model_name='annotation',
            name='task_comple_last_cr_dedad7_idx',
        ),
```
V1.8 successfully deleted these two paragraphs in MySQL
The first paragraph cannot add a combined unique index, please manually add it
Delete the index in the second paragraph because it does not exist

**There are also some grammar issues that are not compatible when using**

**Comment by hogepodge** [comment]
I'm sorry @984958198, but Label Studio doesn't support MySQL. Label Studio supports Postgres and SQLite, and support for MySQL isn't on the roadmap.
