### ISSUE TITLE
Persistent Storage in Label Studio Hugging Face space

### ISSUE THREAD

**Issue by erinmikailstaples** [heartexlabs/label-studio#4548]
**Is your feature request related to a problem? Please describe.**
Hello, I'm trying to run label studio in a huggingface space and to use storage from my external cloud provider (google cloud) so that data can persist between space restarts. The [documentation](https://labelstud.io/blog/introduction-to-label-studio-in-hugging-face-spaces/#attaching-cloud-storage-for-permanent-data-hosting) suggests that to do so I must use postgres. Postgres setup is a big overhead for my small scale project, so please can anybody advise if it is possible to use label studio in a huggingface space with external cloud storage and with the default sqllite DB persistence? (I also documented my question in the huggingface discourse site: https://discuss.huggingface.co/t/configuring-cloud-storage-for-label-studio-enable-use-of-sqllite/46590).

**Describe the solution you'd like**
The ability to use Google Cloud Storage or other external storage when it comes to the Label Studio Hugging Face Space.

**Describe alternatives you've considered**

**Additional context**

**Comment by erinmikailstaples** [comment]
This is now resolved! 

Thank you @hogepodge for your work getting this across the line! 

Blog link here: https://labelstud.io/blog/kickstart-your-label-studio-annotation-project-on-hugging-face-spaces/

**Comment by pietz** [comment]
I'm getting this error once i set the base data path:

```
Initializing database..
Traceback (most recent call last):
  File "/usr/local/bin/label-studio", line 33, in <module>
    sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
  File "/label-studio/label_studio/server.py", line 297, in main
    _apply_database_migrations()
  File "/label-studio/label_studio/server.py", line 67, in _apply_database_migrations
    call_command('migrate', '--no-color', verbosity=0)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/migration.py", line 116, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/operations/fields.py", line 222, in state_forwards
    model_state = state.models[app_label, self.model_name_lower]
KeyError: ('tasks', 'task')
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
```
