### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by eastwing27** [heartexlabs/label-studio#4671]
**Describe the bug**
We have LS deployed to Heroku and used to update it from the repo fork. But after the latest update the app just crashes. We tried to create the instance afresh with "Deploy to Heroku" button [here](https://github.com/HumanSignal/label-studio#deploy-in-a-cloud-instance), but the error is still there.

**To Reproduce**
1. Deploy the app to Heroky
2. Run it

**Expected behavior**
SL is up and running

**Additional context**
Here are Heroku logs:
```

2023-08-22T11:49:38.529551+00:00 app[api]: Initial release by user [redacted]
2023-08-22T11:49:38.529551+00:00 app[api]: Release v1 created by user [redacted]
2023-08-22T11:49:38.766920+00:00 app[api]: Release v2 created by user [redacted]
2023-08-22T11:49:38.766920+00:00 app[api]: Enable Logplex by user [redacted]
2023-08-22T11:49:50.310354+00:00 app[api]: Stack changed from heroku-22 to container by user [redacted]
2023-08-22T11:49:50.325768+00:00 app[api]: Release v3 created by user [redacted]
2023-08-22T11:49:50.325768+00:00 app[api]: Upgrade stack to container by user [redacted]
2023-08-22T11:49:50.496113+00:00 app[api]: Set DISABLE_SIGNUP_WITHOUT_LINK, USERNAME, PASSWORD config vars by user [redacted]
2023-08-22T11:49:50.496113+00:00 app[api]: Release v4 created by user [redacted]
2023-08-22T11:49:51.055268+00:00 app[api]: Attach DATABASE (@ref:postgresql-crystalline-90219) by user [redacted]
2023-08-22T11:49:51.055268+00:00 app[api]: Running release v5 commands by user [redacted]
2023-08-22T11:49:51.066522+00:00 app[api]: Release v6 created by user [redacted]
2023-08-22T11:49:51.066522+00:00 app[api]: @ref:postgresql-crystalline-90219 completed provisioning, setting DATABASE_URL. by user [redacted]
2023-08-22T11:49:52.000000+00:00 app[api]: Build started by user [redacted]
2023-08-22T11:52:29.000000+00:00 app[api]: Build succeeded
2023-08-22T11:52:29.586290+00:00 app[api]: Deployed web (5d2971e11b66) by user [redacted]
2023-08-22T11:52:29.586290+00:00 app[api]: Release v7 created by user [redacted]
2023-08-22T11:52:29.605406+00:00 app[api]: Scaled to web@1:Eco by user [redacted]
2023-08-22T11:52:43.430198+00:00 heroku[web.1]: Starting process with command `/bin/sh -c ./deploy/heroku_run.sh`
2023-08-22T11:52:44.265118+00:00 app[web.1]: Traceback (most recent call last):
2023-08-22T11:52:44.265146+00:00 app[web.1]: File "/usr/local/bin/label-studio", line 33, in <module>
2023-08-22T11:52:44.265198+00:00 app[web.1]: sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
2023-08-22T11:52:44.265212+00:00 app[web.1]: File "/usr/local/bin/label-studio", line 25, in importlib_load_entry_point
2023-08-22T11:52:44.265263+00:00 app[web.1]: return next(matches).load()
2023-08-22T11:52:44.265276+00:00 app[web.1]: File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
2023-08-22T11:52:44.265361+00:00 app[web.1]: module = import_module(match.group('module'))
2023-08-22T11:52:44.265376+00:00 app[web.1]: File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-08-22T11:52:44.265462+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-08-22T11:52:44.265475+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-08-22T11:52:44.265584+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-08-22T11:52:44.265617+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-08-22T11:52:44.265648+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-08-22T11:52:44.265681+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-08-22T11:52:44.265747+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-08-22T11:52:44.265778+00:00 app[web.1]: File "/label-studio/label_studio/server.py", line 28, in <module>
2023-08-22T11:52:44.265829+00:00 app[web.1]: from label_studio.core.argparser import parse_input_args
2023-08-22T11:52:44.265842+00:00 app[web.1]: File "/label-studio/label_studio/core/argparser.py", line 6, in <module>
2023-08-22T11:52:44.265885+00:00 app[web.1]: from .settings.base import EXPORT_DIR
2023-08-22T11:52:44.265898+00:00 app[web.1]: File "/label-studio/label_studio/core/settings/base.py", line 77, in <module>
2023-08-22T11:52:44.265947+00:00 app[web.1]: from label_studio.core.utils.io import get_data_dir
2023-08-22T11:52:44.265960+00:00 app[web.1]: File "/label-studio/label_studio/core/utils/io.py", line 6, in <module>
2023-08-22T11:52:44.266004+00:00 app[web.1]: import pkg_resources
2023-08-22T11:52:44.266026+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3260, in <module>
2023-08-22T11:52:44.266391+00:00 app[web.1]: def _initialize_master_working_set():
2023-08-22T11:52:44.266403+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
2023-08-22T11:52:44.266759+00:00 app[web.1]: f(*args, **kwargs)
2023-08-22T11:52:44.266772+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
2023-08-22T11:52:44.267116+00:00 app[web.1]: working_set = WorkingSet._build_master()
2023-08-22T11:52:44.267128+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 572, in _build_master
2023-08-22T11:52:44.267222+00:00 app[web.1]: ws = cls()
2023-08-22T11:52:44.267234+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 565, in __init__
2023-08-22T11:52:44.267318+00:00 app[web.1]: self.add_entry(entry)
2023-08-22T11:52:44.267331+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 621, in add_entry
2023-08-22T11:52:44.267429+00:00 app[web.1]: for dist in find_distributions(entry, True):
2023-08-22T11:52:44.267443+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2096, in find_on_path
2023-08-22T11:52:44.267676+00:00 app[web.1]: for dist in factory(fullpath):
2023-08-22T11:52:44.267690+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2161, in distributions_from_metadata
2023-08-22T11:52:44.267924+00:00 app[web.1]: yield Distribution.from_location(
2023-08-22T11:52:44.267937+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2612, in from_location
2023-08-22T11:52:44.268225+00:00 app[web.1]: )._reload_version()
2023-08-22T11:52:44.268236+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3010, in _reload_version
2023-08-22T11:52:44.268558+00:00 app[web.1]: md_version = self._get_version()
2023-08-22T11:52:44.268570+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2791, in _get_version
2023-08-22T11:52:44.268872+00:00 app[web.1]: version = _version_from_file(lines)
2023-08-22T11:52:44.268884+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2575, in _version_from_file
2023-08-22T11:52:44.269180+00:00 app[web.1]: line = next(iter(version_lines), '')
2023-08-22T11:52:44.269191+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2786, in _get_metadata
2023-08-22T11:52:44.269498+00:00 app[web.1]: for line in self.get_metadata_lines(name):
2023-08-22T11:52:44.269511+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1930, in get_metadata_lines
2023-08-22T11:52:44.269742+00:00 app[web.1]: return yield_lines(self.get_metadata(name))
2023-08-22T11:52:44.269755+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1917, in get_metadata
2023-08-22T11:52:44.269988+00:00 app[web.1]: with io.open(self.path, encoding='utf-8', errors="replace") as f:
2023-08-22T11:52:44.270035+00:00 app[web.1]: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/.wh.wheel-0.37.1.egg-info'
2023-08-22T11:52:44.360309+00:00 heroku[web.1]: Process exited with status 1
2023-08-22T11:52:44.387591+00:00 heroku[web.1]: State changed from starting to crashed
2023-08-22T11:52:44.390531+00:00 heroku[web.1]: State changed from crashed to starting
2023-08-22T11:52:45.624451+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=[redacted]-ea9e14b2a7e5.herokuapp.com request_id=4a17d5f7-c2ca-4384-a2e8-2ee1d58c7d92 fwd="94.237.111.5" dyno= connect= service= status=503 bytes= protocol=https
2023-08-22T11:52:56.444158+00:00 heroku[web.1]: Starting process with command `/bin/sh -c ./deploy/heroku_run.sh`
2023-08-22T11:52:57.216602+00:00 app[web.1]: Traceback (most recent call last):
2023-08-22T11:52:57.216637+00:00 app[web.1]: File "/usr/local/bin/label-studio", line 33, in <module>
2023-08-22T11:52:57.216671+00:00 app[web.1]: sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
2023-08-22T11:52:57.216678+00:00 app[web.1]: File "/usr/local/bin/label-studio", line 25, in importlib_load_entry_point
2023-08-22T11:52:57.216711+00:00 app[web.1]: return next(matches).load()
2023-08-22T11:52:57.216725+00:00 app[web.1]: File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
2023-08-22T11:52:57.216775+00:00 app[web.1]: module = import_module(match.group('module'))
2023-08-22T11:52:57.216790+00:00 app[web.1]: File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-08-22T11:52:57.216834+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2023-08-22T11:52:57.216835+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-08-22T11:52:57.216956+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-08-22T11:52:57.216983+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-08-22T11:52:57.217014+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-08-22T11:52:57.217041+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-08-22T11:52:57.217110+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-08-22T11:52:57.217140+00:00 app[web.1]: File "/label-studio/label_studio/server.py", line 28, in <module>
2023-08-22T11:52:57.217183+00:00 app[web.1]: from label_studio.core.argparser import parse_input_args
2023-08-22T11:52:57.217186+00:00 app[web.1]: File "/label-studio/label_studio/core/argparser.py", line 6, in <module>
2023-08-22T11:52:57.217229+00:00 app[web.1]: from .settings.base import EXPORT_DIR
2023-08-22T11:52:57.217239+00:00 app[web.1]: File "/label-studio/label_studio/core/settings/base.py", line 77, in <module>
2023-08-22T11:52:57.217282+00:00 app[web.1]: from label_studio.core.utils.io import get_data_dir
2023-08-22T11:52:57.217290+00:00 app[web.1]: File "/label-studio/label_studio/core/utils/io.py", line 6, in <module>
2023-08-22T11:52:57.217319+00:00 app[web.1]: import pkg_resources
2023-08-22T11:52:57.217332+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3260, in <module>
2023-08-22T11:52:57.217690+00:00 app[web.1]: def _initialize_master_working_set():
2023-08-22T11:52:57.217691+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
2023-08-22T11:52:57.218025+00:00 app[web.1]: f(*args, **kwargs)
2023-08-22T11:52:57.218036+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
2023-08-22T11:52:57.218371+00:00 app[web.1]: working_set = WorkingSet._build_master()
2023-08-22T11:52:57.218373+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 572, in _build_master
2023-08-22T11:52:57.218452+00:00 app[web.1]: ws = cls()
2023-08-22T11:52:57.218455+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 565, in __init__
2023-08-22T11:52:57.218537+00:00 app[web.1]: self.add_entry(entry)
2023-08-22T11:52:57.218545+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 621, in add_entry
2023-08-22T11:52:57.218630+00:00 app[web.1]: for dist in find_distributions(entry, True):
2023-08-22T11:52:57.218632+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2096, in find_on_path
2023-08-22T11:52:57.218849+00:00 app[web.1]: for dist in factory(fullpath):
2023-08-22T11:52:57.218860+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2161, in distributions_from_metadata
2023-08-22T11:52:57.219086+00:00 app[web.1]: yield Distribution.from_location(
2023-08-22T11:52:57.219087+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2612, in from_location
2023-08-22T11:52:57.219350+00:00 app[web.1]: )._reload_version()
2023-08-22T11:52:57.219360+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3010, in _reload_version
2023-08-22T11:52:57.219657+00:00 app[web.1]: md_version = self._get_version()
2023-08-22T11:52:57.219666+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2791, in _get_version
2023-08-22T11:52:57.219940+00:00 app[web.1]: version = _version_from_file(lines)
2023-08-22T11:52:57.219948+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2575, in _version_from_file
2023-08-22T11:52:57.220236+00:00 app[web.1]: line = next(iter(version_lines), '')
2023-08-22T11:52:57.220244+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2786, in _get_metadata
2023-08-22T11:52:57.220527+00:00 app[web.1]: for line in self.get_metadata_lines(name):
2023-08-22T11:52:57.220539+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1930, in get_metadata_lines
2023-08-22T11:52:57.220740+00:00 app[web.1]: return yield_lines(self.get_metadata(name))
2023-08-22T11:52:57.220748+00:00 app[web.1]: File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1917, in get_metadata
2023-08-22T11:52:57.220951+00:00 app[web.1]: with io.open(self.path, encoding='utf-8', errors="replace") as f:
2023-08-22T11:52:57.220997+00:00 app[web.1]: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3/dist-packages/.wh.wheel-0.37.1.egg-info'
2023-08-22T11:52:57.346174+00:00 heroku[web.1]: Process exited with status 1
2023-08-22T11:52:57.370783+00:00 heroku[web.1]: State changed from starting to crashed
2023-08-22T11:52:58.200559+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=[redacted]-ea9e14b2a7e5.herokuapp.com request_id=10f636ce-c879-493f-9ef4-3dcc55e06f47 fwd="94.237.111.5" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by upunaprosk** [comment]
#4387

**Comment by farioas** [comment]
The issue has been resolved, please try to click on the button again.
