### ISSUE TITLE
Current Docker image v1.8.2 won't run

### ISSUE THREAD

**Issue by CMcCall-Bayer** [heartexlabs/label-studio#4763]
**Describe the bug**
Current Docker image v1.8.2 won't run

**To Reproduce**
1. `sudo docker run -it -p 8080:8080 -v $(pwd)/mydata:/label-studio/data heartexlabs/label-studio:latest`
2. See error:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/label-studio", line 33, in <module>
    sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
  File "/usr/local/bin/label-studio", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/label-studio/label_studio/server.py", line 28, in <module>
    from label_studio.core.argparser import parse_input_args
  File "/label-studio/label_studio/core/argparser.py", line 6, in <module>
    from .settings.base import EXPORT_DIR
  File "/label-studio/label_studio/core/settings/base.py", line 121, in <module>
    SECRET_KEY = generate_secret_key_if_missing(BASE_DATA_DIR)
  File "/label-studio/label_studio/core/utils/secret_key.py", line 25, in generate_secret_key_if_missing
    logger.warning(f'Warning: failed to write {env_key} to .env file: {e}, new key will be regenerated on every server restart. If this key is used for signing, it will invalidate all existing sessions or tokens. Please set {key} in your environment variables to avoid this warning.')
NameError: name 'key' is not defined
```

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - AWS Lightsail

**Additional context**
This commit in develop fixes it: https://github.com/HumanSignal/label-studio/commit/0caeaf01f4b0413332bd0bdcb8db9a4550ae80a8#diff-e0684bf477cfa7a4194f33a298f703291ab27c296fe27b2e7cf1b6f724e5117b
However, this code is not in the current Docker image. The last working Docker image is v1.8.1. Thanks for making this software, I'm a big fan!

**Comment by jombooth** [comment]
Hi @CMcCall-Bayer - thanks for reporting this issue! We've released [1.8.2.post0](https://github.com/HumanSignal/label-studio/releases/tag/1.8.2.post0) with a hotfix for this oversight, and the new image is already [available on Docker Hub](https://hub.docker.com/r/heartexlabs/label-studio/tags).
