### ISSUE TITLE
Cannot Populate `Table` Component Using JSON Fetched From S3

### ISSUE THREAD

**Issue by narolski** [heartexlabs/label-studio#4915]
**Describe the bug**

I would like to populate the contents of the `Table` component using the contents of the JSON file stored in S3 at the address present in the task description.

**To Reproduce**

For `Video` component, the following code shows the video stored at `$video` path from S3:
```
  <Video name="video" value="$video"/>
```
For `Text` component, the following code shows the contents of the JSON stored at the `$json` path from S3:
```
  <Text name="p1" value="$json" valueType="url"/>
```
However, for `Table` component, the following code:
```
  <Table name="text-1" value="$json" valueType="url"></Table>
```
produces the following error in console:
```
VM734:1 Uncaught (in promise) SyntaxError: Unexpected token '/', "/tasks/926"... is not valid JSON
    at JSON.parse (<anonymous>)
    at Table.js:96:63
    at Generator.next (<anonymous>)
    at mobx-state-tree.module.js:3631:51
    at ve (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at q (mobx-state-tree.module.js:2456:16)
    at s (mobx-state-tree.module.js:3617:13)
    at c (mobx-state-tree.module.js:3631:21)
    at i (mobx-state-tree.module.js:3623:17)
    at ve (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at q (mobx-state-tree.module.js:2456:16)
    at mobx-state-tree.module.js:3626:13
    at new Promise (<anonymous>)
    at Object.n (mobx-state-tree.module.js:3619:16)
    at ve (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at q (mobx-state-tree.module.js:2456:16)
    at Object.r (mobx-state-tree.module.js:2483:16)
    at store.js:270:55
    at n (Tree.tsx:310:17)
    at n (Tree.tsx:317:23)
    at Object.We [as traverseTree] (Tree.tsx:324:3)
    at Object.i (store.js:253:12)
    at ve (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at q (mobx-state-tree.module.js:2456:16)
    at Object.r (mobx-state-tree.module.js:2483:16)
    at Object.initializeStore (AppStore.js:660:12)
    at ve (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at q (mobx-state-tree.module.js:2456:16)
    at Object.r (mobx-state-tree.module.js:2483:16)
    at V9 (configureStore.js:38:9)
    at async Y9.createApp (LabelStudio.js:61:20)
```

**Expected behavior**
`Table` component shows contents of JSON file from given URL, as depicted in a documentation.

**Screenshots**
<img width="468" alt="Zrzut ekranu 2023-10-17 o 16 36 18" src="https://github.com/HumanSignal/label-studio/assets/13568442/bde1e6b4-aadd-4041-bd63-df1054ae85f8">

**Environment (please complete the following information):**
 - OS: Chrome 117.0.5938.149 (macOS, `arm`)
 - Label Studio Version: 1.9.1

**Comment by hogepodge** [comment]
Can you share your json file with us? It looks like the json validator is failing. I want to rule out a problem with the original json file.

**Comment by narolski** [comment]
> Can you share your json file with us? It looks like the json validator is failing. I want to rule out a problem with the original json file.

@hogepodge sorry for late reply. Of course! Here's the contents of the `json` file that I'm trying to load in Label Studio `Table` component:

```
{"sex":"man","age":29,"gestureType":"deviceMoving","recordingType":"print","material":"","fixing":"handheld","printHoles":["eyes","mouth"],"screenPictureType":"","screenType":"","email":"","refCode":"","lightningType":"lightningNatural","localizationType":"outdoor","printFolds":"flat","challenge":"zoomout"}
```

and here is the task `json` for Label Studio:
```
{"video": "s3://<S3_PATH_GOES_HERE>/002168f5-45f5-454f-becc-4b6af9dfc080/1692794109874.mp4", "json": "s3://<S3_PATH_GOES_HERE>/002168f5-45f5-454f-becc-4b6af9dfc080/fzV_wLuPRbyUAOaK7wSQFg.json"}
```

JSON file:

[fzV_wLuPRbyUAOaK7wSQFg.json](https://github.com/HumanSignal/label-studio/files/13251277/fzV_wLuPRbyUAOaK7wSQFg.json)
