### ISSUE TITLE
Running with docker errors out with permission error

### ISSUE THREAD

**Issue by rogusdev** [heartexlabs/label-studio#4942]
**Describe the bug**
I followed the instructions from the README (I changed the local data dir name):
```
mkdir label-studio-data
docker pull heartexlabs/label-studio:latest
docker run -it -p 8080:8080 -v $(pwd)/label-studio-data:/label-studio/data heartexlabs/label-studio:latest
```

But I get this error
```
> docker run -it -p 8080:8080 -v $(pwd)/label-studio-data:/label-studio/data heartexlabs/label-studio:latest
=> Database and media directory: /label-studio/data
=> Static URL is set to: /static/
Traceback (most recent call last):
  File "/usr/local/bin/label-studio", line 33, in <module>
    sys.exit(load_entry_point('label-studio', 'console_scripts', 'label-studio')())
  File "/usr/local/bin/label-studio", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/label-studio/label_studio/server.py", line 28, in <module>
    from label_studio.core.argparser import parse_input_args
  File "/label-studio/label_studio/core/argparser.py", line 5, in <module>
    from .settings.base import EXPORT_DIR
  File "/label-studio/label_studio/core/settings/base.py", line 399, in <module>
    os.makedirs(MEDIA_ROOT, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/label-studio/data/media'
```

**To Reproduce**
Docker pull + run, copy-pasted from the README.

**Expected behavior**
I expect it to not error out

**Environment (please complete the following information):**
 - OS: Win11 WSL2
 - Label Studio Version -- whatever docker latest is as of 2023-10-21

Thanks!

**Comment by hogepodge** [comment]
You will need to adjust the permissions for the image you are mounting for Docker to be able to read it. The installation instructions for Docker includes information how to do this.

https://labelstud.io/guide/install.html#Install-with-Docker

"As this is a non-root container, the mounted files and directories must have the proper permissions for the UID 1001."

I'll also take this to our docs team as something we can improve the documentation of.

**Comment by hogepodge** [comment]
We also have an internal ticket to improve how Docker works with storage, and will also update this issue once it's been improved.

**Comment by rogusdev** [comment]
Thanks. `chmod 666 label-studio-data` was not enough, I needed to give 777, which seems quite extreme. Is there a different recommended way of setting the necessary permissions? Your instructions highlight the specific user id number, are you expecting me to `chown 1001 label-studio-data` instead?

**Comment by Lunatik00** [comment]
> I'll also take this to our docs team as something we can improve the documentation of.

You also need to adjust guides, since in https://labelstud.io/blog/get-started-using-segment-anything/ there are instructions on what command to use and this was not explained in the command, moreover, I am using 1001 and I also got the message, i tried to start it as user 1001 and got the message, finally, since I am ussing it locally and security was not that important to test something at this point, I just went ahead and chmod 777 the folder inside the container, that was not enough for this to work fine with non root for some reason (it should have been, since the outside folder has the same 1001 user) and just changed everything to root for now, I am going to deal with this after, but a simple improvement would be to add the link in the part where the container is used, little reminders on the way are good, since people will skip to the parts they need and not read the whole thing.

**Comment by Red-Eyed** [comment]
For those who faced same issue:
- `docker compose up` (get error)
- `sudo chmod 777 mydata`
- `docker compose up` (no error)

**Comment by lixianglong1205** [comment]
docker run -it -p 8080:8080 -v $(pwd)/mydata:/label-studio/data heartexlabs/label-studio:latest
change $(pwd) >>>  docker run -it -p 8080:8080 -v $/mnt/e/project/label-studio/mydata:/label-studio/data heartexlabs/label-studio:latest
