### ISSUE TITLE
File won't upload on fresh install

### ISSUE THREAD

**Issue by mxchinegod** [heartexlabs/label-studio#5307]
**Describe the bug**
Just getting an error icon on UI when I try to upload a large CSV

**To Reproduce**
1. Try to upload a large CSV

**Expected behavior**
CSV uploads.

**Screenshots**
![Uploading Screenshot 2024-01-18 at 3.03.06 PM.png…]()

**Environment (please complete the following information):**
 - OS: macOS Sonoma
 - Label Studio Version: latest

**Additional context**
```shell
[2024-01-18 20:01:21,607] [django.request::log_response::224] [ERROR] Internal Server Error: /api/projects/3/import
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/django/http/request.py", line 400, in readline
    return self._stream.readline(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 51, in readline
    chunk = self._read_limited()
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 40, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/label_studio/core/middleware.py", line 121, in __call__
    if 'server_id' not in request:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/http/request.py", line 402, in readline
    raise UnreadablePostError(*e.args) from e
django.http.request.UnreadablePostError: [Errno 22] Invalid argument
[2024-01-18 20:01:21,607] [django.request::log_response::224] [ERROR] Internal Server Error: /api/projects/3/import
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/django/http/request.py", line 400, in readline
    return self._stream.readline(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 51, in readline
    chunk = self._read_limited()
            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 40, in read
    result = self.buffer + self._read_limited(size - len(self.buffer))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/label_studio/core/middleware.py", line 121, in __call__
    if 'server_id' not in request:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/django/http/request.py", line 402, in readline
    raise UnreadablePostError(*e.args) from e
django.http.request.UnreadablePostError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/wsgiref/handlers.py", line 196, in finish_response
    self.close()
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/servers/basehttp.py", line 117, in close
    self.get_stdin()._read_limited()
  File "/opt/homebrew/lib/python3.11/site-packages/django/core/handlers/wsgi.py", line 28, in _read_limited
    result = self.stream.read(size)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument
[2024-01-18 20:01:21,610] [django.server::log_message::161] [INFO] code 400, message Bad request syntax ('------WebKitFormBoundarytmq9Xehc0NsRuu34')
[2024-01-18 20:01:21,610] [django.server::log_message::161] [INFO] code 400, message Bad request syntax ('------WebKitFormBoundarytmq9Xehc0NsRuu34')
[2024-01-18 20:01:21,610] [django.server::log_message::161] [WARNING] "------WebKitFormBoundarytmq9Xehc0NsRuu34" 400 -
[2024-01-18 20:01:21,610] [django.server::log_message::161] [WARNING] "------WebKitFormBoundarytmq9Xehc0NsRuu34" 400 -
```

**Comment by hogepodge** [comment]
How large is the CSV file? Django by default has started to limit file upload sizes. You can disable this by overriding these environment variables: 

```
DATA_UPLOAD_MAX_MEMORY_SIZE
DATA_UPLOAD_MAX_NUMBER_FILES
```

**Comment by hogepodge** [comment]
https://github.com/HumanSignal/label-studio/blob/b49f1565c484d42ff7c93daa41d6adf2e15fde03/label_studio/core/settings/base.py#L455C14-L456

**Comment by mxchinegod** [comment]
You don't even want to know how big it is. I'll adjust accordingly. 

Thank you.
