### ISSUE TITLE
Error syncing with S3 on verions 1.10.1 and 1.11.0: ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' 

### ISSUE THREAD

**Issue by gdoermann** [heartexlabs/label-studio#5327]
**Describe the bug**
It looks like s3transfer library is the one that is out of sync.  I have s3transfer version 0.10.0 on my docker build when I exec into the running container. It looks like if i upgrade botocore or boto3 I have no issues with this import.  You have version locks for boto3 and botocore in deploy/requirements.txt:
...
boto~=2.49.0
boto3==1.28.58
botocore==1.31.58

...
There is NO lock on s3transfer but it looks to be installed with other packages. The requirements-test.txt does seem to have a lock:
s3transfer==0.7.0
But this does not end up in the poetry.lock file.

**To Reproduce**
1. Go to 'Project Settings'
2. Click on 'Cloud Storage'
3. Click on 'Add Source Storage'
4. Add a valid/working S3 storage location
5. Click on 'Sync Storage'
6. See error

**Expected behavior**
S3 should sync files in the bucket properly. 

**Traceback**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/io_storages/api.py", line 109, in post
    storage.validate_connection()
  File "/label-studio/label_studio/io_storages/s3/models.py", line 84, in validate_connection
    client = self.get_client()
  File "/label-studio/label_studio/io_storages/s3/models.py", line 72, in get_client
    client, _ = self.get_client_and_resource()
  File "/label-studio/label_studio/io_storages/s3/models.py", line 61, in get_client_and_resource
    result = get_client_and_resource(
  File "/label-studio/label_studio/io_storages/s3/utils.py", line 35, in get_client_and_resource
    client = session.client('s3', config=boto3.session.Config(signature_version='s3v4'), **settings)
  File "/usr/local/lib/python3.10/dist-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/usr/local/lib/python3.10/dist-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 145, in create_client
    )
  File "/usr/local/lib/python3.10/dist-packages/botocore/client.py", line 198, in _create_client_class
    class_attributes['_PY_TO_OP_NAME'] = py_name_to_operation_name
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/boto3/utils.py", line 65, in _handler
    module = import_module(module)
  File "/usr/local/lib/python3.10/dist-packages/boto3/utils.py", line 56, in import_module
    __import__(name)
  File "/usr/local/lib/python3.10/dist-packages/boto3/s3/inject.py", line 18, in <module>
    from boto3.s3.transfer import (
  File "/usr/local/lib/python3.10/dist-packages/boto3/s3/transfer.py", line 134, in <module>
    from s3transfer.futures import NonThreadedExecutor
  File "/usr/local/lib/python3.10/dist-packages/s3transfer/futures.py", line 22, in <module>
    from s3transfer.utils import FunctionContainer, TaskSemaphore
  File "/usr/local/lib/python3.10/dist-packages/s3transfer/utils.py", line 26, in <module>
    from botocore.utils import is_s3express_bucket
ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/usr/local/lib/python3.10/dist-packages/botocore/utils.py)
```

**Environment (please complete the following information):**
 - OS: docker (node:18)
 - Label Studio Version 1.10.1 AND 1.11.0 tested

**Additional context**
I checked the s3transfer library and it is now on version 0.10.0, which requires a newer version of boto3 and botocore.  you either need to pin to s3transfer==0.7.0 or upgrade boto3 and botocore.

**Comment by jombooth** [comment]
Hi @gdoermann,

When setting up your environment for Label Studio, how did you install the dependencies? As I noted in #5328, `requirements.txt` shouldn't be used to install the deps for recent versions of Label Studio, which get their dependencies from `poetry.lock` / `pyproject.toml`. Our QA team checked the most recent versions of LS (`1.10.1` / `1.11.0`) and found that importing from an S3 source storage worked on both.

If you're manually installing your dependencies, I recommend doing so with `poetry`; you can look to `Dockerfile` for some inspiration on how to use it. Feel free to reopen this issue if you're still having trouble with importing from S3!
