### ISSUE TITLE
Fails to delete completion stored on s3

### ISSUE THREAD

**Issue by GiladE** [heartexlabs/label-studio#543]
**Describe the bug**
When trying to delete a `task_completion` that is on s3 it fails with a `NotImplementedError`

**To Reproduce**
Steps to reproduce the behaviour:
1. Have completions target storage set to s3
2. Create a completion for a task
3. Delete the completion

**Expected behavior**
Expect the `task_completion` to be deleted

**Error**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/label_studio/utils/misc.py", line 64, in exception_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/label_studio/blueprint.py", line 786, in api_completion_by_id
    g.project.delete_task_completion(task_id, completion_id)
  File "/usr/local/lib/python3.6/site-packages/label_studio/project.py", line 670, in delete_task_completion
    self.target_storage.remove(task_id)
  File "/usr/local/lib/python3.6/site-packages/label_studio/storage/base.py", line 474, in remove
    raise NotImplementedError
NotImplementedError

[2021-01-13 08:47:25,016] [INFO] [werkzeug::_log::122] 172.17.0.1 - - [13/Jan/2021 08:47:25] "DELETE /api/tasks/0/completions/1001 HTTP/1.1" 500 -
```

**Environment (please complete the following information):**
 - OS: Linux b425d69e6756 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 GNU/Linux
 - Label Studio Version: 0.9.0

**Comment by makseq** [comment]
Label studio doesn't support completion deletion for storages because it could be potentially danger for user data.

**Comment by niklub** [comment]
In general, Label Studio is not intended to fully manage cloud storage - only "List/Read" and "Put" actions are allowed. It's better to rely on storage clients. We won't support this functionality, but I agree that we should better handle that exception at the moment.

**Comment by GiladE** [comment]
Thank you for your responses!! It makes sense that LS doesn't take responsibility for that.
