### ISSUE TITLE
Can not trust custom CA

### ISSUE THREAD

**Issue by mbio16** [heartexlabs/label-studio#5460]
**Describe the bug**
Running OpenShift with own build Docker container. I want to connect to S3 storage with https. S3 storage certificate is issued by third party CA. I followed instructions to import it from: https://labelstud.io/guide/security.html/#Add-self-signed-certificate-to-trusted-root-store.
  
**Dockerfile**
COPY --chown=1001:0 ca_authority/ca.crt /usr/local/share/ca-certificates/ca.crt
COPY --chown=1001:0 ca_authority/ca.crt /opt/heartex/secrets/ca_certs/ca.crt

RUN update-ca-certificates

ENV CUSTOM_CA_CERTS=/opt/heartex/secrets/ca_certs/ca.crt

**Expected behavior**
Be able to add S3 storage. However, I have trust issue with CA issuer. When I call the the from container terminal with curl. Ca is trusted and connection is valid.

**Stack trace error**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:
...
```
**Possible solution**
Is there any other keystore to import CA?

**Comment by mbio16** [comment]
Resolved by boto : opened PR -> https://github.com/HumanSignal/label-studio/pull/5463.

**Comment by makseq** [comment]
Closed as solved.
