### ISSUE TITLE
Video pre-comment import loading

### ISSUE THREAD

**Issue by MMa321** [heartexlabs/label-studio#5737]
When importing the pre-comment, I found that without manually labeling, the pre-comment could not be displayed and the video was always in the loading state. Could you please verify it

![1713339108912](https://github.com/HumanSignal/label-studio/assets/158540059/de51a907-5eab-4b4b-addb-c7d4bc9d33f1)

**Comment by MMa321** [comment]
I tried it again, and to be precise, only the updated task comments will show up in the video

**Comment by makseq** [comment]
What is pre-comment?

**Comment by MMa321** [comment]
Sorry, I'm expressing that wrong, I meant to say pre-annotations

**Comment by makseq** [comment]
You need to check the browser console, there should be errors displayed.

**Comment by MMa321** [comment]
This is a browser error：
store.js:442  Uncaught (in promise) TypeError: e.id.replace is not a function
    at store.js:442:27
    at Array.forEach (<anonymous>)
    at Object.addAnnotationFromPrediction (store.js:440:9)
    at ve (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at q (mobx-state-tree.module.js:2456:16)
    at Object.r (mobx-state-tree.module.js:2483:16)
    at _w.setAnnotation (lsf-sdk.js:456:25)
    at _w.setLSFTask (lsf-sdk.js:379:10)
    at main.js?v=d88e4f:2:1456754
    at Generator.next (<anonymous>)
    at mobx-state-tree.module.js:3631:51
    at Ee (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at io (mobx-state-tree.module.js:2456:16)
    at l (mobx-state-tree.module.js:3617:13)
    at c (mobx-state-tree.module.js:3631:21)

**Comment by MMa321** [comment]
![1713944679111](https://github.com/HumanSignal/label-studio/assets/158540059/7c185ddc-9bff-45d6-a166-47174310137e)
