### ISSUE TITLE
Remove duplicates does not work when importing project

### ISSUE THREAD

**Issue by davidpob99** [heartexlabs/label-studio#5738]
**Describe the bug**
Remove duplicates does not work when exporting project with local storage, changing the data path location, importing it again and sync with the storage again (with old and new images).

**To Reproduce**
1. Export project (object detection) as JSON label-studio format
2. Change file paths in order to update images paths to new location (find and replace in a code editor). Save JSON
3. Import JSON
4. Add source storage (local storage with new location)
5. Sync storage. Will add new tasks that are duplicated with the imported JSON. No problem, will use remove duplicates script
6. Run remove duplicates script, either from `shell` or web interface
7. Error raised:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/data_manager/api.py", line 379, in post
    result = perform_action(action_id, project, queryset, request.user, **kwargs)
  File "/label-studio/label_studio/data_manager/actions/__init__.py", line 117, in perform_action
    raise e
  File "/label-studio/label_studio/data_manager/actions/__init__.py", line 113, in perform_action
    result = action['entry_point'](project, queryset, **kwargs)
  File "/label-studio/label_studio/data_manager/actions/experimental.py", line 113, in remove_duplicates
    link_instance = _class.objects.get(id=source[2])
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
io_storages.localfiles.models.LocalFilesImportStorage.DoesNotExist: LocalFilesImportStorage matching query does not exist.
```

**Expected behavior**
Duplicated tasks should be removed, only saving the previous annotated ones (imported from JSON)

**Environment (please complete the following information):**
 - OS: Docker Hub image label-studio in running in Ubuntu 22.04 host
 - Label Studio Version: tested with `latest` tag (1.11.0) and `develop` tag (1.12.1.dev0)

Thanks in advance!

**Comment by davidpob99** [comment]
Related to #2050 and #5731

**Comment by davidpob99** [comment]
Fixed in https://github.com/HumanSignal/label-studio/pull/5758. Docker tag: `heartexlabs/label-studio:20240419.151443-develop-ff7105f39`
