### ISSUE TITLE
Linking From External Site Does Not Load

### ISSUE THREAD

**Issue by dennism0027** [heartexlabs/label-studio#5805]
**Describe the bug**

We are linking to a task from an external application to allow alternative ways of selecting tasks. This does seem to cause some issue in Label Studio where the task just hangs on loading. One workaround found was selecting a different task and then going back to the task on the previous page. 

**To Reproduce**

1. Create link in external site
2. Click the link to Label Studio
3. Wait for task to load

**Expected behavior**

Expected behavior would be for the task to load

**Screenshots**

https://github.com/HumanSignal/label-studio/assets/33007602/13e9e198-10a3-4a34-b9e0-bdd95f8e81ab

**Environment (please complete the following information):**
 - OS: ubuntu-focal-20.04-amd64-server-20240321
 - Label Studio Version - "release": "1.5.0"

**Additional context**

Here is the the error from console that may be the source of the bug
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'currentAnnotation')
    at AppStore.js:210:37
    at Generator.next (<anonymous>)
    at mobx-state-tree.module.js:3631:51
    at Qe (mobx.module.js:928:19)
    at r (mobx.module.js:915:16)
    at mobx-state-tree.module.js:2593:35
    at to (mobx-state-tree.module.js:2456:16)
    at l (mobx-state-tree.module.js:3617:13)
    at u (mobx-state-tree.module.js:3631:21)
```

**Comment by sajarin** [comment]
/jira create
> [Workflow run](https://github.com/HumanSignal/label-studio/actions/runs/8913784168)
> Jira issue [TRIAG-525](https://humansignal.atlassian.net/browse/TRIAG-525) is created

[TRIAG-525]: https://humansignal.atlassian.net/browse/TRIAG-525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by dennism0027** [comment]
Any updates on this?
