### ISSUE TITLE
Syncing External Storage lead to Gateway Timeout 

### ISSUE THREAD

**Issue by haiminh2001** [heartexlabs/label-studio#5890]
**Describe the bug**
I deployed Label Studio on out internal K8s cluster using the official helm-chart (version 14.0.10). When I sync data storage (a minio cluster on the same k8s cluster) which contains about 1000 json file which represent 1000 tasks (the data is a uri to the minio cluster). After a while, the Gateway Timeout error and occasionally, "in time progress" error pop up, the sync request is not converted in "Failed" status but get stuck in "Queued" status and the project is completely frozen, I cannot do anything without syncing.

**To Reproduce**
1. Go to Project Settings / Cloud Storage
2. Click on "Sync Storage"
3. Gateway Timeout / In time progress
4. Sync task is Failed/Queued

**Expected behavior**
The sync is executed background, there is no need to immediately return the sync task's result.

**Environment (please complete the following information):**
 - Kubernetes: v1.26.10
 - Label Studio Helm Chart version 14.0.10

**Additional context**
This question may be out of context. But I am having issue with performance of Label Studio, the UI is quite lag and syncing data consistently gives me error as in this issue. How can I scale up my Label Studio on K8s and what should I scale up ? The hardware resource is not really my concern.

**Comment by makseq** [comment]
What do you have in these json files? Are they big? 

Label Studio Community doesn't have background workers and all background processes are running on wsgi web workers, so time is limited to 90 seconds for them.

**Comment by haiminh2001** [comment]
> What do you have in these json files? Are they big?
> 
> Label Studio Community doesn't have background workers and all background processes are running on wsgi web workers, so time is limited to 90 seconds for them.

Hi @makseq , thank you for your fast response. The json files are small. They only contains the URI links of the images and the classification labels.

**Comment by makseq** [comment]
You can try setting
```
UWSGI_WORKER_HARAKIRI=0
```
to avoid timeout.

**Comment by haiminh2001** [comment]
> harakiri
> A feature of uWSGI that aborts workers that are serving requests for an excessively long time. Configured using the harakiri family of options. Every request that will take longer than the seconds specified in the harakiri timeout will be dropped and the corresponding worker recycled.

Hmm so this means it will disable not only syncing but every other requests timeout, won't it ? If so it is a little bit dangerous. As I mention, I have the resources to scale up (CPU and memory), can scaling up be the solution?

**Update:** After setting the UWSGI_WORKER_HARAKIRI = 0 in the environment variables, I still get the Gateway Timeout. Is it supposed to be set in the environment variables ?

**Comment by haiminh2001** [comment]
```
Traceback (most recent call last):
  File "/label-studio/label_studio/./io_storages/base_models.py", line 456, in sync
    import_sync_background(self.__class__, self.id)
  File "/label-studio/label_studio/./io_storages/base_models.py", line 485, in import_sync_background
    storage.scan_and_create_links()
  File "/label-studio/label_studio/./io_storages/s3/models.py", line 148, in scan_and_create_links
    return self._scan_and_create_links(S3ImportStorageLink)
  File "/label-studio/label_studio/./io_storages/base_models.py", line 364, in _scan_and_create_links
    self.info_set_in_progress()
  File "/label-studio/label_studio/./io_storages/base_models.py", line 85, in info_set_in_progress
    raise ValueError(f'Storage status ({self.status}) must be QUEUED to move it IN_PROGRESS')
ValueError: Storage status (initialized) must be QUEUED to move it IN_PROGRESS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/label-studio/label_studio/./io_storages/api.py", line 110, in post
    storage.sync()
  File "/label-studio/label_studio/./io_storages/base_models.py", line 458, in sync
    storage_background_failure(self)
  File "/label-studio/label_studio/./io_storages/base_models.py", line 515, in storage_background_failure
    storage.info_set_failed()
  File "/label-studio/label_studio/./io_storages/base_models.py", line 117, in info_set_failed
    self.meta['duration'] = (time_failure - self.time_in_progress).total_seconds()
  File "/label-studio/label_studio/./io_storages/base_models.py", line 96, in time_in_progress
    return datetime.fromisoformat(self.meta['time_in_progress'])
KeyError: 'time_in_progress'
```
I just ran into the "time in progress" error while syncing again, here is the stack trace, hope it will help.

**Comment by makseq** [comment]
> Hmm so this means it will disable not only syncing but every other requests timeout, won't it ? If so it is a little bit dangerous. As I mention, I have the resources to scale up (CPU and memory), can scaling up be the solution?

Correct, it may eat all your resources. 

> Update: After setting the UWSGI_WORKER_HARAKIRI = 0 in the environment variables, I still get the Gateway Timeout. Is it supposed to be set in the environment variables ?

Probably you have some balancers like nginx and they throw timeouts.

**Comment by sajarin** [comment]
@haiminh2001 were you able to get the syncing to external storage working without the gateway timeouts?

**Comment by haiminh2001** [comment]
> @haiminh2001 were you able to get the syncing to external storage working without the gateway timeouts? 

No, I have not. Syncing storage is terribly slow that my approach is to keep my folders in minio storage having no more than 1000 tasks.

**Comment by WillieMaddox** [comment]
I ran into this problem about a year ago when my project grew to over a few thousand tasks.  Here is how I increased the timeout.

In `deploy/uwsgi.ini`, replace this line:
```ini
http-timeout = 300
```
with this,
```ini
if-env = UWSGI_HTTP_TIMEOUT
http-timeout = $(UWSGI_HTTP_TIMEOUT)
endif =
if-not-env = UWSGI_HTTP_TIMEOUT
http-timeout = 300
endif =
```

In `deploy/default.conf`, set `proxy_read_timeout` to whatever you want the timeout to be (for this example I'll use 180):
```conf
        proxy_read_timeout 180;
```

Add the following lines to the `docker-compose.yml`:
```yml
services:

  nginx:
    volumes:
      - ./deploy/default.conf:/etc/nginx/nginx.conf

  app:
    environment:
      - UWSGI_HTTP_TIMEOUT=180
      - UWSGI_WORKER_HARAKIRI=181
    volumes:
      - ./deploy/uwsgi.ini:/label-studio/deploy/uwsgi.ini
```
Set `UWSGI_HTTP_TIMEOUT` equal to `proxy_read_timeout` in `deploy/default.conf`, and set the `UWSGI_WORKER_HARAKIRI` to whatever that number is plus 1.  The changes should take effect the next time you run `docker compose up`.

**Comment by haiminh2001** [comment]
@WillieMaddox thank you so much. I'll give it a try.

**Comment by ieddu** [comment]
Thank you very much @WillieMaddox , It worked well for me.

**Comment by khoapham2801** [comment]
Any update on this? 
I tried @WillieMaddox 's approach but no effect whatsoever.
Dev team [claimed](https://github.com/HumanSignal/label-studio/issues/6831#issuecomment-2564968016) that storage syncing for heavy projects is only supported in enterprise version.

**Comment by sbatchelder** [comment]
Hi All, 
I worked around this limitation by using the LabelStudio API to create an arbitrarily large number of tasks. 
So instead of using the "Source Cloud Storage" Sync, you have a script create each task one-by-one. It's about as fast as "Source Cloud Storage Sync" though. 

1. Create your bucket with images/files/objects
2. Do not create task json files in those buckets. If you've got these, hold on to them for later to loop over.
3. Add your bucket to LabelStudio Source Cloud Storage as you normally would, verify credentials are correct (Check Connection), but **Do Not Sync**.  I typically add `\\A\\Z` to "File Filter Regex" so it matches "empty strings" ie nothing, to make sure nothing gets synced if the Sync button gets accidentally pressed.
4.  write a script to programmaticaly add tasks to your LS instance. Code below is python, and uses HumanSignal's SDK, but you could use whatever language you're comfortable with and hit your LS instance's html API endpoints directly if you like. 

```
from label_studio_sdk import LabelStudio
bucket = ...  # same bucket as configured for your LS instance's "Source Cloud Storage"
key = ...  # the key of some image/file/object you have saved in bucket
ls_client =  LabelStudio(base_url=..., api_key=...)
task = dict(data={'image':f's3://{bucket}/{key}'})
ls_client.tasks.create(project=project_id, data=task)
```
`task` is pretty much the same thing as what would go in that task json file, so arbitrary content in 'data', annotations/predictions if you gottem. At minimum though, you will need to create one field under 'data' that points to something in your s3 bucket. 

Build your list of task dicts ahead of time, then loop over them with `ls_client.tasks.create(project=project_id, data=task)` in the loop and you get to upload as many as you like. Wrap your loop with `tqdm` for a progressbar ;)

Note: this is not idempotent, so if there's any risk of re-uploading the same tasks / duplicate tasks, I recommend checking whether the object already exists or not. I couldn't figure out how to do this with their sdk, but their API endpoint works so I do `ls_get_filtered_tasks(ls_client, project_id, 'image', f's3://{bucket}/{key}', resolve_uri=False)`
with the below function, and only proceed with making a new task if the returned result is empty `[]` .

```
import requests
def ls_get_filtered_tasks(ls_client, project_id, field, value, operator='equal', fieldtype='String', resolve_uri=False):
    host = ls_client._client_wrapper._base_url
    token = ls_client._client_wrapper._tokens_client._api_key
    url = host + '/api/tasks'  
    headers = {"Content-Type": "application/json", "Authorization": f"Token {token}"}

    filter = {"conjunction": "and",
              "items": [{"filter": f"filter:tasks:data.{field}",
                         "operator": operator,
                         "value": value,
                         "type": fieldtype}]
              }
    query = dict(filters=filter)
    query = json.dumps(query)
    payload = dict(
        project=project_id,
        resolve_uri=resolve_uri,
        query=query
    )
    response = requests.get(url, params=payload, headers=headers)
    if response.status_code!=200:
        raise ValueError(f"Status Code {response.status_code}: {response.json()['detail']}")
    return response.json()['tasks']
```
