### ISSUE TITLE
My COCO dataset JSON file contains empty list of segmentations...

### ISSUE THREAD

**Issue by ajmalrasi** [heartexlabs/label-studio#5898]
My COCO dataset JSON file contains empty list of segmentations...

```
WARNING:root:Segmentation in COCO is experimental
Traceback (most recent call last):
  File "/home/frta/.local/bin/label-studio-converter", line 33, in <module>
    sys.exit(load_entry_point('label-studio-converter', 'console_scripts', 'label-studio-converter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frta/projects/***-pose-estimation/label-studio-converter/label_studio_converter/main.py", line 189, in main
    imports(args)
  File "/home/frta/projects/***-pose-estimation/label-studio-converter/label_studio_converter/main.py", line 171, in imports
    import_coco.convert_coco_to_ls(
  File "/home/frta/projects/***-pose-estimation/label-studio-converter/label_studio_converter/imports/coco.py", line 219, in convert_coco_to_ls
    item = create_segmentation(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/frta/projects/***-pose-estimation/label-studio-converter/label_studio_converter/imports/coco.py", line 54, in create_segmentation
    segmentation = annotation['segmentation'][0]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

_Originally posted by @frippe75 in https://github.com/HumanSignal/label-studio/issues/2806#issuecomment-1792769373_

**Comment by INCMPE** [comment]
If you still have this problem, take a look at this commit:  https://github.com/HumanSignal/label-studio-converter/commit/dec9c58c983b1f0ff2efd49af37e05aa600f4480
Check your `coco.py` file and apply the change yourself, this solved the issue for me.
Cheers

**Comment by sajarin** [comment]
hey @ajmalrasi thanks for making this issue, I'm moving to close this because it's a duplicate as you pointed out but I've reopened the other issue. It would be good to have a single thread of discussion for all issues relating to the same or similar COCO json issues. Feel free to comment there!
