### ISSUE TITLE
sync data error

### ISSUE THREAD

**Issue by 191086** [heartexlabs/label-studio#6039]
Traceback (most recent call last):
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/rest_framework/generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/label_studio/ml/api.py", line 83, in get_queryset
    ml_backends = project.update_ml_backends_state()
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/label_studio/projects/models.py", line 966, in update_ml_backends_state
    mlb.update_state()
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/label_studio/ml/models.py", line 220, in update_state
    self.save()
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/label_studio/ml/models.py", line 155, in save
    super().save(*args, **kwargs)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/base.py", line 858, in _save_table
    updated = self._do_update(base_qs, using, pk_val, values, update_fields,
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/sentry_sdk/utils.py", line 1713, in runner
    return sentry_patched_function(*args, **kwargs)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/sentry_sdk/integrations/django/__init__.py", line 650, in execute
    result = real_execute(self, sql, params)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/amax/Data/wrj/miniconda3/envs/label-studio/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked

**Comment by jombooth** [comment]
Hi @191086 - could you add some more context about this error, and how we can go about reproducing it? Details about your setup would also be helpful.
