### ISSUE TITLE
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by jagan1333** [heartexlabs/label-studio#614]
Unable to import files from GCS bucket, it is able to scan files inside but when I do import it throws error like,
Traceback (most recent call last):
  File "/root/LS/label-studio/label_studio/utils/misc.py", line 64, in exception_f
    return f(*args, **kwargs)
  File "/root/LS/label-studio/label_studio/data_manager/api.py", line 159, in api_project_tab_tasks
    tasks = prepare_tasks(g.project, params)
  File "/root/LS/label-studio/label_studio/data_manager/functions.py", line 554, in prepare_tasks
    tasks, total_tasks = load_tasks(project, params, resolve_uri=False, task_range=task_range)
  File "/root/LS/label-studio/label_studio/data_manager/functions.py", line 361, in load_tasks
    task = load_task(project, i, params, resolve_uri)
  File "/root/LS/label-studio/label_studio/data_manager/functions.py", line 299, in load_task
    source_task = project.source_storage.get(task_id, inplace=True, validate=False)
  File "/root/LS/label-studio/label_studio/storage/base.py", line 320, in get
    raise exc
  File "/root/LS/label-studio/label_studio/storage/base.py", line 316, in get
    data = self.get_data(key, inplace=inplace, validate=validate)
  File "/root/LS/label-studio/label_studio/storage/base.py", line 295, in get_data
    raise Exception(key + ' :: ' + str(e))
Exception: label_studio/images (1).jpg :: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

**Comment by makseq** [comment]
@jagan1333 What files do you store on the bucket? 
There seems you forget to enable checkbox `Treat every bucket object as a resource file (jpg, txt, time-series, etc). If unchecked, Label Studio treats every bucket object as a JSON-formatted task.`

![image](https://user-images.githubusercontent.com/501780/109043271-36435180-76e2-11eb-8033-06e57ac8df2d.png)

**Comment by jagan1333** [comment]
Hi @makseq when I enable checkbox getting following error even though service account has all necessary permissions.

  File "/root/LS/label-studio/label_studio/utils/uri_resolver.py", line 125, in resolve_gs
    return python_cloud_function_get_signed_url(bucket_name, key)
  File "/root/LS/label-studio/label_studio/utils/uri_resolver.py", line 183, in python_cloud_function_get_signed_url
    signed_url = signed_blob_path.generate_signed_url(expires_at_ms, credentials=signing_credentials, version="v4")
  File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 565, in generate_signed_url
    access_token=access_token,
  File "/usr/local/lib/python3.6/site-packages/google/cloud/storage/_signing.py", line 622, in generate_signed_url_v4
    signature_bytes = credentials.sign_bytes(string_to_sign.encode("ascii"))
  File "/usr/local/lib/python3.6/site-packages/google/auth/compute_engine/credentials.py", line 404, in sign_bytes
    return self._signer.sign(message)
  File "/usr/local/lib/python3.6/site-packages/google/auth/iam.py", line 99, in sign
    response = self._make_signing_request(message)
  File "/usr/local/lib/python3.6/site-packages/google/auth/iam.py", line 82, in _make_signing_request
    "Error calling the IAM signBytes API: {}".format(response.data)
google.auth.exceptions.TransportError: Error calling the IAM signBytes API: b'{\n  "error": {\n    "code": 403,\n    "message": "The caller does not have permission",\n    "status": "PERMISSION_DENIED"\n  }\n}\n'

Service account has the following roles assigned:
* Service Account Token Creator
* Storage Admin
* Owner

**Comment by makseq** [comment]
@jagan1333 Sorry for a long answer. We were deeply into the release LS 1.0. Try this new version, I hope it's fixed there.
