### ISSUE TITLE
Auto-Annotation Not Appearing in Label Studio After Configuring Tesseract as ML Backend

### ISSUE THREAD

**Issue by sadek-snoussi** [heartexlabs/label-studio#6219]
**Describe the bug**
After configuring Tesseract as the ML backend for Label Studio, the "Auto-Annotation" option does not appear in the label options within the project data manager.

**To Reproduce**
I followed the steps in a tutorial to configure Tesseract as the ML backend for Label Studio.
Link : https://labelstud.io/blog/interactive-ocr-with-tesseract-and-label-studio/
  1. Set up Label Studio and Tesseract containers, ensuring they are on the same network and can communicate.
  2. Configure the ML Backend connection in Label Studio.
  ![image](https://github.com/user-attachments/assets/863a3eab-dcfb-43ba-810d-b7049dad78c9)
  3. Navigate to the project data manager.
  4. Attempt to access the "Auto-Annotation" option in the labeling interface.
  ![image](https://github.com/user-attachments/assets/7c4d3261-16c3-4724-be53-d0ce88cf0001)

**Expected behavior**
The "Auto-Annotation" option should be available in the label options after correctly setting up the ML backend.

**Screenshots**
![image](https://github.com/user-attachments/assets/ede43b18-cf28-4d66-a1d8-920d40bf182a)

**Environment (please complete the following information):**
 - OS: Win 11
 - Docker Version 27.1.1 - Docker Desktop 4.33.1
 - Label Studio Version 1.13.0

**Additional context**
Nothing

**Comment by jombooth** [comment]
hi @sadek-snoussi - please ensure that interactive mode has been enabled on your model (click the 3 dots on the model card in your first screenshot); then auto-annotation should appear as a toggle at the bottom of Quick View or Label Stream. It's not displayed in the menu you've screenshotted.

**Comment by pascal-maker** [comment]
![Image](https://github.com/user-attachments/assets/a331616f-e0f2-4f5f-b124-b0ac170c5893) when I click on it it still does not automatically annotate.

**Comment by fan106** [comment]
I've encountered the same problem. If you solve it, could you teach me how to do it?

**Comment by fan106** [comment]
the below is the output from ML backend
MMDetection => Label Studio mapping of labels :
mmdetection-3  |  {'airplane': 'Airplane', 'car': 'Car', 'cat': 'cat'}
mmdetection-3  | [2025-12-17 03:10:02,345] [DEBUG] [label_studio_sdk._extensions.label_studio_tools.core.utils.io::get_local_path::139] Image and upload dirs: image_dir=/root/.local/share/label-studio/media/upload, upload_dir=/root/.local/share/label-studio/media/upload
mmdetection-3  | [2025-12-17 03:10:02,346] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
mmdetection-3  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
mmdetection-3  |     return f(*args, **kwargs)
mmdetection-3  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_ml/api.py", line 69, in _predict
mmdetection-3  |     response = model.predict(tasks, context=context, **params)
mmdetection-3  |   File "/app/mmdetection.py", line 160, in predict
mmdetection-3  |     prediction = self.predict_one_task(task)
mmdetection-3  |   File "/app/mmdetection.py", line 166, in predict_one_task
mmdetection-3  |     image_path = get_local_path(image_url, task_id=task.get('id'))
mmdetection-3  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_sdk/_extensions/label_studio_tools/core/utils/io.py", line 159, in get_local_path
mmdetection-3  |     raise FileNotFoundError(
mmdetection-3  | FileNotFoundError: Can't resolve url, neither hostname or project_dir passed: /data/upload/3/c29f36f7-mmexport1633684900217.jpg. You can set LABEL_STUDIO_URL environment variable to use it as a hostname.
mmdetection-3  | 
mmdetection-3  | Traceback (most recent call last):
mmdetection-3  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
mmdetection-3  |     return f(*args, **kwargs)
mmdetection-3  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_ml/api.py", line 69, in _predict
mmdetection-3  |     response = model.predict(tasks, context=context, **params)
mmdetection-3  |   File "/app/mmdetection.py", line 160, in predict
mmdetection-3  |     prediction = self.predict_one_task(task)
mmdetection-3  |   File "/app/mmdetection.py", line 166, in predict_one_task
mmdetection-3  |     image_path = get_local_path(image_url, task_id=task.get('id'))
mmdetection-3  |   File "/opt/conda/lib/python3.10/site-packages/label_studio_sdk/_extensions/label_studio_tools/core/utils/io.py", line 159, in get_local_path
mmdetection-3  |     raise FileNotFoundError(
mmdetection-3  | FileNotFoundError: Can't resolve url, neither hostname or project_dir passed: /data/upload/3/c29f36f7-mmexport1633684900217.jpg. You can set LABEL_STUDIO_URL environment variable to use it as a hostname.
mmdetection-3  | 
mmdetection-3  | [2025-12-17 03:10:02,346] [DEBUG] [label_studio_ml.api::log_response_info::191] Response status: 500 INTERNAL SERVER ERROR
mmdetection-3  | [2025-12-17 03:10:02,346] [DEBUG] [label_studio_ml.api::log_response_info::192] Response headers: Content-Type: application/json
mmdetection-3  | Content-Length: 1216
mmdetection-3  | 
mmdetection-3  | 
mmdetection-3  | [2025-12-17 03:10:02,346] [DEBUG] [label_studio_ml.api::log_response_info::193] Response body: b'{"detail":"FileNotFoundError: Can\'t resolve url, neither hostname or project_dir passed: /data/upload/3/c29f36f7-mmexport1633684900217.jpg. You can set LABEL_STUDIO_URL environment variable to use it as a hostname.","request":{},"result":{"traceback":"Traceback (most recent call last):\\n  File \\"/opt/conda/lib/python3.10/site-packages/label_studio_ml/exceptions.py\\", line 39, in exception_f\\n    return f(*args, **kwargs)\\n  File \\"/opt/conda/lib/python3.10/site-packages/label_studio_ml/api.py\\", line 69, in _predict\\n    response = model.predict(tasks, context=context, **params)\\n  File \\"/app/mmdetection.py\\", line 160, in predict\\n    prediction = self.predict_one_task(task)\\n  File \\"/app/mmdetection.py\\", line 166, in predict_one_task\\n    image_path = get_local_path(image_url, task_id=task.get(\'id\'))\\n  File \\"/opt/conda/lib/python3.10/site-packages/label_studio_sdk/_extensions/label_studio_tools/core/utils/io.py\\", line 159, in get_local_path\\n    raise FileNotFoundError(\\nFileNotFoundError: Can\'t resolve url, neither hostname or project_dir passed: /data/upload/3/c29f36f7-mmexport1633684900217.jpg. You can set LABEL_STUDIO_URL environment variable to use it as a hostname.\\n"},"status":500}\n'
