### ISSUE TITLE
FileNotFoundError when exporting to Pascal VOC

### ISSUE THREAD

**Issue by razvanilin** [heartexlabs/label-studio#627]
**Describe the bug**
I annotate some images with the Bbox object detection setting and then when I hit Export to VOC I get the error below. If I remove the completion for the particular file that is not found, I get the same error but for another completed file.

Error from the console:

```
Traceback (most recent call last):
  File "/var/www/html/label-studio/label_studio/utils/misc.py", line 64, in exception_f
    return f(*args, **kwargs)
  File "/var/www/html/label-studio/label_studio/blueprint.py", line 576, in api_export
    g.project.converter.convert(g.project.output_dir, zip_dir, format=export_format)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter-0.0.23rc3-py3.8.egg/label_studio_converter/converter.py", line 93, in convert
    self.convert_to_voc(input_data, output_data, output_image_dir=image_dir, is_dir=is_dir)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter-0.0.23rc3-py3.8.egg/label_studio_converter/converter.py", line 419, in convert_to_voc
    _, _, channels = get_image_size_and_channels(image_path)
  File "/usr/local/lib/python3.8/dist-packages/label_studio_converter-0.0.23rc3-py3.8.egg/label_studio_converter/utils.py", line 131, in get_image_size_and_channels
    i = Image.open(image_path)
  File "/home/surgical/.local/lib/python3.8/site-packages/PIL/Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'images/0d36db-Screenshot_2020-10-28_122403.jpg'
```

**To Reproduce**
1. Clone the repo and follow the instructions here to set it up: https://labelstud.io/guide/index.html#Running-from-source
2. Select the Bbox settings from the `Settings` menu
3. Upload some images and annotate a few
4. Click on Export from the `/tasks` route
5. Select VOC from the dropdown and click export to get the error

**Expected behavior**
I was expecting to be able to download the annotations in the Pascal VOC format.

**Screenshots**
![image](https://user-images.githubusercontent.com/5342321/109451493-89bdf280-7a88-11eb-8c17-a206c95bc48a.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio Version: Not sure where to find this - Using latest on `master`

**Comment by mirfan899** [comment]
Same issue here. I'm using Ubuntu 18.04.

**Comment by stevebit** [comment]
Same issues with the latest version of docker hub.

**Comment by makseq** [comment]
@mirfan899 @stevebit @razvanilin Could you check the latest master of https://github.com/heartexlabs/label-studio-converter ?

```
pip install -e git+https://github.com/heartexlabs/label-studio-converter@master#egg=label-studio-converter 
```

I hope it's fixed there.

**Comment by mirfan899** [comment]
Sure.

**Comment by mirfan899** [comment]
Great, it's working now.
