### ISSUE TITLE
from label_studio_sdk.label_interface.objects import PredictionValue fails

### ISSUE THREAD

**Issue by kvkamal** [heartexlabs/label-studio#6292]
**Describe the bug**
After installing label studio version 1.13.1, unable to start ml backend using command:

label-studio-ml start --debug mycustom_ml_backend

fails when executing:
from label_studio_sdk.label_interface.objects import PredictionValue
when running label-studio-ml-backem/label_studio_ml/response.py

**To Reproduce**
Try running any custom ml backend that needs to run response.py

**Expected behavior**
used to work in 1.12
**Screenshots**
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\path\to\new\virtual\environment\Scripts\label-studio-ml.exe\__main__.py", line 4, in <module>
  File "C:\path\to\new\virtual\environment\Lib\site-packages\label_studio_ml\server.py", line 13, in <module>
    from .model import get_all_classes_inherited_LabelStudioMLBase
  File "C:\path\to\new\virtual\environment\Lib\site-packages\label_studio_ml\model.py", line 28, in <module>
    from .response import ModelResponse
  File "C:\path\to\new\virtual\environment\Lib\site-packages\label_studio_ml\response.py", line 5, in <module>
    from label_studio_sdk.objects import PredictionValue
ModuleNotFoundError: No module named 'label_studio_sdk.objects'
Press any key to continue . . .

**Environment (please complete the following information):**
 - OS: Windows Server 2022 Datacenter
 - Label Studio Version [1.13.1]
 - (used to work in v1.12)

**Additional context**
tried installing 1.13.1 because of #6291 when using v1.12.1 .  Currently work stalled because I'm unable to use ml backend.

**Comment by jombooth** [comment]
Hi @kvkamal,

Could you pull the latest version of the ML backend? This was fixed in https://github.com/HumanSignal/label-studio-ml-backend/commit/bdfc42b68a0a7e5dd0eeb328d27457b71eec6540#diff-89ce0fb4c09d2e5133f5924a8b373dad7d7145cb555a16b444d39b0b25d2031c

**Comment by kvkamal** [comment]
ML backend works fine after reinstalling latest backend.  Thanks.
