### ISSUE TITLE
Max retries exceeded with url: /pypi/label-studio/json & Temporary failure in name resolution'

### ISSUE THREAD

**Issue by fatemeh-mohseni-AI** [heartexlabs/label-studio#6339]
trying to run labelstudio and connect it to SAM-2 , I encounter an error and a warning .

Ubuntu 22
Docker version 27.0.3,  
Docker Compose version v2.28.1

```
docker run -it --user root -p 8080:8080 \
               -v $(pwd)/mydata:/label-studio/data \
               --env LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true \
               --env LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/home/fatemeh/develop/label-studio/data/images \
               heartexlabs/label-studio:latest
```

```
Can't get latest version


You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_provider_connection_delete" has conflict with protected namespace "model_".


Traceback (most recent call last):
  File "/label-studio/label_studio/core/utils/common.py", line 378, in get_latest_version
    response = requests.get(pypi_url, timeout=10).text
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/label-studio/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7dd0ed9e0580>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by fatemeh-mohseni-AI** [comment]
using docker exec , I entered in the container. the result of running  
```
python3 manage.py makemigrations
```
command, was the error above. 
why that happens?

**Comment by jombooth** [comment]
Hi @fatemeh-mohseni-AI - it looks like your machine failed to connect to pypi.org. This is likely to be a transient error; unfortunately, it's also not something we can control on our side. Thanks for using Label Studio!

**Comment by DrissiReda** [comment]
@jombooth I'm getting the same error, and the thread closes, because I'm in an offline environment. Any way to use label studio when completely offline? Setting `LABEL_STUDIO_LATEST_VERSION_CHECK="False"` does nothing


These are my relevant logs:

```bash
  File "/label-studio/.venv/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/label-studio/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f49fd7f11c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
{"timestamp": "17/Jan/2025:13:03:39 +0000", "source": "uwsgi", "levelname": "INFO", "message": "SIGINT/SIGTERM received...killing workers..."}
{"timestamp": "17/Jan/2025:13:03:39 +0000", "source": "uwsgi", "levelname": "INFO", "message": "gateway \"uWSGI http 1\" has been buried (pid: 64)"}
```
