### ISSUE TITLE
Instructions on "Using custom DM build in Label Studio" not working

### ISSUE THREAD

**Issue by NotAnyMike** [heartexlabs/label-studio#640]
**Describe the bug**
After modifying dm2, and following the steps in the read me of dm2 for "Using custom DM build in Label Studio". I expect to see the changes reflected in the dm UI of label studio.

**To Reproduce**

You can follow the official steps [here](https://github.com/heartexlabs/dm2#using-custom-dm-build-in-label-studio)

What I did is

1. I make a small change on md2
2. `run npm ci && npm run build:module`
3. copy the files inside build to `[my/path/to/ls]/label_studio/static/dm`,
4. Run `label_studio start project` but the changes do not show up

**Expected behavior**
I expect to see the changes reflected in the dm UI of label studio.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Mac
 - Label Studio Version 0.9.1

**Additional context**
N/A

**Comment by nicholasrq** [comment]
hey, @NotAnyMike. could you please show the structure of your `label_studio/static/dm` directory after copying files fro DM?

**Comment by NotAnyMike** [comment]
```
label_studio/static/dm/
├── index.html
├── js
│   ├── main.js
│   ├── main.js.LICENSE.txt
│   └── main.js.map
├── main.css
├── main.css.map
├── main.js
├── main.js.map
├── src_dev_js.chunk.js
├── src_dev_js.chunk.js.map
├── static
│   ├── css
│   │   ├── main.css
│   │   └── main.css.map
│   └── js
│       ├── main.js
│       ├── main.js.LICENSE.txt
│       └── main.js.map
└── version.json
```

**Comment by NotAnyMike** [comment]
Even renaming the `dm` folder doesn't look like changing anything. LS still loads perfectly and I cannot see any difference

**Comment by nicholasrq** [comment]
@NotAnyMike thanks. as the instruction says, you need to copy **contents** of `build/static/**` to `label_studio/static/dm`. you now have `static` directory under `label_studio/static/dm` which is incorrect. you should end up with structure like this:

```
label_studio/static/dm/
├── index.html
├── css
│   ├── main.css
│   └── main.css.map
└── js
│   ├── main.js
│   ├── main.js.LICENSE.txt
│   └── main.js.map
└── version.json
```

**Comment by NotAnyMike** [comment]
I have tried that already, as I said even removing the dm folder doesn't look like changing anything. What I am doing exactly is adding in line `153` of file `src/components/DataManager/TabPanel/TabPanel.js` another button for importing (just to change something). I repeat the code for importing

```
{store.SDK.interfaceEnabled("import") && (
<ImportButton size={toolbarSize}>Importing</ImportButton>
)}
```

then I run `run npm ci && npm run build:module` and then copy `build/static/` files and folders to `[ls/path/]/label_studio/static/dm`. But it does not work. When I launch label studio and see no extra button. Same if i remove totally the folder `dm` from `[ls/path]/label_studio/static/dm`.

Removing the folder at least should change something. I am wondering if I am missing a step before in label studio? I have only run the command to launch label studio. Should I run something before there?

**Comment by nicholasrq** [comment]
@NotAnyMike alright, I got it. seems we missed one of the steps on the instruction

after copying files from `build` dir execute this command in **label studio** folder:

```
npm ci && npx webpack
```

we'll add it to the instruction, sorry for that

**Comment by NotAnyMike** [comment]
Nice thank you! we are having progress, but now there is a different issue. If I run `npc ci && npx webpack` before launching LS. The DM only shows `loading...`. If I copy the whole `build` folder instead of `build/static` it loads normally. But then I cannot see any change in the DM UI.

**Comment by nicholasrq** [comment]
@NotAnyMike sorry for the long reply, was super busy with 1.0.0 launch

do you see any errors in your browser console when this "loading..." thing happens? 

copying whole `build` instead of `build/static` won't take any effect as that's not an expected structure

**Comment by NotAnyMike** [comment]
I am running this with the new version. After running `npm ci && npm run build:module` in dm2 I get the following outputs

```
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.13 install /Users/mikem/Documents/git/dm2/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mikem/Documents/git/dm2/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v14.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> husky@3.1.0 install /Users/mikem/Documents/git/dm2/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@3.1.0 postinstall /Users/mikem/Documents/git/dm2/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate


> core-js@2.6.11 postinstall /Users/mikem/Documents/git/dm2/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

added 1642 packages in 26.138s

> @heartexlabs/datamanager@2.0.4 build:module /Users/mikem/Documents/git/dm2
> BUILD_NO_HASH=true BUILD_NO_CHUNKS=true BUILD_MODULE=true npm run build


> @heartexlabs/datamanager@2.0.4 build /Users/mikem/Documents/git/dm2
> webpack

Failed to load ./.env.
assets by status 6.82 MiB [emitted]
  asset main.js 6.82 MiB [emitted] [big] (name: main) 1 related asset
  asset src_dev_js.chunk.js 2.53 KiB [emitted] 1 related asset
assets by status 59.3 KiB [compared for emit]
  asset main.css 56.9 KiB [compared for emit] (name: main) 1 related asset
  asset index.html 2.49 KiB [compared for emit]
Entrypoint main 6.87 MiB (6.69 MiB) = main.css 56.9 KiB main.js 6.82 MiB 2 auxiliary assets
orphan modules 331 KiB [orphan] 194 modules
runtime modules 7.53 KiB 13 modules
cacheable modules 5.98 MiB
  modules by path ./node_modules/ 5.13 MiB 89 modules
  modules by path ./src/ 879 KiB 158 modules
css modules 56.8 KiB
  modules by path ./src/components/Common/ 25.4 KiB 7 modules
  modules by path ./src/components/Filters/ 2.85 KiB 3 modules
  modules by path ./src/components/Table/ 1.65 KiB 3 modules
  modules by path ./src/components/DataManager/ 332 bytes 2 modules
  modules by path ./src/components/Label/ 1.6 KiB
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[1]!./node_modules/stylus-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[2]!./src/components/Label/Label.styl 1.13 KiB [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[1]!./node_modules/stylus-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[2]!./src/components/Label/Toolbar/Toolbar.styl 480 bytes [code generated]
  css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[1]!./node_modules/stylus-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[2]!./src/components/App/App.styl 1.49 KiB [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/react-datepicker/dist/react-datepicker.css 23.5 KiB [code generated]
webpack 5.23.0 compiled successfully in 10678 ms
```

After copying the `static` folder to `label_studio/static/dm`, I run `npm ci && npx webpack` inside `label_studio` I get the follwoing error (I didn't have this error in the older version).

```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/mikem/Documents/git/label-studio/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/mikem/Documents/git/label-studio/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mikem/.npm/_logs/2021-03-18T11_48_08_349Z-debug.log
```

**Comment by nicholasrq** [comment]
thank you, appreciate your feedback!

if you're running LS 1.0.0, there are massive changes to the overall structure and architecture of the app. the instruction in DM repo is only applicable to LS <1.0.0

to run custom DM build in LS >1.0.0, please follow these steps:

- as previously, you should first build the DM itself by running `npm ci &&  npm run build:module` in the DM repo
- next copy everything from `[your-dm-dir]/build/static` to `[your-ls-dir]/label_studio/frontend/lib/dm`
- make sure not to remove `version.json` from `frontend/lib/dm`, it's significant to have it there
- in the `label_studio/frontend` execute the following: `npm ci  && npx run build` to build your LS frontend JS and CSS bundles

we have plans to improve and simplify those scenarios, where our users want to run LS with custom builds of LSF/DM, but it is  a work in progress and not yet available. we're planning to make it happen in LS 1.0.1

**Comment by NotAnyMike** [comment]
I am doing this in new clones of dm2 and label-studio to have everything new and shiny. On dm2 with the new version, after calling `npm ci && npm run build:module` the `build` folder does not have the`css` nor the `js` folders anymore. Is this expected behaviour?

Anyway moving all the files (there is no js or css folder now) from `dm2/build/` into `[ls/path]/label-studio/frontend/lib/dm` has no effect.
 
---

This is the output of running ` npm ci && npm run build:module` in dm2

```
npm WARN prepare removing existing node_modules/ before installation

> fsevents@1.2.13 install /Users/mikem/Documents/git/dm3/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> husky@3.1.0 install /Users/mikem/Documents/git/dm3/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> husky@3.1.0 postinstall /Users/mikem/Documents/git/dm3/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate


> core-js@2.6.11 postinstall /Users/mikem/Documents/git/dm3/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 1642 packages in 30.473s

> @heartexlabs/datamanager@2.0.4 build:module /Users/mikem/Documents/git/dm3
> BUILD_NO_HASH=true BUILD_NO_CHUNKS=true BUILD_MODULE=true npm run build


> @heartexlabs/datamanager@2.0.4 build /Users/mikem/Documents/git/dm3
> webpack

Failed to load ./.env.
assets by path *.js 6.82 MiB
  asset main.js 6.82 MiB [compared for emit] [big] (name: main) 1 related asset
  asset src_dev_js.chunk.js 2.53 KiB [compared for emit] 1 related asset
asset main.css 56.9 KiB [compared for emit] (name: main) 1 related asset
asset index.html 2.49 KiB [compared for emit]
Entrypoint main 6.87 MiB (6.69 MiB) = main.css 56.9 KiB main.js 6.82 MiB 2 auxiliary assets
orphan modules 331 KiB [orphan] 194 modules
runtime modules 7.53 KiB 13 modules
cacheable modules 5.98 MiB
  modules by path ./node_modules/ 5.13 MiB 89 modules
  modules by path ./src/ 879 KiB 158 modules
css modules 56.8 KiB
  modules by path ./src/components/Common/ 25.4 KiB 7 modules
  modules by path ./src/components/Filters/ 2.85 KiB 3 modules
  modules by path ./src/components/Table/ 1.65 KiB 3 modules
  modules by path ./src/components/DataManager/ 332 bytes 2 modules
  modules by path ./src/components/Label/ 1.6 KiB
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[1]!./node_modules/stylus-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[2]!./src/components/Label/Label.styl 1.13 KiB [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[1]!./node_modules/stylus-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[2]!./src/components/Label/Toolbar/Toolbar.styl 480 bytes [code generated]
  css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[1]!./node_modules/stylus-loader/dist/cjs.js??ruleSet[1].rules[3].oneOf[1].use[2]!./src/components/App/App.styl 1.49 KiB [code generated]
  css ./node_modules/css-loader/dist/cjs.js!./node_modules/react-datepicker/dist/react-datepicker.css 23.5 KiB [code generated]
webpack 5.23.0 compiled successfully in 10467 ms
```


This is the output of `npm ci && npm run build` after running it inside `label-studio/frontend`

```
npm WARN prepare removing existing node_modules/ before installation
added 573 packages in 10.567s

> frontend@1.0.0 build /Users/mikem/Documents/git/label-studio3/label_studio/frontend
> webpack

[BABEL] Note: The code generator has deoptimised the styling of /Users/mikem/Documents/git/label-studio3/label_studio/frontend/lib/dm/js/main.js as it exceeds the max of 500KB.
asset index.js 4.96 MiB [compared for emit] (name: main) 1 related asset
asset main.css 118 KiB [compared for emit] (name: main) 1 related asset
Entrypoint main 5.08 MiB (3.84 MiB) = main.css 118 KiB index.js 4.96 MiB 2 auxiliary assets
orphan modules 426 KiB [orphan] 201 modules
runtime modules 1.13 KiB 5 modules
cacheable modules 4.51 MiB
  modules by path ./src/ 316 KiB 144 modules
  modules by path ./node_modules/ 3 MiB 62 modules
  modules by path ./lib/dm/ 1.21 MiB
    ./lib/dm/css/main.css 50 bytes [built] [code generated]
    ./lib/dm/js/main.js 1.21 MiB [built] [code generated]
css modules 118 KiB
  modules by path ./src/components/ 35.5 KiB 11 modules
  modules by path ./src/pages/ 24.4 KiB 8 modules
```

**Comment by nicholasrq** [comment]
@NotAnyMike it not an expected behavior. I pushed a fix to Webpack settings so it should properly build DM now. there was an issue with `NODE_ENV` not being properly set

**Comment by nicholasrq** [comment]
hey @NotAnyMike, please check out #685. this PR brings easier integration with custom DM builds

**Comment by NotAnyMike** [comment]
If you run the instructions on a new dm and ls without any notifications, you cannot see the table with the labelled examples once you launch ls.

In the browser console this shows

```
Uncaught (in promise) TypeError: _lib_dm_js_main__WEBPACK_IMPORTED_MODULE_1___default(...).DataManager is not a constructor
    at initializeDataManager (DataManager.js:45)
    at DataManager.js:66
    at DataManager.js:99
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:646)
    at runWithPriority$1 (react-dom.development.js:11276)
```

**Comment by nicholasrq** [comment]
@NotAnyMike nevermind, the PR is merged into master already.

those changes remove the DM from main LS bundle. it mean that you only have to build DM itself and copy the files to LS. building LS bundle is only required if you're making changes to the LS frontend

**Comment by NotAnyMike** [comment]
Now it is working! There is no longer a `[your-ls-dir]/label_studio/frontend/lib/dm` but a `[your-ls-dir]/label_studio/frontend/dist/dm`. But there is one more thing that I haven't manage to make it work, how can I add an extra button on top right next to the Settings button or change the text on Setting?

**Comment by nicholasrq** [comment]
@NotAnyMike such changes are made inside `label_studio/frontend/src/pages/DataManager/DataManager.js`. you can find `DataManager.context` section there, it describes what buttons will be in the top-right corner

after changing any of the files in `frontend/src` you need to build the bundle. to do that navigate to `label_studio/frontend` directory and execute the following command: `npm ci && npm run build` or, if you need optimized production build, run `npm ci && npm run build:production`

**Comment by NotAnyMike** [comment]
There is something else that I haven't been able to figure it out. There are two ways of launching LS, using `label-studio start ...` or `python label-studio/manage.py run_server`. The first is reachable from outside the instance through the url but the static folder is not found (so the interface looks bad), and with the second method, the static folder is found but you cannot reach it from outside the instance, do you know how to solve this (i.e. make it accessible from outside and have the static folder)?

**Comment by makseq** [comment]
Now we have a special build scripts: 

```
cd label-studio
make frontend-setup
make frontend-fetch
make frontend-build  # or make frontend-watch
```
