### ISSUE TITLE
Unauthorized on /data/local-files/ on Server

### ISSUE THREAD

**Issue by phalix** [heartexlabs/label-studio#6783]
**Describe the bug**
When exporting the project in yolo format, i get the following error messages. As a result I get a zip folder, but the images folder is completely empty. I am running ls on Version 1.15.0 in a docker container. 
The API /data/local-files which is called locally on the server throws Unauthorized.

app_1  | [2024-12-12 07:53:16,791] [core.utils.common::custom_exception_handler::91] [ERROR] d7a00b57-cd82-4731-801f-059dac0bf2eb Authentication credentials were not provided.
app_1  | Traceback (most recent call last):
app_1  |   File "/label-studio/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 497, in dispatch
app_1  |     self.initial(request, *args, **kwargs)
app_1  |   File "/label-studio/.venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 333, in sentry_patched_drf_initial
app_1  |     return old_drf_initial(self, request, *args, **kwargs)
app_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
app_1  |   File "/label-studio/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 415, in initial
app_1  |     self.check_permissions(request)
app_1  |   File "/label-studio/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 333, in check_permissions
app_1  |     self.permission_denied(
app_1  |   File "/label-studio/.venv/lib/python3.12/site-packages/rest_framework/views.py", line 174, in permission_denied
app_1  |     raise exceptions.NotAuthenticated()
app_1  | rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided.
app_1  | [2024-12-12 07:53:16,797] [django.request::log_response::241] [WARNING] Unauthorized: /data/local-files/
app_1  | [2024-12-12 07:53:16,797] [django.request::log_response::241] [WARNING] Unauthorized: /data/local-files/

**To Reproduce**
1. Create a project
2. Create some annotations
3. export the project in yolo format

**Expected behavior**
The exported zip file should have the images in its folder.

**Environment (please complete the following information):**
 - OS: Image is heartexlabs/label-studio:1.15.0
 - Label Studio Version 1.15.0

**Comment by makseq** [comment]
Check this related issue please: https://github.com/HumanSignal/label-studio/issues/6771
