### ISSUE TITLE
"You cannot access body after reading from request's data stream"

### ISSUE THREAD

**Issue by S4r4h-O** [heartexlabs/label-studio#6794]
**Describe the bug**
Cannot import data to a set

**To Reproduce**
1. Creat a project
2. Click on Import data
3. Import URL or files don't work
4:

"Object { id: "42272f52-0cd5-4b38-ae72-ef10a567b62c", status_code: 500, version: "1.15.0", detail: "You cannot access body after reading from request's data stream", exc_info: `Traceback (most recent call last):\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\views.py", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\utils\\decorators.py", line 46, in _wrapper\n    return bound_method(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\label_studio\\data_import\\api.py", line 256, in post\n    return super(ImportAPI, self).post(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\generics.py", line 194, in post\n    return self.create(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\label_studio\\data_import\\api.py", line 393, in create\n    return self.sync_import(request, project, preannotated_from_fields, commit_to_project, return_task_ids)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\label_studio\\data_import\\api.py", line 273, in sync_import\n    parsed_data, file_upload_ids, could_be_tasks_list, found_formats, data_columns = load_tasks(request, project)\n                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\label_studio\\data_import\\uploader.py", line 226, in load_tasks\n    if len(request.FILES):\n           ^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\request.py", line 447, in FILES\n    self._load_data_and_files()\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\request.py", line 283, in _load_data_and_files\n    self._data, self._files = self._parse()\n                              ^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\request.py", line 333, in _parse\n    stream = self.stream\n             ^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\request.py", line 207, in stream\n    self._load_stream()\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\request.py", line 313, in _load_stream\n    self._stream = io.BytesIO(self.body)\n                              ^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\rest_framework\\request.py", line 421, in __getattr__\n    return getattr(_request, attr)\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File "C:\\Users\\Sarah\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\django\\http\\request.py", line 327, in body\n    raise RawPostDataException(\ndjango.http.request.RawPostDataException: You cannot access body after reading from request's data stream\n` }"

When importing files.

[c2b17384-3845-4728-953c-2f25b8dfc8d9] Validation error ('content-length')

When adding url

**Environment (please complete the following information):**
 - OS: Win11
 - Label Studio Version 1.15.0
 - Python 3.12.8

**Comment by jsomeara** [comment]
I am also getting this issue

**Comment by MPavFox** [comment]
I'm also having the same problem.

**Comment by ssuljo** [comment]
I'm also getting same issue

**Comment by S4r4h-O** [comment]
Forgot to mention that happens with the latest version of Ubuntu too

**Comment by elifriedman** [comment]
Same problem. I'm using label-studio==1.15.0
I think the problem might be with djangorestframework because I downgraded to djangorestframework==3.13.0 and label-studio==1.13.1 and don't get the error

**Comment by MPavFox** [comment]
Making the videos shorter to a duration of max 6 min (no more than 250 MB) worked for me. I keep having the problem if I try to import all the shorter videos together, but one by one works.

**Comment by HouseWay** [comment]
me too,when I import images from local

**Comment by devoden** [comment]
same error when try to import 138 images at once. 
Fixed with import small portions of 20-40 images at once.

**Comment by bakwc** [comment]
Same here. For large dataset reproduce 100%

**Comment by laurenzbirnbaum** [comment]
I am having the same issue

**Comment by jbadger3** [comment]
For anyone else that stumbles into this problem it turns out there is a limit of [200k tasks and 200mb per post](https://labelstud.io/api#tag/Import/operation/api_projects_file-uploads_delete) request to your Label Studio server.  You can get around this limitation by breaking up your import into smaller pieces but **don't**!  Use the [source storage](https://labelstud.io/guide/storage) mechanism as recommended by Label studio instead.  I ended up setting up local storage for my project, which solved the issue.

**Comment by omrode1** [comment]
how do we setup local storage ?

**Comment by xxesth** [comment]
I'm working well within the limits, but I'm running into the same issue.
I also tried changing `self.body` to `self.data` on line 313 of `rest_framework/request.py`, but that resulted in a `maximum recursion depth exceeded` error.

Why the API forces us to buy a cloud service?
