### ISSUE TITLE
API call /api/tasks causing HTTP 500 

### ISSUE THREAD

**Issue by antonyscerri** [heartexlabs/label-studio#684]
**Describe the bug**
After working through several JSON payload issues making a call to /api/tasks to create a single task the server responded with a HTTP 500 error. On the server end there was a stack trace (below). If i take the same JSON payload and wrap in an array and use the bulk import call at /api/projects/[id]/import it works fine. 

'''
[2021-03-19 15:04:10,113] [django.request::log_response::224] [ERROR] Internal Server Error: /api/tasks/
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/label_studio/tasks/api.py", line 58, in post
    return super(TaskListAPI, self).post(request, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/label_studio/tasks/serializers.py", line 141, in validate
    return validator.validate(task)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/label_studio/tasks/validation.py", line 132, in validate
    self.check_data_and_root(self.project, task['data'])
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/label_studio/tasks/validation.py", line 81, in check_data_and_root
    TaskValidator.check_data(project, data)
  File "/home/xxx/anaconda3/envs/labelstudio/lib/python3.8/site-packages/label_studio/tasks/validation.py", line 51, in check_data
    for data_key, data_type in project.data_types.items():
AttributeError: 'NoneType' object has no attribute 'data_types'
'''

**Expected behavior**
I should be able to add a single task item through the API call /api/tasks

**Environment (please complete the following information):**
 - OS: linux
 - Label Studio Version 1.0.0 and 1.0.0.post0

**Comment by makseq** [comment]
@antonyscerri it's not possible to call api/tasks without project. Try api/tasks?project=N

**Comment by antonyscerri** [comment]
@makseq The documentation shows the project ID as part of the payload. I gave it a try putting it in the url and its producing the same error.

**Comment by niklub** [comment]
@antonyscerri thanks for bringing it up. Fixing it in https://github.com/heartexlabs/label-studio/pull/692

**Comment by antonyscerri** [comment]
I had some other issues with related API calls which i may log i've got to try it again and check if its been reported. Deleting tasks in bulk with DELETE /api/project/<id>/tasks/ is taking a long time and then producing the similar something went wrong.  Deleting tasks using the DELETE /api/tasks/<id> call can require multiple calls as the first one seems to delete any annotations on the task and the second time deletes the task, but it's not documented. I was going to check out 1.0.0.post2 release but I couldn't use it as the UI is broken, looks like a CSS issue causing things to render poorly.

**Comment by niklub** [comment]
Hi, @antonyscerri ! 
I've just checked the tasks bulk delete problem in [release branch](https://github.com/heartexlabs/label-studio/pull/681), it doesn't reproduce. Can you try it?

**Comment by makseq** [comment]
@antonyscerri Do you still have this problem?

**Comment by antonyscerri** [comment]
sorry not had a chance to go back and test, i was reviewing it at the time and have been down a different rabbit hole. I do intend to come back to Label Studio at some point to check it and look at some elements in more depth, not sure when at this time sorry.

**Comment by niklub** [comment]
@antonyscerri please feel free to reopen the issue if you encounter the same problem in versions `label-studio>=1.0.1`
