### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Vickzhang** [heartexlabs/label-studio#693]
**Describe the bug**
I installed  label-studio  with conda sucessfully,  but failed to start correctly.  

**To Reproduce**
1. conda create --name label-studio python=3.8
2. conda activate label-studio
3. pip install label-studio
4.  label-studio start -b
5.  Error:  The server console output info as follows and the UI is  almost blank:
```
Traceback (most recent call last):
  File "/miniconda/envs/label-studio/lib/python3.8/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/miniconda/envs/label-studio/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/miniconda/envs/label-studio/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/miniconda/envs/label-studio/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/miniconda/envs/label-studio/lib/python3.8/site-packages/django/core/servers/basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/miniconda/envs/label-studio/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[22/Mar/2021 06:07:27] "GET / HTTP/1.1" 302 0
[22/Mar/2021 06:07:27] "GET /projects/ HTTP/1.1" 200 2432
[22/Mar/2021 06:07:27] "GET /static/fonts/roboto/roboto.6ffe390dd5ff.css HTTP/1.1" 200 4451
[22/Mar/2021 06:07:27] "GET /static/css/uikit.e49a7a43adbd.css HTTP/1.1" 200 3892
[22/Mar/2021 06:07:27] "GET /static/css/main.3b36b24fbb6f.css HTTP/1.1" 200 15457
[22/Mar/2021 06:07:27] "GET /react-app/main.css?v=4f10ca HTTP/1.1" 200 71464
[22/Mar/2021 06:07:27] "GET /static/js/helpers.9a01b074ff58.js HTTP/1.1" 200 13336
[22/Mar/2021 06:07:27] "GET /static/js/jquery.min.220afd743d9e.js HTTP/1.1" 200 88145
[22/Mar/2021 06:07:32] "GET /react-app/index.js?v=4f10ca HTTP/1.1" 200 3933744
[22/Mar/2021 06:07:33] "GET /static/icons/logo-black.svg HTTP/1.1" 200 10236
[22/Mar/2021 06:07:33] "GET /api/version HTTP/1.1" 200 453
[22/Mar/2021 06:07:33] "GET /api/projects HTTP/1.1" 200 1894
[22/Mar/2021 06:07:33] "GET /static/fonts/roboto/roboto-v20-latin_cyrillic-500.2e0bf09ac4b4.woff2 HTTP/1.1" 200 22880
[22/Mar/2021 06:07:33] "GET /projects/ HTTP/1.1" 200 2432
[22/Mar/2021 06:07:35] "GET /static/fonts/roboto/roboto-v20-latin_cyrillic-regular.9af3b948743a.woff2 HTTP/1.1" 200 22428
[22/Mar/2021 06:07:39] "GET /dm/js/main.js?v=099282 HTTP/1.1" 404 1472
[22/Mar/2021 06:07:39] "GET /dm/css/main.css?v=099282 HTTP/1.1" 404 1472
[22/Mar/2021 06:07:39] "GET /api/projects/1 HTTP/1.1" 200 952
```

**Environment (please complete the following information):**
 - OS:  ubuntu 16.04
 -  Label Studio Version :  label-studio-1.0.0.post2

**Additional context**

**Comment by niklub** [comment]
Hi, @Vickzhang ! Recurrent `ConnectionResetError` in the runtime is a known issue, but by now it looks non-blocking for the user flow. But what do you mean from "...UI is almost blank..." ? Can you please specify what page  exactly is, and may be you can check for the browser console logs and drop them here so we can better understand what's going on.

**Comment by Vickzhang** [comment]
> Hi, @Vickzhang ! Recurrent `ConnectionResetError` in the runtime is a known issue, but by now it looks non-blocking for the user flow. But what do you mean from "...UI is almost blank..." ? Can you please specify what page exactly is, and may be you can check for the browser console logs and drop them here so we can better understand what's going on.

Hi, @niklub .  The browser console logs:
```
Refused to apply style from 'http://myip:port/dm/css/main.css?v=099282' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Failed to load resource: the server responded with a status of 404 (Not Found)
```
-----
But version 1.0.0-post3 and  1.0.0 don't seem to have this problem.  
Thanks.
