### ISSUE TITLE
Cloned the latest changes and when i run docker-compose up -d getting below error

### ISSUE THREAD

**Issue by bharath4793** [heartexlabs/label-studio#725]
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/dist-packages/compose/cli/errors.py", line 11, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/dist-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/dist-packages/docker/api/client.py", line 6, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 97, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "/usr/lib/python2.7/dist-packages/requests/_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "/usr/lib/python2.7/dist-packages/requests/compat.py", line 47, in <module>
    from urllib3.packages.ordered_dict import OrderedDict
ImportError: No module named ordered_dict

**Comment by niklub** [comment]
Hi, @bharath4793 !

Could you please check running the same from this branch https://github.com/heartexlabs/label-studio/pull/681 ? We'd significantly reworked docker-compose scripts there, so maybe your problem has been gone

**Comment by bharath4793** [comment]
Hi,

I am getting the below error when I checked out #681
<https://github.com/heartexlabs/label-studio/pull/681> [release/1.0.1] and
run sudo docker-compose up -d

Creating labelstudio_db_1 ...
Creating labelstudio_db_1 ... done
Creating labelstudio_app_1 ...
Creating labelstudio_app_1 ... error

ERROR: for labelstudio_app_1  Cannot start service app: OCI runtime create
failed: container_linux.go:349: starting container process caused "exec:
\"./deploy/wait-for-postgres.sh\": stat ./deploy/wait-for-postgres.sh: no
such file or directory": unknown

ERROR: for app  Cannot start service app: OCI runtime create failed:
container_linux.go:349: starting container process caused "exec:
\"./deploy/wait-for-postgres.sh\": stat ./deploy/wait-for-postgres.sh: no
such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by makseq** [comment]
@bharath4793 Could you check it again from the latest master commit?

**Comment by OmaymaS** [comment]
I get the same error

```
trv0089:label-studio osaid$ docker-compose up -d
Creating network "label-studio_default" with the default driver
Creating label-studio_db_1 ... done
Creating label-studio_app_1 ... error

ERROR: for label-studio_app_1  Cannot start service app: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./deploy/wait-for-postgres.sh\": stat ./deploy/wait-for-postgres.sh: no such file or directory": unknown

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"./deploy/wait-for-postgres.sh\": stat ./deploy/wait-for-postgres.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

using the latest version --> `Commit: 8d5e616220cdca0e7efea859408517786651c3de`
