### ISSUE TITLE
sync local storage error: 'cp950' codec can't decode byte 0xff in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by tingjhenjiang** [heartexlabs/label-studio#824]
**Describe the bug**
Sync local files storage error in file handler.

**To Reproduce**
1. create any project
2. Click on 'Settings/Cloud Storage/Add Source Storage/Storage Type: Local Files/Assign any path to Local path/Add storage'
3. Click "Sync storage"
4. See error below:

> RUNTIME ERROR
> 'cp950' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> Traceback (most recent call last):
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\site-packages\rest_framework\views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\site-packages\label_studio\io_storages\api.py", line 139, in post
>     storage.sync()
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\site-packages\label_studio\io_storages\base_models.py", line 99, in sync
>     self.scan_and_create_links()
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\site-packages\label_studio\io_storages\localfiles\models.py", line 59, in scan_and_create_links
>     return self._scan_and_create_links(LocalFilesImportStorageLink)
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\site-packages\label_studio\io_storages\base_models.py", line 76, in _scan_and_create_links
>     data = self.get_data(key)
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\site-packages\label_studio\io_storages\localfiles\models.py", line 53, in get_data
>     value = json.load(f)
>   File "d:\programdata\miniconda3\envs\labelstudio\lib\json\__init__.py", line 293, in load
>     return loads(fp.read(),
> UnicodeDecodeError: 'cp950' codec can't decode byte 0xff in position 0: illegal multibyte sequence
> 

**Expected behavior**
Expect no error

**Screenshots**
![image](https://user-images.githubusercontent.com/34190920/115295304-2dc04200-a18c-11eb-8e7c-921f9f8802ae.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Traditional Chinese
 - python 3.8 under conda 4.10.1 env
 - label-studio 1.0.1

**Additional context**
no any other context.

**Comment by makseq** [comment]
@tingjhenjiang could you try LS from the master branch on github? I hope we fixed this bug in the latest commits.

**Comment by tingjhenjiang** [comment]
Hello @makseq , after a try on the last commit, and after some adjustment, no clear error messages appear.
But the import process does not work well: nothing imported.
Below is my file structure:
- coffee-beans (at F:\coffee-beans\)
- - ABC_good1.xml
- - ABC_bad1.xml
- labels
- images
- - bad
- - - ABC_good1.jpg
- - good
- - - ABC_bad1.jpg

The settings are:
![image](https://user-images.githubusercontent.com/34190920/115501519-f04fd780-a2a5-11eb-8cb3-909f884faa1f.png)
Sync results are:
![image](https://user-images.githubusercontent.com/34190920/115501541-fa71d600-a2a5-11eb-811c-5874a63ea791.png)

Tried on either option "Treat every bucket object as a source file is on or off.

**Comment by tingjhenjiang** [comment]
addition:

if local path is set to "F:\coffee-beans" or "F:\\coffee-beans" and "Treat every bucket object as a source file" is **OFF**, error message is 

> Traceback (most recent call last):
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\base_models.py", line 82, in _scan_and_create_links
>     data = self.get_data(key)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\localfiles\models.py", line 58, in get_data
>     value = json.load(f)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\lib\json\__init__.py", line 293, in load
>     return loads(fp.read(),
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\lib\codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\lib\site-packages\rest_framework\views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\api.py", line 139, in post
>     storage.sync()
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\base_models.py", line 144, in sync
>     self.scan_and_create_links()
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\localfiles\models.py", line 64, in scan_and_create_links
>     return self._scan_and_create_links(LocalFilesImportStorageLink)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\base_models.py", line 85, in _scan_and_create_links
>     raise ValueError(
> ValueError: Error loading JSON from file "F:\coffee-beans\images\bad\IMAG0605.jpg".
> If you're trying to import non-JSON data (images, audio, text, etc.), edit storage settings and enable "Treat every bucket object as a source file"


If local path is "F:\coffee-beans" or "F:\\coffee-beans" and "Treat every bucket object as a source file" is **ON**, error message is:
> Traceback (most recent call last):
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\lib\site-packages\rest_framework\views.py", line 506, in dispatch
>     response = handler(request, *args, **kwargs)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\api.py", line 139, in post
>     storage.sync()
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\base_models.py", line 144, in sync
>     self.scan_and_create_links()
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\localfiles\models.py", line 64, in scan_and_create_links
>     return self._scan_and_create_links(LocalFilesImportStorageLink)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\base_models.py", line 82, in _scan_and_create_links
>     data = self.get_data(key)
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\label-studio\label_studio\io_storages\localfiles\models.py", line 55, in get_data
>     relative_path = str(path.relative_to(document_root))
>   File "D:\ProgramData\Miniconda3\envs\labelstudio\lib\pathlib.py", line 907, in relative_to
>     raise ValueError("{!r} does not start with {!r}"
> ValueError: 'F:\\coffee-beans\\images\\bad\\IMAG0605.jpg' does not start with '\\'

**Comment by makseq** [comment]
@tingjhenjiang what if you try to insert `.*jpg` inside of `File filter regex` ?

**Comment by makseq** [comment]
@tingjhenjiang Also you should try to setup environment var before LS start: 
LOCAL_FILES_DOCUMENT_ROOT=F:\

**Comment by tingjhenjiang** [comment]
Hello, I've set env var as follows:
![圖片](https://user-images.githubusercontent.com/34190920/116412445-48b84380-a869-11eb-8414-db2b5ef64720.png)
![圖片](https://user-images.githubusercontent.com/34190920/116412780-9765dd80-a869-11eb-8f9b-584217be3b5c.png)
and tried:
![圖片](https://user-images.githubusercontent.com/34190920/116412856-a8165380-a869-11eb-91de-babb55c4ea52.png)

all of them Synced 0 task(s)

**Comment by tingjhenjiang** [comment]
Hello,
I've cross-validated that setting other env vars such as LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true in my Windows environment variables(settings/advanced system configuration/environment variables) does not make label studio turning off the sign-up page.
Is the Synced 0 task(s) error occurs due to a wrong setting?
May I set the label studio env var by command-line arguments?

**Comment by makseq** [comment]
1. This option doesn't hide sign up page, it only disables sign up logic.
2. What wrong seeing do you mean?
3. You can set the most parameters via command line, but not all the parameters.

**Comment by zhimin-z** [comment]
This happens again. Take a screenshot:
![image](https://user-images.githubusercontent.com/8592144/142631323-0335d712-bf07-4e4b-bb2d-965820ca1914.png)
To replicate this, allow me to upload the text csv file here.
[mlflow.csv](https://github.com/heartexlabs/label-studio/files/7570559/mlflow.csv)
