### ISSUE TITLE
ML coco example does not show any predictions result

### ISSUE THREAD

**Issue by joul55320** [heartexlabs/label-studio#849]
**Describe the bug**
I connected the coco example to LS,
and I select "Object Detection with Bounding Boxes".

When I import mmdetection demo image,
in label interface, doesn't show any predictions result.

**To Reproduce**

I followed this guide to install and create ML for LS.
1. label-studio-ml start coco --with config_file=Path/ to /faster_rcnn_r50_fpn_iou_1x_coco.py 
checkpoint_file=Path / to /faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Label Studio Version [e.g. 0.8.0]

**Additional context**

**Comment by makseq** [comment]
@joul55320 Could your share ML backend logs?

**Comment by chriscramer** [comment]
FWIW, I've been dealing with a similar issue.  On my end, it seems that the ML backend is getting an image or image_url and has no way to access that URL.  

```
[2021-04-26 13:56:22,661] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/Users/cec2/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/Users/cec2/label-studio-ml-backend/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/Users/cec2/label-studio-ml-backend/label_studio_ml/model.py", line 273, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/Users/cec2/lsread/my_ml_backend/show_image.py", line 244, in predict
    get_local_path(task['data'][self.value])
  File "/Users/cec2/lsread/my_ml_backend/show_image.py", line 204, in get_local_path
    r = requests.get(url, stream=True)
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/data/upload/segmentation_trial_00017.jpeg': No schema supplied. Perhaps you meant http:///data/upload/segmentation_trial_00017.jpeg?
```

So, in this example, the URL was /data/upload/segmentation_trial_00017.jpeg, but there was no service/server/port attached to the URL.  To fix this, I tried to hardcode the path `http://localhost:8080` in front of the URL.  That gave me a permissions issue:

```
[2021-04-26 13:57:17,434] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
  File "/Users/cec2/label-studio-ml-backend/label_studio_ml/exceptions.py", line 39, in exception_f
    return f(*args, **kwargs)
  File "/Users/cec2/label-studio-ml-backend/label_studio_ml/api.py", line 31, in _predict
    predictions, model = _manager.predict(tasks, project, label_config, force_reload, try_fetch, **params)
  File "/Users/cec2/label-studio-ml-backend/label_studio_ml/model.py", line 273, in predict
    predictions = m.model.predict(tasks, **kwargs)
  File "/Users/cec2/lsread/my_ml_backend/show_image.py", line 244, in predict
    get_local_path(task['data'][self.value])
  File "/Users/cec2/lsread/my_ml_backend/show_image.py", line 205, in get_local_path
    r.raise_for_status()
  File "/Users/cec2/opt/anaconda3/envs/images/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8080/data/upload/segmentation_trial_00054.jpeg
```

**Comment by joul55320** [comment]
@chriscramer :
Oh yeah! I also find this issue, look like is the image path was wrong, so make model can not read the image?

**Comment by joul55320** [comment]
@chriscramer :

I modified "label-studio-ml-backend/label_studio_ml/utils.py" file, 

at line 112   
- filepath = os.path.join(cache_dir, url_hash + '__' + url_filename)
+ local_dir = "/home/<user>/.local/share/label-studio/media/upload"
+ filepath = os.path.join(local_dir, url_filename)


It;s work for me, maybe you can try this way.

**Comment by niklub** [comment]
Hey, guys,
Please check [this comment](https://github.com/heartexlabs/label-studio-ml-backend/issues/8#issuecomment-827602100)
