### ISSUE TITLE
KeyError: 'from_name' when deleting tasks

### ISSUE THREAD

**Issue by bethard** [heartexlabs/label-studio#895]
**Describe the bug**
I tried to select all tasks then "Delete Tasks". After I hit "Ok" on the "Destructive Action" dialog, no tasks are deleted. At the command line, the following error trace shows:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/label_studio/data_manager/api.py", line 339, in post
    result = perform_action(action_id, project, queryset, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/label_studio/data_manager/actions/__init__.py", line 90, in perform_action
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/label_studio/data_manager/actions/__init__.py", line 86, in perform_action
    result = _actions[action_id]['entry_point'](project, queryset, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/label_studio/data_manager/actions/basic.py", line 18, in delete_tasks
    queryset.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/db/models/query.py", line 747, in delete
    deleted, _rows_count = collector.delete()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/db/models/deletion.py", line 405, in delete
    sender=model, instance=obj, using=self.using
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in send
    for receiver in self._live_receivers(sender)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 179, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/label_studio/tasks/models.py", line 412, in remove_project_summary_annotations_and_is_labeled
    summary.remove_created_annotations_and_labels([instance])
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/label_studio/projects/models.py", line 808, in remove_created_annotations_and_labels
    from_name = result['from_name']
KeyError: 'from_name'
```

**To Reproduce**
I believe this happens when a `Relation` has been annotated, and I believe the problem is here:
https://github.com/heartexlabs/label-studio/blob/master/label_studio/projects/models.py#L752
As far as I can tell, `Relation` annotations do not have any `from_name` and instead look something like:
```
{"from_id": "HIymEToFvn", "to_id": "82_q3ASlne", "type": "relation", "direction": "right", "labels": ["Sub-Interval"]}
```

**Expected behavior**
Deleting all tasks should delete all tasks.

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Label Studio Version: 1.0.1

**Comment by bethard** [comment]
Indeed, I can confirm that if I add a useless `"from_name": ""` to all relations, "Delete Tasks" works again.

**Comment by bethard** [comment]
Yes, I can confirm that if I make that change locally, I can delete relations.
