### ISSUE TITLE
Unable to import file from GCS storage

### ISSUE THREAD

**Issue by jagan1333** [heartexlabs/label-studio#937]
Hello, I've added GCS cloud storage to import files, When I click Sync it says synced 5task(s), but I'm unable to view those images, when I checked the Container logs I see below error:

ERROR:
[18/May/2021 17:24:31] "PATCH /api/dm/views/4?project=2 HTTP/1.1" 200 499
[2021-05-18 17:24:31,876] [core.utils.common::custom_exception_handler::85] [ERROR] 6e858289-57ad-4238-9bc2-f11b1d7c079f Error calling the IAM signBytes API:                                                                                 b'{\n  "error": {\n    "code": 403,\n    "message": "Request had insufficient authentication scopes.",\n    "status": "PERMISSION_DENIED",\n    "details": [                                                                                \n      {\n        "@type": "type.googleapis.com/google.rpc.ErrorInfo",\n        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",\n        "domain": "googleapis.                                                                                com",\n        "metadata": {\n          "service": "iamcredentials.googleapis.com",\n          "method": "google.iam.credentials.v1.IAMCredentials.SignBlob"\                                                                                n        }\n      }\n    ]\n  }\n}\n'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/label-studio/label_studio/data_manager/api.py", line 132, in tasks
    return self.get_paginated_response(serializer.data)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 663, in to_representation
    return [
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/label-studio/label_studio/tasks/serializers.py", line 144, in to_representation
    instance.data = instance.resolve_uri(instance.data, proxy=self.context.get('proxy', False))
  File "/label-studio/label_studio/tasks/models.py", line 139, in resolve_uri
    return storage.resolve_task_data_uri(task_data)
  File "/label-studio/label_studio/io_storages/base_models.py", line 68, in resolve_task_data_uri
    resolved_uri = self.resolve_uri(data)
  File "/label-studio/label_studio/io_storages/gcs/models.py", line 159, in resolve_uri
    resolved_uri = self.resolve_gs(uri)
  File "/label-studio/label_studio/io_storages/gcs/models.py", line 103, in resolve_gs
    return self.python_cloud_function_get_signed_url(bucket_name, key)
  File "/label-studio/label_studio/io_storages/gcs/models.py", line 151, in python_cloud_function_get_signed_url
    signed_url = signed_blob_path.generate_signed_url(expires_at_ms, credentials=signing_credentials, version="v4")
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/blob.py", line 551, in generate_signed_url
    return helper(
  File "/usr/local/lib/python3.8/dist-packages/google/cloud/storage/_signing.py", line 622, in generate_signed_url_v4
    signature_bytes = credentials.sign_bytes(string_to_sign.encode("ascii"))
  File "/usr/local/lib/python3.8/dist-packages/google/auth/compute_engine/credentials.py", line 404, in sign_bytes
    return self._signer.sign(message)
  File "/usr/local/lib/python3.8/dist-packages/google/auth/iam.py", line 99, in sign
    response = self._make_signing_request(message)
  File "/usr/local/lib/python3.8/dist-packages/google/auth/iam.py", line 81, in _make_signing_request
    raise exceptions.TransportError(
google.auth.exceptions.TransportError: Error calling the IAM signBytes API: b'{\n  "error": {\n    "code": 403,\n    "message": "Request had insufficient aut                                                                                hentication scopes.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.ErrorInfo",\n        "                                                                                reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",\n        "domain": "googleapis.com",\n        "metadata": {\n          "service": "iamcredentials.googleapis.com"                                                                                ,\n          "method": "google.iam.credentials.v1.IAMCredentials.SignBlob"\n        }\n      }\n    ]\n  }\n}\n'
[2021-05-18 17:24:31,882] [django.request::log_response::224] [ERROR] Internal Server Error: /api/dm/views/4/tasks/
[18/May/2021 17:24:31] "GET /api/dm/views/4/tasks?page=1&page_size=30&project=2 HTTP/1.1" 500 4009

I've added GOOGLE_APPLICATION_CREDENTIALS with the service account which has storage admin permission.

I faced similar issue in previous version as well and i've issue created #614 

Following is the screenshot of bucket settings,
![image](https://user-images.githubusercontent.com/30555574/118697833-5a1fba80-b82d-11eb-961d-c98f5550318d.png)

**Comment by jagan1333** [comment]
Same issue even when I install label studio from pip...
[19/May/2021 13:59:32] "PATCH /api/dm/views/1?project=1 HTTP/1.1" 200 578
[2021-05-19 13:59:33,385] [core.utils.common::custom_exception_handler::85] [ERROR] e68db48b-55a6-44b4-9e48-ca2302b84dd9 Error calling the IAM signBytes API: b'{\n  "error": {\n    "code": 403,\n    "message": "Request had insufficient authentication scopes.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.ErrorInfo",\n        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",\n        "domain": "googleapis.com",\n        "metadata": {\n          "method": "google.iam.credentials.v1.IAMCredentials.SignBlob",\n          "service": "iamcredentials.googleapis.com"\n        }\n      }\n    ]\n  }\n}\n'
Traceback (most recent call last):
  File "/root/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/env/lib/python3.6/site-packages/label_studio/data_manager/api.py", line 133, in tasks
    return self.get_paginated_response(serializer.data)
  File "/root/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 745, in data
    ret = super().data
  File "/root/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
File "/root/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/root/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 664, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/root/env/lib/python3.6/site-packages/label_studio/tasks/serializers.py", line 149, in to_representation
    instance.data = instance.resolve_uri(instance.data, proxy=self.context.get('proxy', False))
  File "/root/env/lib/python3.6/site-packages/label_studio/tasks/models.py", line 135, in resolve_uri
    return storage.resolve_task_data_uri(task_data)
  File "/root/env/lib/python3.6/site-packages/label_studio/io_storages/base_models.py", line 61, in resolve_task_data_uri
    resolved_uri = self.resolve_uri(data)
  File "/root/env/lib/python3.6/site-packages/label_studio/io_storages/gcs/models.py", line 159, in resolve_uri
    resolved_uri = self.resolve_gs(uri)
  File "/root/env/lib/python3.6/site-packages/label_studio/io_storages/gcs/models.py", line 103, in resolve_gs
    return self.python_cloud_function_get_signed_url(bucket_name, key)
  File "/root/env/lib/python3.6/site-packages/label_studio/io_storages/gcs/models.py", line 151, in python_cloud_function_get_signed_url
    signed_url = signed_blob_path.generate_signed_url(expires_at_ms, credentials=signing_credentials, version="v4")
  File "/root/env/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 565, in generate_signed_url
    access_token=access_token,
  File "/root/env/lib/python3.6/site-packages/google/cloud/storage/_signing.py", line 622, in generate_signed_url_v4
    signature_bytes = credentials.sign_bytes(string_to_sign.encode("ascii"))
  File "/root/env/lib/python3.6/site-packages/google/auth/compute_engine/credentials.py", line 404, in sign_bytes
    return self._signer.sign(message)
  File "/root/env/lib/python3.6/site-packages/google/auth/iam.py", line 99, in sign
    response = self._make_signing_request(message)
  File "/root/env/lib/python3.6/site-packages/google/auth/iam.py", line 82, in _make_signing_request
    "Error calling the IAM signBytes API: {}".format(response.data)
google.auth.exceptions.TransportError: Error calling the IAM signBytes API: b'{\n  "error": {\n    "code": 403,\n    "message": "Request had insufficient authentication scopes.",\n    "status": "PERMISSION_DENIED",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.ErrorInfo",\n        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",\n        "domain": "googleapis.com",\n        "metadata": {\n          "method": "google.iam.credentials.v1.IAMCredentials.SignBlob",\n          "service": "iamcredentials.googleapis.com"\n        }\n      }\n    ]\n  }\n}\n'
[2021-05-19 13:59:33,389] [django.request::log_response::230] [ERROR] Internal Server Error: /api/dm/views/1/tasks/
[19/May/2021 13:59:33] "GET /api/dm/views/1/tasks?page=1&page_size=30&project=1 HTTP/1.1" 500 4259

**Comment by niklub** [comment]
Hi, @jagan1333 ! Could you please check that your service account contains `Service Account Token Creator` role?

**Comment by jagan1333** [comment]
Hi @niklub Yes it has. I've set up the service account json key to GOOGLE_APPLICATION_CREDENTIALS. Is this is the way to use for label studio or anything else I'm missing. Thanks

**Comment by jagan1333** [comment]
Hello guys any suggestions ?

**Comment by smoreface** [comment]
@jagan1333 Does your account have `storage.buckets.get` access as well? Sorry for the delay, I wasn't sure what else could be causing the issue.

**Comment by rexlow** [comment]
@jagan1333 I have exactly the error yesterday and I manage to solve it with the below approach. It depends on where and how do you publish the app. My mistake was deploying without specifying the `--service-account` flag.

For me, I decoupled `label-studio`, build the docker image (with some customizations) and deploy it with `gcloud run deploy`. I was deploying without specifying the correct service account file. 

First, you will need to make sure your service account has the following roles

`Service Account Token Creator, Storage Object Viewer`

Then, verify that it is working locally.  [Activate the service account](https://cloud.google.com/sdk/gcloud/reference/auth/activate-service-account) in your local machine, start the app via `label-studio`. Go to `Settings > Cloud Storage > Add Source Storage` and insert the service account content to the `Google Application Credentials`. Finally, check the connection and go back to the project page. If your service account is indeed having the required `iam` permissions, it will work.

To deploy,

```
gcloud run deploy $APP_NAME \
    --project $PROJECT \
    --platform managed \
    --region asia-southeast1 \
    --image $IMAGE_NAME \
    --set-env-vars DJANGO_DB=default \
    --set-env-vars LABEL_STUDIO_ONE_CLICK_DEPLOY=1 \
    --set-env-vars POSTGRE_NAME=${LABEL_STUDIO_DB_NAME} \
    --set-env-vars POSTGRE_USER=${LABEL_STUDIO_DB_USER} \
    --set-env-vars POSTGRE_PASSWORD=${LABEL_STUDIO_DB_PASS} \
    --set-env-vars POSTGRE_PORT=${LABEL_STUDIO_DB_PORT} \
    --set-env-vars POSTGRE_HOST=${LABEL_STUDIO_DB_HOST} \
    --set-env-vars LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME} \
    --set-env-vars LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD} \
    --set-env-vars LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true \
    --allow-unauthenticated \
    --service-account ${LABEL_STUDIO_SERVICE_ACCOUNT}
```

**Comment by makseq** [comment]
@smoreface what do you think, should we add the last post instructions to our troubleshooting for storages?
