### ISSUE TITLE
Error creating project

### ISSUE THREAD

**Issue by gatagat** [heartexlabs/label-studio#942]
**Describe the bug**
After installing from pypi, label-studio crashes on project initialization.

**To Reproduce**
1. Install from pypi following the readme: https://github.com/heartexlabs/label-studio#install-locally-with-pip
2. Run `label-studio init test`

**Expected behavior**
No errors during the init of a project.

**Screenshots**
```
label-studio init test
=> Database and media directory: xyz/.local/share/label-studio
=> Static URL is set to: /static/

Please enter default user email, or press Enter to use "default_user@localhost"
Email:
Default user password:
Traceback (most recent call last):
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: project.template_used_id
                                                                                                                     
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxx/label-studio/bin/label-studio", line 8, in <module>
    sys.exit(main())
  File "xxx/label-studio/lib/python3.8/site-packages/label_studio/server.py", line 261, in main
    _init(input_args, config)
  File "xxx/label-studio/lib/python3.8/site-packages/label_studio/server.py", line 138, in _init
    _create_project(
  File "xxx/label-studio/lib/python3.8/site-packages/label_studio/server.py", line 70, in _create_project
    project = Project.objects.filter(title=title).first()
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 678, in first
    for obj in (self if self.ordered else self.order_by('pk'))[:1]:
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()                                                                                                  
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "xxx/label-studio/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: project.template_used_id
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Label Studio 1.0.1 (from pypi)

**Comment by gatagat** [comment]
Sorry for the noise, deleting the ~/.local/share/label-studio directory and starting over, solved the issue.
